"""Append A1 vocabulary to german_vocab_session_new.xlsx (the master file).

A1 vocabulary is curated against the Goethe Start Deutsch 1 / Fit in Deutsch 1
official word lists (~650 essential A1 words). Each row carries full info:
  German term | POS | Article | Japanese | English | Appearance_Count |
  Präteritum  | Partizip II | Plural | Notes | Tags

Tags are computed automatically (theme + POS + level=A1).
"""

from __future__ import annotations
import re
import sys
from pathlib import Path

from openpyxl import load_workbook

sys.stdout.reconfigure(encoding="utf-8")

MASTER = Path(__file__).resolve().parent / "german_vocab_master.xlsx"
SHEET = "Session Vokabeln"
LEVEL = "A1"

# Entry format:
# (German, POS, Article, Japanese, English, Präteritum, Partizip II, Plural, Notes)
#
# Conventions:
#   - For nouns the German cell includes the article in lower form ("der Tag").
#     The Article cell repeats just the article ("der").
#   - For verbs Präteritum & Partizip II are filled in. For irregular verbs
#     auxiliary is in Partizip II ("ist gegangen" / "hat gegessen").
#   - For nouns Plural is the full plural form ("die Tage", "die Häuser").
#   - "" (empty) for fields that do not apply (verb has no article/plural, etc.)
A1_ENTRIES: list[tuple[str, str, str, str, str, str, str, str, str]] = [
    # ---------- Greetings & basics ----------
    ("Hallo", "interj", "", "こんにちは／やあ", "hello, hi", "", "", "", "casual greeting"),
    ("Guten Tag", "phrase", "", "こんにちは", "good day, hello", "", "", "", "daytime greeting"),
    ("Guten Morgen", "phrase", "", "おはようございます", "good morning", "", "", "", ""),
    ("Guten Abend", "phrase", "", "こんばんは", "good evening", "", "", "", ""),
    ("Gute Nacht", "phrase", "", "おやすみなさい", "good night", "", "", "", ""),
    ("Tschüs", "interj", "", "じゃあね／バイバイ", "bye", "", "", "", "casual farewell"),
    ("Auf Wiedersehen", "phrase", "", "さようなら", "goodbye", "", "", "", "formal farewell"),
    ("bitte", "adv", "", "どうぞ／お願いします", "please, you're welcome", "", "", "", ""),
    ("danke", "interj", "", "ありがとう", "thank you", "", "", "", ""),
    ("danke schön", "phrase", "", "どうもありがとう", "thank you very much", "", "", "", ""),
    ("ja", "adv", "", "はい", "yes", "", "", "", ""),
    ("nein", "adv", "", "いいえ", "no", "", "", "", ""),
    ("Entschuldigung", "noun", "die", "すみません／お詫び", "excuse me, sorry", "", "", "die Entschuldigungen", ""),
    ("Verzeihung", "noun", "die", "失礼", "pardon", "", "", "", ""),
    ("okay", "interj", "", "オーケー", "okay", "", "", "", ""),

    # ---------- Personal pronouns & articles ----------
    ("ich", "pron", "", "私", "I", "", "", "", ""),
    ("du", "pron", "", "あなた（親しい）", "you (informal)", "", "", "", ""),
    ("er", "pron", "", "彼", "he", "", "", "", ""),
    ("sie", "pron", "", "彼女／彼ら／あなた（敬）", "she / they / you (formal)", "", "", "", ""),
    ("es", "pron", "", "それ", "it", "", "", "", ""),
    ("wir", "pron", "", "私たち", "we", "", "", "", ""),
    ("ihr", "pron", "", "あなたたち", "you (plural)", "", "", "", ""),
    ("Sie", "pron", "", "あなた（敬称）", "you (formal)", "", "", "", ""),
    ("mein", "pron", "", "私の", "my", "", "", "", "possessive"),
    ("dein", "pron", "", "あなたの", "your (informal)", "", "", "", ""),
    ("sein", "pron", "", "彼の", "his", "", "", "", ""),
    ("ihr", "pron", "", "彼女の／彼らの", "her / their", "", "", "", ""),
    ("unser", "pron", "", "私たちの", "our", "", "", "", ""),
    ("euer", "pron", "", "あなたたちの", "your (plural)", "", "", "", ""),

    # ---------- Question words ----------
    ("wer", "pron", "", "誰", "who", "", "", "", ""),
    ("was", "pron", "", "何", "what", "", "", "", ""),
    ("wo", "adv", "", "どこ", "where", "", "", "", ""),
    ("wann", "adv", "", "いつ", "when", "", "", "", ""),
    ("wie", "adv", "", "どう／どのように", "how", "", "", "", ""),
    ("warum", "adv", "", "なぜ", "why", "", "", "", ""),
    ("woher", "adv", "", "どこから", "where from", "", "", "", ""),
    ("wohin", "adv", "", "どこへ", "where to", "", "", "", ""),
    ("welch-", "pron", "", "どの", "which", "", "", "", "inflected"),
    ("wie viel", "phrase", "", "いくつ／いくら", "how much / how many", "", "", "", ""),

    # ---------- Numbers ----------
    ("null", "num", "", "ゼロ", "zero", "", "", "", ""),
    ("eins", "num", "", "1", "one", "", "", "", ""),
    ("zwei", "num", "", "2", "two", "", "", "", ""),
    ("drei", "num", "", "3", "three", "", "", "", ""),
    ("vier", "num", "", "4", "four", "", "", "", ""),
    ("fünf", "num", "", "5", "five", "", "", "", ""),
    ("sechs", "num", "", "6", "six", "", "", "", ""),
    ("sieben", "num", "", "7", "seven", "", "", "", ""),
    ("acht", "num", "", "8", "eight", "", "", "", ""),
    ("neun", "num", "", "9", "nine", "", "", "", ""),
    ("zehn", "num", "", "10", "ten", "", "", "", ""),
    ("elf", "num", "", "11", "eleven", "", "", "", ""),
    ("zwölf", "num", "", "12", "twelve", "", "", "", ""),
    ("dreizehn", "num", "", "13", "thirteen", "", "", "", ""),
    ("vierzehn", "num", "", "14", "fourteen", "", "", "", ""),
    ("fünfzehn", "num", "", "15", "fifteen", "", "", "", ""),
    ("sechzehn", "num", "", "16", "sixteen", "", "", "", ""),
    ("siebzehn", "num", "", "17", "seventeen", "", "", "", ""),
    ("achtzehn", "num", "", "18", "eighteen", "", "", "", ""),
    ("neunzehn", "num", "", "19", "nineteen", "", "", "", ""),
    ("zwanzig", "num", "", "20", "twenty", "", "", "", ""),
    ("dreißig", "num", "", "30", "thirty", "", "", "", ""),
    ("vierzig", "num", "", "40", "forty", "", "", "", ""),
    ("fünfzig", "num", "", "50", "fifty", "", "", "", ""),
    ("sechzig", "num", "", "60", "sixty", "", "", "", ""),
    ("siebzig", "num", "", "70", "seventy", "", "", "", ""),
    ("achtzig", "num", "", "80", "eighty", "", "", "", ""),
    ("neunzig", "num", "", "90", "ninety", "", "", "", ""),
    ("hundert", "num", "", "100", "hundred", "", "", "", ""),
    ("tausend", "num", "", "1000", "thousand", "", "", "", ""),

    # ---------- Time: days / months / seasons ----------
    ("der Montag", "noun", "der", "月曜日", "Monday", "", "", "die Montage", ""),
    ("der Dienstag", "noun", "der", "火曜日", "Tuesday", "", "", "die Dienstage", ""),
    ("der Mittwoch", "noun", "der", "水曜日", "Wednesday", "", "", "die Mittwoche", ""),
    ("der Donnerstag", "noun", "der", "木曜日", "Thursday", "", "", "die Donnerstage", ""),
    ("der Freitag", "noun", "der", "金曜日", "Friday", "", "", "die Freitage", ""),
    ("der Samstag", "noun", "der", "土曜日", "Saturday", "", "", "die Samstage", "south DE"),
    ("der Sonnabend", "noun", "der", "土曜日", "Saturday", "", "", "die Sonnabende", "north DE"),
    ("der Sonntag", "noun", "der", "日曜日", "Sunday", "", "", "die Sonntage", ""),
    ("der Tag", "noun", "der", "日", "day", "", "", "die Tage", ""),
    ("die Woche", "noun", "die", "週", "week", "", "", "die Wochen", ""),
    ("der Monat", "noun", "der", "月", "month", "", "", "die Monate", ""),
    ("das Jahr", "noun", "das", "年", "year", "", "", "die Jahre", ""),
    ("das Wochenende", "noun", "das", "週末", "weekend", "", "", "die Wochenenden", ""),
    ("der Januar", "noun", "der", "1月", "January", "", "", "", ""),
    ("der Februar", "noun", "der", "2月", "February", "", "", "", ""),
    ("der März", "noun", "der", "3月", "March", "", "", "", ""),
    ("der April", "noun", "der", "4月", "April", "", "", "", ""),
    ("der Mai", "noun", "der", "5月", "May", "", "", "", ""),
    ("der Juni", "noun", "der", "6月", "June", "", "", "", ""),
    ("der Juli", "noun", "der", "7月", "July", "", "", "", ""),
    ("der August", "noun", "der", "8月", "August", "", "", "", ""),
    ("der September", "noun", "der", "9月", "September", "", "", "", ""),
    ("der Oktober", "noun", "der", "10月", "October", "", "", "", ""),
    ("der November", "noun", "der", "11月", "November", "", "", "", ""),
    ("der Dezember", "noun", "der", "12月", "December", "", "", "", ""),
    ("der Frühling", "noun", "der", "春", "spring", "", "", "die Frühlinge", ""),
    ("der Sommer", "noun", "der", "夏", "summer", "", "", "die Sommer", ""),
    ("der Herbst", "noun", "der", "秋", "autumn", "", "", "die Herbste", ""),
    ("der Winter", "noun", "der", "冬", "winter", "", "", "die Winter", ""),
    ("heute", "adv", "", "今日", "today", "", "", "", ""),
    ("morgen", "adv", "", "明日", "tomorrow", "", "", "", ""),
    ("gestern", "adv", "", "昨日", "yesterday", "", "", "", ""),
    ("vorgestern", "adv", "", "おととい", "day before yesterday", "", "", "", ""),
    ("übermorgen", "adv", "", "あさって", "day after tomorrow", "", "", "", ""),
    ("jetzt", "adv", "", "今", "now", "", "", "", ""),
    ("dann", "adv", "", "それから", "then", "", "", "", ""),
    ("früh", "adj", "", "早い", "early", "", "", "", ""),
    ("spät", "adj", "", "遅い", "late", "", "", "", ""),
    ("der Morgen", "noun", "der", "朝", "morning", "", "", "die Morgen", ""),
    ("der Vormittag", "noun", "der", "午前", "morning, forenoon", "", "", "die Vormittage", ""),
    ("der Mittag", "noun", "der", "正午", "noon", "", "", "die Mittage", ""),
    ("der Nachmittag", "noun", "der", "午後", "afternoon", "", "", "die Nachmittage", ""),
    ("der Abend", "noun", "der", "夕方", "evening", "", "", "die Abende", ""),
    ("die Nacht", "noun", "die", "夜", "night", "", "", "die Nächte", ""),
    ("die Uhr", "noun", "die", "時計／〜時", "clock, hour", "", "", "die Uhren", ""),
    ("die Stunde", "noun", "die", "時間", "hour", "", "", "die Stunden", ""),
    ("die Minute", "noun", "die", "分", "minute", "", "", "die Minuten", ""),
    ("die Sekunde", "noun", "die", "秒", "second", "", "", "die Sekunden", ""),

    # ---------- Family ----------
    ("die Familie", "noun", "die", "家族", "family", "", "", "die Familien", ""),
    ("die Mutter", "noun", "die", "母", "mother", "", "", "die Mütter", ""),
    ("der Vater", "noun", "der", "父", "father", "", "", "die Väter", ""),
    ("die Eltern", "noun", "die", "両親", "parents", "", "", "", "plural only"),
    ("der Bruder", "noun", "der", "兄／弟", "brother", "", "", "die Brüder", ""),
    ("die Schwester", "noun", "die", "姉／妹", "sister", "", "", "die Schwestern", ""),
    ("die Geschwister", "noun", "die", "兄弟姉妹", "siblings", "", "", "", "plural"),
    ("der Sohn", "noun", "der", "息子", "son", "", "", "die Söhne", ""),
    ("die Tochter", "noun", "die", "娘", "daughter", "", "", "die Töchter", ""),
    ("das Kind", "noun", "das", "子供", "child", "", "", "die Kinder", ""),
    ("der Mann", "noun", "der", "男／夫", "man, husband", "", "", "die Männer", ""),
    ("die Frau", "noun", "die", "女／妻", "woman, wife", "", "", "die Frauen", ""),
    ("der Junge", "noun", "der", "男の子", "boy", "", "", "die Jungen", ""),
    ("das Mädchen", "noun", "das", "女の子", "girl", "", "", "die Mädchen", ""),
    ("der Großvater", "noun", "der", "祖父", "grandfather", "", "", "die Großväter", ""),
    ("die Großmutter", "noun", "die", "祖母", "grandmother", "", "", "die Großmütter", ""),
    ("die Großeltern", "noun", "die", "祖父母", "grandparents", "", "", "", "plural"),
    ("der Opa", "noun", "der", "おじいちゃん", "grandpa", "", "", "die Opas", ""),
    ("die Oma", "noun", "die", "おばあちゃん", "grandma", "", "", "die Omas", ""),
    ("der Onkel", "noun", "der", "おじ", "uncle", "", "", "die Onkel", ""),
    ("die Tante", "noun", "die", "おば", "aunt", "", "", "die Tanten", ""),
    ("der Cousin", "noun", "der", "いとこ（男）", "male cousin", "", "", "die Cousins", ""),
    ("die Cousine", "noun", "die", "いとこ（女）", "female cousin", "", "", "die Cousinen", ""),
    ("das Baby", "noun", "das", "赤ちゃん", "baby", "", "", "die Babys", ""),
    ("der Freund", "noun", "der", "友人（男）／彼氏", "friend, boyfriend", "", "", "die Freunde", ""),
    ("die Freundin", "noun", "die", "友人（女）／彼女", "friend, girlfriend", "", "", "die Freundinnen", ""),

    # ---------- Body parts ----------
    ("der Körper", "noun", "der", "体", "body", "", "", "die Körper", ""),
    ("der Kopf", "noun", "der", "頭", "head", "", "", "die Köpfe", ""),
    ("das Gesicht", "noun", "das", "顔", "face", "", "", "die Gesichter", ""),
    ("das Auge", "noun", "das", "目", "eye", "", "", "die Augen", ""),
    ("das Ohr", "noun", "das", "耳", "ear", "", "", "die Ohren", ""),
    ("die Nase", "noun", "die", "鼻", "nose", "", "", "die Nasen", ""),
    ("der Mund", "noun", "der", "口", "mouth", "", "", "die Münder", ""),
    ("der Zahn", "noun", "der", "歯", "tooth", "", "", "die Zähne", ""),
    ("das Haar", "noun", "das", "髪／毛", "hair", "", "", "die Haare", ""),
    ("der Hals", "noun", "der", "首", "neck, throat", "", "", "die Hälse", ""),
    ("die Schulter", "noun", "die", "肩", "shoulder", "", "", "die Schultern", ""),
    ("der Arm", "noun", "der", "腕", "arm", "", "", "die Arme", ""),
    ("die Hand", "noun", "die", "手", "hand", "", "", "die Hände", ""),
    ("der Finger", "noun", "der", "指", "finger", "", "", "die Finger", ""),
    ("der Bauch", "noun", "der", "腹", "belly, stomach", "", "", "die Bäuche", ""),
    ("der Rücken", "noun", "der", "背中", "back", "", "", "die Rücken", ""),
    ("das Bein", "noun", "das", "脚", "leg", "", "", "die Beine", ""),
    ("der Fuß", "noun", "der", "足", "foot", "", "", "die Füße", ""),

    # ---------- Colors ----------
    ("die Farbe", "noun", "die", "色", "color", "", "", "die Farben", ""),
    ("rot", "adj", "", "赤い", "red", "", "", "", ""),
    ("blau", "adj", "", "青い", "blue", "", "", "", ""),
    ("grün", "adj", "", "緑の", "green", "", "", "", ""),
    ("gelb", "adj", "", "黄色い", "yellow", "", "", "", ""),
    ("schwarz", "adj", "", "黒い", "black", "", "", "", ""),
    ("weiß", "adj", "", "白い", "white", "", "", "", ""),
    ("braun", "adj", "", "茶色の", "brown", "", "", "", ""),
    ("grau", "adj", "", "灰色の", "gray", "", "", "", ""),
    ("rosa", "adj", "", "ピンクの", "pink", "", "", "", "uninflected"),
    ("orange", "adj", "", "オレンジ色の", "orange", "", "", "", "uninflected"),
    ("lila", "adj", "", "紫の", "purple", "", "", "", "uninflected"),
    ("bunt", "adj", "", "カラフルな", "colorful", "", "", "", ""),
    ("hell", "adj", "", "明るい", "bright, light", "", "", "", ""),
    ("dunkel", "adj", "", "暗い", "dark", "", "", "", ""),

    # ---------- Food & drink ----------
    ("das Essen", "noun", "das", "食事／食べ物", "food, meal", "", "", "die Essen", ""),
    ("das Brot", "noun", "das", "パン", "bread", "", "", "die Brote", ""),
    ("das Brötchen", "noun", "das", "小型のパン", "bread roll", "", "", "die Brötchen", ""),
    ("die Butter", "noun", "die", "バター", "butter", "", "", "", "no plural"),
    ("der Käse", "noun", "der", "チーズ", "cheese", "", "", "die Käse", ""),
    ("die Wurst", "noun", "die", "ソーセージ", "sausage", "", "", "die Würste", ""),
    ("das Fleisch", "noun", "das", "肉", "meat", "", "", "", "no plural"),
    ("der Fisch", "noun", "der", "魚", "fish", "", "", "die Fische", ""),
    ("das Ei", "noun", "das", "卵", "egg", "", "", "die Eier", ""),
    ("die Milch", "noun", "die", "牛乳", "milk", "", "", "", "no plural"),
    ("das Wasser", "noun", "das", "水", "water", "", "", "die Wässer", ""),
    ("der Saft", "noun", "der", "ジュース", "juice", "", "", "die Säfte", ""),
    ("der Kaffee", "noun", "der", "コーヒー", "coffee", "", "", "die Kaffees", ""),
    ("der Tee", "noun", "der", "茶", "tea", "", "", "die Tees", ""),
    ("das Bier", "noun", "das", "ビール", "beer", "", "", "die Biere", ""),
    ("der Wein", "noun", "der", "ワイン", "wine", "", "", "die Weine", ""),
    ("das Obst", "noun", "das", "果物", "fruit", "", "", "", "collective"),
    ("der Apfel", "noun", "der", "りんご", "apple", "", "", "die Äpfel", ""),
    ("die Banane", "noun", "die", "バナナ", "banana", "", "", "die Bananen", ""),
    ("die Orange", "noun", "die", "オレンジ", "orange", "", "", "die Orangen", ""),
    ("das Gemüse", "noun", "das", "野菜", "vegetable", "", "", "die Gemüse", ""),
    ("die Tomate", "noun", "die", "トマト", "tomato", "", "", "die Tomaten", ""),
    ("die Kartoffel", "noun", "die", "じゃがいも", "potato", "", "", "die Kartoffeln", ""),
    ("der Salat", "noun", "der", "サラダ／レタス", "salad, lettuce", "", "", "die Salate", ""),
    ("die Suppe", "noun", "die", "スープ", "soup", "", "", "die Suppen", ""),
    ("der Reis", "noun", "der", "米", "rice", "", "", "", "no plural"),
    ("die Nudel", "noun", "die", "麺", "noodle", "", "", "die Nudeln", ""),
    ("der Kuchen", "noun", "der", "ケーキ", "cake", "", "", "die Kuchen", ""),
    ("die Schokolade", "noun", "die", "チョコレート", "chocolate", "", "", "die Schokoladen", ""),
    ("das Salz", "noun", "das", "塩", "salt", "", "", "die Salze", ""),
    ("der Zucker", "noun", "der", "砂糖", "sugar", "", "", "", "no plural"),
    ("das Frühstück", "noun", "das", "朝食", "breakfast", "", "", "die Frühstücke", ""),
    ("das Mittagessen", "noun", "das", "昼食", "lunch", "", "", "die Mittagessen", ""),
    ("das Abendessen", "noun", "das", "夕食", "dinner", "", "", "die Abendessen", ""),
    ("das Restaurant", "noun", "das", "レストラン", "restaurant", "", "", "die Restaurants", ""),
    ("das Café", "noun", "das", "カフェ", "café", "", "", "die Cafés", ""),

    # ---------- Clothing ----------
    ("die Kleidung", "noun", "die", "服", "clothing", "", "", "", "no plural typical"),
    ("das T-Shirt", "noun", "das", "Tシャツ", "T-shirt", "", "", "die T-Shirts", ""),
    ("das Hemd", "noun", "das", "シャツ", "shirt", "", "", "die Hemden", ""),
    ("die Bluse", "noun", "die", "ブラウス", "blouse", "", "", "die Blusen", ""),
    ("die Hose", "noun", "die", "ズボン", "trousers", "", "", "die Hosen", ""),
    ("der Rock", "noun", "der", "スカート", "skirt", "", "", "die Röcke", ""),
    ("das Kleid", "noun", "das", "ワンピース／ドレス", "dress", "", "", "die Kleider", ""),
    ("die Jacke", "noun", "die", "ジャケット", "jacket", "", "", "die Jacken", ""),
    ("der Mantel", "noun", "der", "コート", "coat", "", "", "die Mäntel", ""),
    ("der Pullover", "noun", "der", "セーター", "pullover", "", "", "die Pullover", ""),
    ("der Schuh", "noun", "der", "靴", "shoe", "", "", "die Schuhe", ""),
    ("die Socke", "noun", "die", "靴下", "sock", "", "", "die Socken", ""),
    ("der Hut", "noun", "der", "帽子", "hat", "", "", "die Hüte", ""),
    ("die Mütze", "noun", "die", "ニット帽", "cap", "", "", "die Mützen", ""),
    ("die Tasche", "noun", "die", "バッグ／ポケット", "bag, pocket", "", "", "die Taschen", ""),
    ("die Brille", "noun", "die", "メガネ", "glasses", "", "", "die Brillen", ""),

    # ---------- Home & furniture ----------
    ("das Haus", "noun", "das", "家", "house", "", "", "die Häuser", ""),
    ("die Wohnung", "noun", "die", "アパート", "apartment", "", "", "die Wohnungen", ""),
    ("das Zimmer", "noun", "das", "部屋", "room", "", "", "die Zimmer", ""),
    ("die Küche", "noun", "die", "キッチン", "kitchen", "", "", "die Küchen", ""),
    ("das Bad", "noun", "das", "風呂／浴室", "bathroom", "", "", "die Bäder", ""),
    ("das Schlafzimmer", "noun", "das", "寝室", "bedroom", "", "", "die Schlafzimmer", ""),
    ("das Wohnzimmer", "noun", "das", "リビング", "living room", "", "", "die Wohnzimmer", ""),
    ("die Toilette", "noun", "die", "トイレ", "toilet", "", "", "die Toiletten", ""),
    ("der Garten", "noun", "der", "庭", "garden", "", "", "die Gärten", ""),
    ("der Balkon", "noun", "der", "バルコニー", "balcony", "", "", "die Balkone", ""),
    ("der Tisch", "noun", "der", "テーブル／机", "table", "", "", "die Tische", ""),
    ("der Stuhl", "noun", "der", "椅子", "chair", "", "", "die Stühle", ""),
    ("das Bett", "noun", "das", "ベッド", "bed", "", "", "die Betten", ""),
    ("der Schrank", "noun", "der", "戸棚", "cupboard, wardrobe", "", "", "die Schränke", ""),
    ("die Lampe", "noun", "die", "ランプ", "lamp", "", "", "die Lampen", ""),
    ("die Tür", "noun", "die", "ドア", "door", "", "", "die Türen", ""),
    ("das Fenster", "noun", "das", "窓", "window", "", "", "die Fenster", ""),
    ("die Wand", "noun", "die", "壁", "wall", "", "", "die Wände", ""),
    ("der Boden", "noun", "der", "床", "floor", "", "", "die Böden", ""),
    ("der Schlüssel", "noun", "der", "鍵", "key", "", "", "die Schlüssel", ""),
    ("die Adresse", "noun", "die", "住所", "address", "", "", "die Adressen", ""),
    ("die Straße", "noun", "die", "通り／道", "street", "", "", "die Straßen", ""),
    ("die Hausnummer", "noun", "die", "番地", "house number", "", "", "die Hausnummern", ""),

    # ---------- Work & professions ----------
    ("die Arbeit", "noun", "die", "仕事", "work, job", "", "", "die Arbeiten", ""),
    ("der Beruf", "noun", "der", "職業", "profession", "", "", "die Berufe", ""),
    ("der Job", "noun", "der", "仕事", "job", "", "", "die Jobs", ""),
    ("das Büro", "noun", "das", "オフィス", "office", "", "", "die Büros", ""),
    ("die Firma", "noun", "die", "会社", "company", "", "", "die Firmen", ""),
    ("der Chef", "noun", "der", "上司（男）", "boss (m)", "", "", "die Chefs", ""),
    ("die Chefin", "noun", "die", "上司（女）", "boss (f)", "", "", "die Chefinnen", ""),
    ("der Kollege", "noun", "der", "同僚（男）", "colleague (m)", "", "", "die Kollegen", ""),
    ("die Kollegin", "noun", "die", "同僚（女）", "colleague (f)", "", "", "die Kolleginnen", ""),
    ("der Lehrer", "noun", "der", "教師（男）", "teacher (m)", "", "", "die Lehrer", ""),
    ("die Lehrerin", "noun", "die", "教師（女）", "teacher (f)", "", "", "die Lehrerinnen", ""),
    ("der Arzt", "noun", "der", "医者（男）", "doctor (m)", "", "", "die Ärzte", ""),
    ("die Ärztin", "noun", "die", "医者（女）", "doctor (f)", "", "", "die Ärztinnen", ""),
    ("der Student", "noun", "der", "学生（男）", "student (m)", "", "", "die Studenten", ""),
    ("die Studentin", "noun", "die", "学生（女）", "student (f)", "", "", "die Studentinnen", ""),
    ("der Schüler", "noun", "der", "生徒（男）", "pupil (m)", "", "", "die Schüler", ""),
    ("die Schülerin", "noun", "die", "生徒（女）", "pupil (f)", "", "", "die Schülerinnen", ""),
    ("der Verkäufer", "noun", "der", "店員（男）", "salesperson (m)", "", "", "die Verkäufer", ""),
    ("die Verkäuferin", "noun", "die", "店員（女）", "salesperson (f)", "", "", "die Verkäuferinnen", ""),
    ("der Polizist", "noun", "der", "警察官（男）", "police officer (m)", "", "", "die Polizisten", ""),
    ("der Ingenieur", "noun", "der", "技術者（男）", "engineer (m)", "", "", "die Ingenieure", ""),
    ("die Termin", "noun", "der", "予約／約束", "appointment", "", "", "die Termine", ""),

    # ---------- Travel & transport ----------
    ("die Reise", "noun", "die", "旅行", "trip", "", "", "die Reisen", ""),
    ("der Urlaub", "noun", "der", "休暇", "vacation", "", "", "die Urlaube", ""),
    ("die Ferien", "noun", "die", "休み", "holidays", "", "", "", "plural"),
    ("das Hotel", "noun", "das", "ホテル", "hotel", "", "", "die Hotels", ""),
    ("das Auto", "noun", "das", "車", "car", "", "", "die Autos", ""),
    ("der Bus", "noun", "der", "バス", "bus", "", "", "die Busse", ""),
    ("der Zug", "noun", "der", "電車", "train", "", "", "die Züge", ""),
    ("die Bahn", "noun", "die", "鉄道", "railway", "", "", "die Bahnen", ""),
    ("das Fahrrad", "noun", "das", "自転車", "bicycle", "", "", "die Fahrräder", ""),
    ("das Taxi", "noun", "das", "タクシー", "taxi", "", "", "die Taxis", ""),
    ("das Flugzeug", "noun", "das", "飛行機", "airplane", "", "", "die Flugzeuge", ""),
    ("der Flughafen", "noun", "der", "空港", "airport", "", "", "die Flughäfen", ""),
    ("der Bahnhof", "noun", "der", "駅", "train station", "", "", "die Bahnhöfe", ""),
    ("die Haltestelle", "noun", "die", "停留所", "bus stop", "", "", "die Haltestellen", ""),
    ("das Ticket", "noun", "das", "チケット", "ticket", "", "", "die Tickets", ""),
    ("die Fahrkarte", "noun", "die", "乗車券", "ticket", "", "", "die Fahrkarten", ""),
    ("der Pass", "noun", "der", "パスポート", "passport", "", "", "die Pässe", ""),
    ("der Koffer", "noun", "der", "スーツケース", "suitcase", "", "", "die Koffer", ""),

    # ---------- School & study ----------
    ("die Schule", "noun", "die", "学校", "school", "", "", "die Schulen", ""),
    ("die Klasse", "noun", "die", "クラス", "class", "", "", "die Klassen", ""),
    ("der Unterricht", "noun", "der", "授業", "lesson", "", "", "", "no plural"),
    ("die Universität", "noun", "die", "大学", "university", "", "", "die Universitäten", ""),
    ("die Hausaufgabe", "noun", "die", "宿題", "homework", "", "", "die Hausaufgaben", ""),
    ("die Prüfung", "noun", "die", "試験", "exam", "", "", "die Prüfungen", ""),
    ("der Test", "noun", "der", "テスト", "test", "", "", "die Tests", ""),
    ("das Buch", "noun", "das", "本", "book", "", "", "die Bücher", ""),
    ("das Heft", "noun", "das", "ノート", "notebook", "", "", "die Hefte", ""),
    ("der Stift", "noun", "der", "ペン", "pen", "", "", "die Stifte", ""),
    ("der Kugelschreiber", "noun", "der", "ボールペン", "ballpoint pen", "", "", "die Kugelschreiber", ""),
    ("der Bleistift", "noun", "der", "鉛筆", "pencil", "", "", "die Bleistifte", ""),
    ("das Papier", "noun", "das", "紙", "paper", "", "", "die Papiere", ""),
    ("die Tafel", "noun", "die", "黒板／表", "board, table", "", "", "die Tafeln", ""),
    ("das Fach", "noun", "das", "科目／引き出し", "subject, drawer", "", "", "die Fächer", ""),
    ("die Note", "noun", "die", "成績", "grade", "", "", "die Noten", ""),

    # ---------- Health ----------
    ("die Gesundheit", "noun", "die", "健康", "health", "", "", "", "no plural"),
    ("krank", "adj", "", "病気の", "sick", "", "", "", ""),
    ("gesund", "adj", "", "健康な", "healthy", "", "", "", ""),
    ("das Krankenhaus", "noun", "das", "病院", "hospital", "", "", "die Krankenhäuser", ""),
    ("die Apotheke", "noun", "die", "薬局", "pharmacy", "", "", "die Apotheken", ""),
    ("das Medikament", "noun", "das", "薬", "medicine", "", "", "die Medikamente", ""),
    ("die Tablette", "noun", "die", "錠剤", "pill, tablet", "", "", "die Tabletten", ""),
    ("der Schmerz", "noun", "der", "痛み", "pain", "", "", "die Schmerzen", ""),
    ("das Fieber", "noun", "das", "熱", "fever", "", "", "", "no plural"),
    ("die Erkältung", "noun", "die", "風邪", "cold", "", "", "die Erkältungen", ""),
    ("der Husten", "noun", "der", "咳", "cough", "", "", "", "no plural"),
    ("müde", "adj", "", "疲れた", "tired", "", "", "", ""),

    # ---------- Weather & nature ----------
    ("das Wetter", "noun", "das", "天気", "weather", "", "", "", "no plural"),
    ("die Sonne", "noun", "die", "太陽", "sun", "", "", "die Sonnen", ""),
    ("der Regen", "noun", "der", "雨", "rain", "", "", "", "no plural"),
    ("der Schnee", "noun", "der", "雪", "snow", "", "", "", "no plural"),
    ("der Wind", "noun", "der", "風", "wind", "", "", "die Winde", ""),
    ("die Wolke", "noun", "die", "雲", "cloud", "", "", "die Wolken", ""),
    ("kalt", "adj", "", "寒い", "cold", "", "", "", ""),
    ("warm", "adj", "", "暖かい", "warm", "", "", "", ""),
    ("heiß", "adj", "", "暑い／熱い", "hot", "", "", "", ""),
    ("kühl", "adj", "", "涼しい", "cool", "", "", "", ""),
    ("sonnig", "adj", "", "晴れの", "sunny", "", "", "", ""),
    ("der Baum", "noun", "der", "木", "tree", "", "", "die Bäume", ""),
    ("die Blume", "noun", "die", "花", "flower", "", "", "die Blumen", ""),
    ("der Hund", "noun", "der", "犬", "dog", "", "", "die Hunde", ""),
    ("die Katze", "noun", "die", "猫", "cat", "", "", "die Katzen", ""),

    # ---------- Common verbs (irregular & regular essentials) ----------
    ("sein", "verb", "", "〜である", "to be", "war", "ist gewesen", "", "irregular"),
    ("haben", "verb", "", "持つ", "to have", "hatte", "hat gehabt", "", "irregular"),
    ("werden", "verb", "", "なる", "to become", "wurde", "ist geworden", "", ""),
    ("können", "verb", "", "〜できる", "can, to be able to", "konnte", "hat gekonnt", "", "modal"),
    ("müssen", "verb", "", "〜しなければならない", "must, to have to", "musste", "hat gemusst", "", "modal"),
    ("wollen", "verb", "", "〜したい", "to want", "wollte", "hat gewollt", "", "modal"),
    ("sollen", "verb", "", "〜すべき", "should", "sollte", "hat gesollt", "", "modal"),
    ("dürfen", "verb", "", "〜してもよい", "may, to be allowed to", "durfte", "hat gedurft", "", "modal"),
    ("mögen", "verb", "", "好む", "to like", "mochte", "hat gemocht", "", ""),
    ("gehen", "verb", "", "行く", "to go", "ging", "ist gegangen", "", ""),
    ("kommen", "verb", "", "来る", "to come", "kam", "ist gekommen", "", ""),
    ("fahren", "verb", "", "乗り物で行く／運転する", "to drive, go (vehicle)", "fuhr", "ist gefahren", "", ""),
    ("fliegen", "verb", "", "飛ぶ／飛行機で行く", "to fly", "flog", "ist geflogen", "", ""),
    ("laufen", "verb", "", "走る／歩く", "to run, walk", "lief", "ist gelaufen", "", ""),
    ("sehen", "verb", "", "見る", "to see", "sah", "hat gesehen", "", ""),
    ("hören", "verb", "", "聞く", "to hear", "hörte", "hat gehört", "", ""),
    ("sprechen", "verb", "", "話す", "to speak", "sprach", "hat gesprochen", "", ""),
    ("sagen", "verb", "", "言う", "to say", "sagte", "hat gesagt", "", ""),
    ("lesen", "verb", "", "読む", "to read", "las", "hat gelesen", "", ""),
    ("schreiben", "verb", "", "書く", "to write", "schrieb", "hat geschrieben", "", ""),
    ("essen", "verb", "", "食べる", "to eat", "aß", "hat gegessen", "", ""),
    ("trinken", "verb", "", "飲む", "to drink", "trank", "hat getrunken", "", ""),
    ("kaufen", "verb", "", "買う", "to buy", "kaufte", "hat gekauft", "", ""),
    ("verkaufen", "verb", "", "売る", "to sell", "verkaufte", "hat verkauft", "", ""),
    ("bezahlen", "verb", "", "支払う", "to pay", "bezahlte", "hat bezahlt", "", ""),
    ("kosten", "verb", "", "値段がする", "to cost", "kostete", "hat gekostet", "", ""),
    ("arbeiten", "verb", "", "働く", "to work", "arbeitete", "hat gearbeitet", "", ""),
    ("lernen", "verb", "", "学ぶ", "to learn", "lernte", "hat gelernt", "", ""),
    ("studieren", "verb", "", "勉強する／専攻する", "to study (university)", "studierte", "hat studiert", "", ""),
    ("verstehen", "verb", "", "理解する", "to understand", "verstand", "hat verstanden", "", ""),
    ("wissen", "verb", "", "知っている", "to know (fact)", "wusste", "hat gewusst", "", ""),
    ("kennen", "verb", "", "知っている（人）", "to know (person)", "kannte", "hat gekannt", "", ""),
    ("denken", "verb", "", "考える", "to think", "dachte", "hat gedacht", "", ""),
    ("glauben", "verb", "", "信じる／思う", "to believe, think", "glaubte", "hat geglaubt", "", ""),
    ("finden", "verb", "", "見つける／思う", "to find", "fand", "hat gefunden", "", ""),
    ("suchen", "verb", "", "探す", "to search", "suchte", "hat gesucht", "", ""),
    ("fragen", "verb", "", "尋ねる", "to ask", "fragte", "hat gefragt", "", ""),
    ("antworten", "verb", "", "答える", "to answer", "antwortete", "hat geantwortet", "", ""),
    ("geben", "verb", "", "与える", "to give", "gab", "hat gegeben", "", ""),
    ("nehmen", "verb", "", "取る", "to take", "nahm", "hat genommen", "", ""),
    ("bringen", "verb", "", "持って来る", "to bring", "brachte", "hat gebracht", "", ""),
    ("schicken", "verb", "", "送る", "to send", "schickte", "hat geschickt", "", ""),
    ("schlafen", "verb", "", "眠る", "to sleep", "schlief", "hat geschlafen", "", ""),
    ("aufstehen", "verb", "", "起きる", "to get up", "stand auf", "ist aufgestanden", "", "separable"),
    ("anziehen", "verb", "", "着る", "to put on", "zog an", "hat angezogen", "", "separable"),
    ("ausziehen", "verb", "", "脱ぐ", "to take off", "zog aus", "hat ausgezogen", "", "separable"),
    ("waschen", "verb", "", "洗う", "to wash", "wusch", "hat gewaschen", "", ""),
    ("duschen", "verb", "", "シャワーする", "to shower", "duschte", "hat geduscht", "", ""),
    ("kochen", "verb", "", "料理する", "to cook", "kochte", "hat gekocht", "", ""),
    ("backen", "verb", "", "焼く", "to bake", "backte", "hat gebacken", "", ""),
    ("öffnen", "verb", "", "開ける", "to open", "öffnete", "hat geöffnet", "", ""),
    ("schließen", "verb", "", "閉じる", "to close", "schloss", "hat geschlossen", "", ""),
    ("anfangen", "verb", "", "始まる", "to begin", "fing an", "hat angefangen", "", "separable"),
    ("beginnen", "verb", "", "始める", "to begin", "begann", "hat begonnen", "", ""),
    ("aufhören", "verb", "", "やめる", "to stop", "hörte auf", "hat aufgehört", "", "separable"),
    ("brauchen", "verb", "", "必要とする", "to need", "brauchte", "hat gebraucht", "", ""),
    ("helfen", "verb", "", "助ける", "to help", "half", "hat geholfen", "", "+ Dat."),
    ("lieben", "verb", "", "愛する", "to love", "liebte", "hat geliebt", "", ""),
    ("spielen", "verb", "", "遊ぶ／プレーする", "to play", "spielte", "hat gespielt", "", ""),
    ("singen", "verb", "", "歌う", "to sing", "sang", "hat gesungen", "", ""),
    ("tanzen", "verb", "", "踊る", "to dance", "tanzte", "hat getanzt", "", ""),
    ("wohnen", "verb", "", "住む", "to live (reside)", "wohnte", "hat gewohnt", "", ""),
    ("leben", "verb", "", "生きる", "to live", "lebte", "hat gelebt", "", ""),
    ("heißen", "verb", "", "〜という名前である", "to be called", "hieß", "hat geheißen", "", ""),
    ("treffen", "verb", "", "会う", "to meet", "traf", "hat getroffen", "", ""),
    ("besuchen", "verb", "", "訪問する", "to visit", "besuchte", "hat besucht", "", ""),
    ("anrufen", "verb", "", "電話する", "to call (phone)", "rief an", "hat angerufen", "", "separable"),
    ("telefonieren", "verb", "", "電話する", "to telephone", "telefonierte", "hat telefoniert", "", ""),
    ("mitbringen", "verb", "", "持参する", "to bring along", "brachte mit", "hat mitgebracht", "", "separable"),
    ("mitkommen", "verb", "", "一緒に来る", "to come along", "kam mit", "ist mitgekommen", "", "separable"),
    ("abholen", "verb", "", "迎えに行く", "to pick up", "holte ab", "hat abgeholt", "", "separable"),
    ("abfahren", "verb", "", "出発する", "to depart", "fuhr ab", "ist abgefahren", "", "separable"),
    ("ankommen", "verb", "", "到着する", "to arrive", "kam an", "ist angekommen", "", "separable"),
    ("einkaufen", "verb", "", "買い物する", "to shop", "kaufte ein", "hat eingekauft", "", "separable"),
    ("warten", "verb", "", "待つ", "to wait", "wartete", "hat gewartet", "", "auf + Akk."),
    ("bleiben", "verb", "", "とどまる", "to stay", "blieb", "ist geblieben", "", ""),
    ("zeigen", "verb", "", "示す", "to show", "zeigte", "hat gezeigt", "", ""),
    ("machen", "verb", "", "する／作る", "to do, make", "machte", "hat gemacht", "", ""),
    ("tun", "verb", "", "する", "to do", "tat", "hat getan", "", ""),
    ("erklären", "verb", "", "説明する", "to explain", "erklärte", "hat erklärt", "", ""),
    ("üben", "verb", "", "練習する", "to practice", "übte", "hat geübt", "", ""),
    ("reisen", "verb", "", "旅行する", "to travel", "reiste", "ist gereist", "", ""),
    ("besichtigen", "verb", "", "見物する", "to sightsee", "besichtigte", "hat besichtigt", "", ""),
    ("schmecken", "verb", "", "味がする", "to taste", "schmeckte", "hat geschmeckt", "", ""),
    ("möchten", "verb", "", "〜したい", "would like", "wollte", "hat gewollt", "", "subjunctive form"),
    ("freuen (sich)", "verb", "", "喜ぶ", "to be glad", "freute", "hat gefreut", "", "reflexive"),
    ("interessieren (sich)", "verb", "", "興味を持つ", "to be interested", "interessierte", "hat interessiert", "", "reflexive"),

    # ---------- Common adjectives ----------
    ("groß", "adj", "", "大きい", "big, tall", "", "", "", ""),
    ("klein", "adj", "", "小さい", "small", "", "", "", ""),
    ("gut", "adj", "", "良い", "good", "", "", "", ""),
    ("schlecht", "adj", "", "悪い", "bad", "", "", "", ""),
    ("schön", "adj", "", "美しい", "beautiful", "", "", "", ""),
    ("hässlich", "adj", "", "醜い", "ugly", "", "", "", ""),
    ("alt", "adj", "", "古い／高齢の", "old", "", "", "", ""),
    ("jung", "adj", "", "若い", "young", "", "", "", ""),
    ("neu", "adj", "", "新しい", "new", "", "", "", ""),
    ("schnell", "adj", "", "速い", "fast", "", "", "", ""),
    ("langsam", "adj", "", "遅い", "slow", "", "", "", ""),
    ("teuer", "adj", "", "高い（値段）", "expensive", "", "", "", ""),
    ("billig", "adj", "", "安い", "cheap", "", "", "", ""),
    ("lang", "adj", "", "長い", "long", "", "", "", ""),
    ("kurz", "adj", "", "短い", "short", "", "", "", ""),
    ("hoch", "adj", "", "高い", "high, tall", "", "", "", ""),
    ("niedrig", "adj", "", "低い", "low", "", "", "", ""),
    ("breit", "adj", "", "広い", "wide", "", "", "", ""),
    ("schmal", "adj", "", "狭い", "narrow", "", "", "", ""),
    ("dick", "adj", "", "厚い／太い", "thick, fat", "", "", "", ""),
    ("dünn", "adj", "", "薄い／細い", "thin", "", "", "", ""),
    ("schwer", "adj", "", "重い／難しい", "heavy, difficult", "", "", "", ""),
    ("leicht", "adj", "", "軽い／簡単な", "light, easy", "", "", "", ""),
    ("voll", "adj", "", "いっぱい", "full", "", "", "", ""),
    ("leer", "adj", "", "空の", "empty", "", "", "", ""),
    ("sauber", "adj", "", "きれい", "clean", "", "", "", ""),
    ("schmutzig", "adj", "", "汚い", "dirty", "", "", "", ""),
    ("offen", "adj", "", "開いている", "open", "", "", "", ""),
    ("geschlossen", "adj", "", "閉まっている", "closed", "", "", "", ""),
    ("frei", "adj", "", "自由な", "free", "", "", "", ""),
    ("besetzt", "adj", "", "ふさがっている", "occupied", "", "", "", ""),
    ("richtig", "adj", "", "正しい", "correct", "", "", "", ""),
    ("falsch", "adj", "", "間違い", "wrong", "", "", "", ""),
    ("nett", "adj", "", "親切な", "nice", "", "", "", ""),
    ("freundlich", "adj", "", "親切な", "friendly", "", "", "", ""),
    ("interessant", "adj", "", "面白い", "interesting", "", "", "", ""),
    ("langweilig", "adj", "", "退屈な", "boring", "", "", "", ""),
    ("wichtig", "adj", "", "重要な", "important", "", "", "", ""),
    ("möglich", "adj", "", "可能な", "possible", "", "", "", ""),
    ("glücklich", "adj", "", "幸せな", "happy", "", "", "", ""),
    ("traurig", "adj", "", "悲しい", "sad", "", "", "", ""),
    ("lustig", "adj", "", "楽しい／面白い", "fun, funny", "", "", "", ""),
    ("zufrieden", "adj", "", "満足している", "satisfied", "", "", "", ""),
    ("fertig", "adj", "", "出来上がった", "finished, ready", "", "", "", ""),
    ("lecker", "adj", "", "美味しい", "tasty", "", "", "", ""),
    ("gemütlich", "adj", "", "居心地のよい", "cozy", "", "", "", ""),
    ("verheiratet", "adj", "", "結婚している", "married", "", "", "", ""),
    ("ledig", "adj", "", "独身の", "single", "", "", "", ""),

    # ---------- Common adverbs ----------
    ("sehr", "adv", "", "とても", "very", "", "", "", ""),
    ("auch", "adv", "", "も", "also", "", "", "", ""),
    ("noch", "adv", "", "まだ", "still", "", "", "", ""),
    ("schon", "adv", "", "もう", "already", "", "", "", ""),
    ("nicht", "adv", "", "〜ない", "not", "", "", "", ""),
    ("kein", "art", "", "〜ない", "no, not any", "", "", "", "negation article"),
    ("nie", "adv", "", "決して〜ない", "never", "", "", "", ""),
    ("immer", "adv", "", "いつも", "always", "", "", "", ""),
    ("oft", "adv", "", "よく", "often", "", "", "", ""),
    ("manchmal", "adv", "", "時々", "sometimes", "", "", "", ""),
    ("selten", "adv", "", "めったに〜ない", "rarely", "", "", "", ""),
    ("nur", "adv", "", "〜だけ", "only", "", "", "", ""),
    ("zusammen", "adv", "", "一緒に", "together", "", "", "", ""),
    ("allein", "adv", "", "一人で", "alone", "", "", "", ""),
    ("vielleicht", "adv", "", "もしかしたら", "maybe", "", "", "", ""),
    ("natürlich", "adv", "", "もちろん", "of course", "", "", "", ""),
    ("hier", "adv", "", "ここ", "here", "", "", "", ""),
    ("dort", "adv", "", "そこ", "there", "", "", "", ""),
    ("da", "adv", "", "そこ／その時", "there, then", "", "", "", ""),
    ("oben", "adv", "", "上に", "above", "", "", "", ""),
    ("unten", "adv", "", "下に", "below", "", "", "", ""),
    ("links", "adv", "", "左に", "left", "", "", "", ""),
    ("rechts", "adv", "", "右に", "right", "", "", "", ""),
    ("vorne", "adv", "", "前に", "in front", "", "", "", ""),
    ("hinten", "adv", "", "後ろに", "behind", "", "", "", ""),
    ("gern", "adv", "", "〜するのが好き", "gladly", "", "", "", ""),
    ("ganz", "adv", "", "全く", "completely", "", "", "", ""),
    ("fast", "adv", "", "ほとんど", "almost", "", "", "", ""),
    ("etwa", "adv", "", "およそ", "approximately", "", "", "", ""),
    ("zu", "adv", "", "〜すぎる", "too", "", "", "", ""),

    # ---------- Prepositions ----------
    ("in", "prep", "", "〜の中で", "in", "", "", "", "+ Akk./Dat."),
    ("an", "prep", "", "〜に", "at, on", "", "", "", "+ Akk./Dat."),
    ("auf", "prep", "", "〜の上に", "on", "", "", "", "+ Akk./Dat."),
    ("unter", "prep", "", "〜の下に", "under", "", "", "", "+ Akk./Dat."),
    ("über", "prep", "", "〜の上方に", "over, above", "", "", "", "+ Akk./Dat."),
    ("vor", "prep", "", "〜の前に", "in front of, before", "", "", "", "+ Akk./Dat."),
    ("hinter", "prep", "", "〜の後ろに", "behind", "", "", "", "+ Akk./Dat."),
    ("neben", "prep", "", "〜の隣に", "next to", "", "", "", "+ Akk./Dat."),
    ("zwischen", "prep", "", "〜の間に", "between", "", "", "", "+ Akk./Dat."),
    ("bei", "prep", "", "〜のところで", "at, by", "", "", "", "+ Dat."),
    ("mit", "prep", "", "〜と一緒に", "with", "", "", "", "+ Dat."),
    ("nach", "prep", "", "〜の後に／〜へ", "after, to", "", "", "", "+ Dat."),
    ("von", "prep", "", "〜から", "from, of", "", "", "", "+ Dat."),
    ("zu", "prep", "", "〜へ", "to", "", "", "", "+ Dat."),
    ("aus", "prep", "", "〜から", "out of, from", "", "", "", "+ Dat."),
    ("seit", "prep", "", "〜から", "since, for (time)", "", "", "", "+ Dat."),
    ("für", "prep", "", "〜のために", "for", "", "", "", "+ Akk."),
    ("ohne", "prep", "", "〜なしで", "without", "", "", "", "+ Akk."),
    ("um", "prep", "", "〜の周り／〜時に", "around, at (time)", "", "", "", "+ Akk."),
    ("durch", "prep", "", "〜を通って", "through", "", "", "", "+ Akk."),
    ("gegen", "prep", "", "〜に対して", "against", "", "", "", "+ Akk."),

    # ---------- Conjunctions ----------
    ("und", "conj", "", "そして", "and", "", "", "", ""),
    ("oder", "conj", "", "または", "or", "", "", "", ""),
    ("aber", "conj", "", "しかし", "but", "", "", "", ""),
    ("denn", "conj", "", "なぜなら", "because", "", "", "", ""),
    ("weil", "conj", "", "〜なので", "because", "", "", "", "subord."),
    ("dass", "conj", "", "〜ということ", "that", "", "", "", "subord."),
    ("wenn", "conj", "", "もし〜なら", "if, when", "", "", "", "subord."),
    ("als", "conj", "", "〜した時", "when (past)", "", "", "", "subord."),
    ("ob", "conj", "", "〜かどうか", "whether", "", "", "", "subord."),

    # ---------- Articles ----------
    ("der", "art", "", "（男性定冠詞）", "the (m)", "", "", "", ""),
    ("die", "art", "", "（女性定冠詞）", "the (f/pl)", "", "", "", ""),
    ("das", "art", "", "（中性定冠詞）", "the (n)", "", "", "", ""),
    ("ein", "art", "", "ある（男・中）", "a (m/n)", "", "", "", ""),
    ("eine", "art", "", "ある（女）", "a (f)", "", "", "", ""),

    # ---------- Misc essentials ----------
    ("der Name", "noun", "der", "名前", "name", "", "", "die Namen", ""),
    ("der Vorname", "noun", "der", "名", "first name", "", "", "die Vornamen", ""),
    ("der Nachname", "noun", "der", "姓", "last name", "", "", "die Nachnamen", ""),
    ("die Sprache", "noun", "die", "言語", "language", "", "", "die Sprachen", ""),
    ("die Frage", "noun", "die", "質問", "question", "", "", "die Fragen", ""),
    ("die Antwort", "noun", "die", "答え", "answer", "", "", "die Antworten", ""),
    ("das Beispiel", "noun", "das", "例", "example", "", "", "die Beispiele", ""),
    ("das Problem", "noun", "das", "問題", "problem", "", "", "die Probleme", ""),
    ("die Idee", "noun", "die", "アイデア", "idea", "", "", "die Ideen", ""),
    ("das Geld", "noun", "das", "お金", "money", "", "", "die Gelder", ""),
    ("der Euro", "noun", "der", "ユーロ", "euro", "", "", "die Euro", ""),
    ("der Cent", "noun", "der", "セント", "cent", "", "", "die Cents", ""),
    ("die Stadt", "noun", "die", "市／町", "city", "", "", "die Städte", ""),
    ("das Land", "noun", "das", "国／田舎", "country, land", "", "", "die Länder", ""),
    ("die Welt", "noun", "die", "世界", "world", "", "", "die Welten", ""),
    ("der Mensch", "noun", "der", "人間", "human", "", "", "die Menschen", ""),
    ("die Leute", "noun", "die", "人々", "people", "", "", "", "plural"),
    ("der Brief", "noun", "der", "手紙", "letter", "", "", "die Briefe", ""),
    ("die E-Mail", "noun", "die", "メール", "email", "", "", "die E-Mails", ""),
    ("das Telefon", "noun", "das", "電話", "telephone", "", "", "die Telefone", ""),
    ("das Handy", "noun", "das", "携帯電話", "mobile phone", "", "", "die Handys", ""),
    ("der Computer", "noun", "der", "コンピュータ", "computer", "", "", "die Computer", ""),
    ("das Internet", "noun", "das", "インターネット", "internet", "", "", "", "no plural"),
    ("die Information", "noun", "die", "情報", "information", "", "", "die Informationen", ""),
    ("die Nummer", "noun", "die", "番号", "number", "", "", "die Nummern", ""),
    ("der Geburtstag", "noun", "der", "誕生日", "birthday", "", "", "die Geburtstage", ""),
    ("die Geschichte", "noun", "die", "歴史／物語", "history, story", "", "", "die Geschichten", ""),
    ("die Musik", "noun", "die", "音楽", "music", "", "", "", "no plural typical"),
    ("der Film", "noun", "der", "映画", "movie, film", "", "", "die Filme", ""),
    ("das Kino", "noun", "das", "映画館", "cinema", "", "", "die Kinos", ""),
    ("das Theater", "noun", "das", "劇場", "theater", "", "", "die Theater", ""),
    ("das Museum", "noun", "das", "博物館", "museum", "", "", "die Museen", ""),
    ("der Park", "noun", "der", "公園", "park", "", "", "die Parks", ""),
    ("der Sport", "noun", "der", "スポーツ", "sport", "", "", "die Sportarten", ""),
    ("das Spiel", "noun", "das", "ゲーム", "game", "", "", "die Spiele", ""),
    ("der Ball", "noun", "der", "ボール", "ball", "", "", "die Bälle", ""),
    ("der Fußball", "noun", "der", "サッカー", "football, soccer", "", "", "die Fußbälle", ""),
    ("das Foto", "noun", "das", "写真", "photo", "", "", "die Fotos", ""),
    ("das Bild", "noun", "das", "絵／画像", "picture", "", "", "die Bilder", ""),
    ("die Karte", "noun", "die", "カード／地図", "card, map", "", "", "die Karten", ""),
    ("der Tisch", "noun", "der", "テーブル", "table", "", "", "die Tische", ""),
    ("der Hunger", "noun", "der", "空腹", "hunger", "", "", "", "no plural"),
    ("der Durst", "noun", "der", "渇き", "thirst", "", "", "", "no plural"),
    ("die Liebe", "noun", "die", "愛", "love", "", "", "", "no plural"),
    ("der Spaß", "noun", "der", "楽しみ", "fun", "", "", "die Späße", ""),
    ("die Zeit", "noun", "die", "時間", "time", "", "", "die Zeiten", ""),
    ("der Geburtsort", "noun", "der", "出生地", "place of birth", "", "", "die Geburtsorte", ""),
    ("der Anfang", "noun", "der", "始まり", "beginning", "", "", "die Anfänge", ""),
    ("das Ende", "noun", "das", "終わり", "end", "", "", "die Enden", ""),
    ("der Weg", "noun", "der", "道", "way, path", "", "", "die Wege", ""),
    ("das Wort", "noun", "das", "言葉", "word", "", "", "die Wörter", ""),
]

# Theme keyword groups (mirrored from add_tags_to_session_new.py).
THEMES: dict[str, list[str]] = {
    "Familie": [
        "mother", "father", "brother", "sister", "wife", "husband", "family",
        "parent", "child", "son", "daughter", "uncle", "aunt", "cousin",
        "母", "父", "兄", "姉", "弟", "妹", "夫", "妻", "家族", "両親", "祖", "息子", "娘",
        "Mutter", "Vater", "Bruder", "Schwester", "Eltern", "Familie", "Kind",
        "Sohn", "Tochter", "Onkel", "Tante", "Oma", "Opa", "Großmutter",
        "Großvater", "Großeltern", "Geschwister", "Enkel", "Baby", "Cousin",
        "Cousine", "Verwandte", "Ehefrau", "Ehemann", "Mann", "Frau", "Junge", "Mädchen",
        "Freund", "Freundin",
    ],
    "Essen": [
        "food", "eat", "drink", "bread", "meat", "fish", "vegetable", "fruit",
        "cheese", "milk", "coffee", "tea", "wine", "beer", "water", "soup",
        "breakfast", "lunch", "dinner", "restaurant", "cook", "kitchen",
        "食べ", "飲み", "パン", "肉", "魚", "野菜", "果物", "コーヒー", "茶", "水",
        "朝食", "昼食", "夕食", "レストラン", "料理", "台所", "牛乳", "ワイン", "ビール",
        "essen", "Essen", "trinken", "Brot", "Brötchen", "Butter", "Käse",
        "Wurst", "Schinken", "Fleisch", "Fisch", "Gemüse", "Obst", "Apfel",
        "Banane", "Orange", "Tomate", "Kartoffel", "Zwiebel", "Salat", "Suppe",
        "Reis", "Nudel", "Kuchen", "Schokolade", "Salz", "Pfeffer", "Zucker",
        "Saft", "Wasser", "Milch", "Kaffee", "Tee", "Wein", "Bier", "Glas",
        "Tasse", "Teller", "Gabel", "Messer", "Löffel", "kochen", "backen",
        "Restaurant", "Café", "Frühstück", "Mittagessen", "Abendessen",
        "schmecken", "lecker", "Ei",
    ],
    "Arbeit": [
        "work", "job", "office", "boss", "colleague", "salary", "meeting",
        "company", "profession",
        "仕事", "会社", "オフィス", "同僚", "上司", "職業",
        "Arbeit", "arbeiten", "Beruf", "Job", "Büro", "Firma", "Unternehmen",
        "Chef", "Chefin", "Kollege", "Kollegin", "Termin",
    ],
    "Reisen": [
        "travel", "trip", "holiday", "vacation", "airport", "flight", "hotel",
        "passport", "ticket", "tourist",
        "旅", "旅行", "休暇", "空港", "飛行", "ホテル", "パスポート", "観光",
        "Reise", "reisen", "Urlaub", "Ferien", "Flug", "fliegen", "Flughafen",
        "Hotel", "Pass", "Ticket", "Fahrkarte", "Koffer",
    ],
    "Verkehr": [
        "car", "bus", "train", "bike", "taxi", "drive", "street", "station",
        "車", "バス", "電車", "自転車", "タクシー", "駅",
        "Auto", "Wagen", "Bus", "Zug", "Bahn", "Fahrrad", "Taxi", "fahren",
        "Bahnhof", "Haltestelle", "Straße", "Flugzeug",
    ],
    "Wohnen": [
        "house", "apartment", "room", "kitchen", "bathroom", "bedroom",
        "garden", "door", "window",
        "家", "部屋", "アパート", "キッチン", "風呂", "庭", "ドア", "窓",
        "Haus", "Wohnung", "Zimmer", "Küche", "Bad", "Schlafzimmer",
        "Wohnzimmer", "Garten", "Balkon", "Tisch", "Stuhl", "Bett", "Schrank",
        "Lampe", "Tür", "Fenster", "Wand", "Boden", "Adresse", "Straße",
    ],
    "Gesundheit": [
        "health", "sick", "doctor", "hospital", "medicine", "pain", "fever",
        "健康", "病気", "医者", "病院", "痛", "薬",
        "Gesundheit", "gesund", "krank", "Arzt", "Ärztin", "Krankenhaus",
        "Apotheke", "Medikament", "Tablette", "Schmerz", "Fieber", "Husten",
        "Erkältung",
    ],
    "Kleidung": [
        "clothes", "shirt", "trouser", "dress", "shoe", "jacket", "coat",
        "skirt", "hat",
        "シャツ", "ズボン", "靴", "ジャケット", "コート", "スカート", "帽子",
        "Kleidung", "Hemd", "Bluse", "Pullover", "Jacke", "Mantel", "Hose",
        "Rock", "Schuh", "Socke", "Hut", "Mütze", "Tasche", "Brille",
        "anziehen", "ausziehen",
    ],
    "Einkaufen": [
        "shop", "buy", "sell", "pay", "money", "price", "cheap", "expensive",
        "店", "買う", "売る", "値段", "安い", "高い",
        "einkaufen", "kaufen", "verkaufen", "Preis", "kosten", "billig",
        "teuer", "Euro", "Geld", "bezahlen", "Verkäufer",
    ],
    "Zeit": [
        "hour", "minute", "day", "week", "month", "year", "morning", "evening",
        "night", "today", "tomorrow", "yesterday",
        "時間", "分", "週", "月", "年", "朝", "夕方", "夜", "今日", "明日", "昨日",
        "Zeit", "Stunde", "Minute", "Tag", "Woche", "Monat", "Jahr", "heute",
        "morgen", "gestern", "jetzt", "früh", "spät", "Uhr", "Termin",
        "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag",
        "Sonntag", "Januar", "Februar", "März", "April", "Mai", "Juni", "Juli",
        "August", "September", "Oktober", "November", "Dezember",
    ],
    "Wetter": [
        "weather", "rain", "snow", "sun", "wind", "cold", "hot", "warm",
        "天気", "雨", "雪", "太陽", "寒い", "暑い", "暖かい",
        "Wetter", "Regen", "Schnee", "Sonne", "Wind", "Wolke", "kalt", "warm",
        "heiß", "kühl", "sonnig",
    ],
    "Schule": [
        "school", "teacher", "student", "class", "lesson", "learn", "study",
        "homework", "exam", "university",
        "学校", "先生", "学生", "授業", "勉強", "宿題", "試験", "大学",
        "Schule", "Schüler", "Schülerin", "Lehrer", "Lehrerin", "Klasse",
        "Unterricht", "lernen", "studieren", "Universität", "Hausaufgabe",
        "Prüfung", "Test", "Buch", "Heft", "Stift", "Tafel", "Fach", "Note",
    ],
    "Freizeit": [
        "sport", "game", "play", "music", "film", "movie", "book", "read",
        "hobby", "party", "dance",
        "スポーツ", "ゲーム", "音楽", "映画", "本", "趣味",
        "Sport", "Spiel", "spielen", "Musik", "Film", "Kino", "Theater",
        "Museum", "Park", "Fußball", "Ball", "tanzen", "singen",
    ],
    "Gefühle": [
        "happy", "sad", "angry", "love", "feel", "feeling",
        "嬉", "悲", "怒", "愛",
        "Liebe", "lieben", "glücklich", "traurig", "Spaß", "freuen", "müde",
        "interessant", "langweilig",
    ],
    "Farben": [
        "color", "colour", "red", "blue", "green", "yellow", "black", "white",
        "brown", "pink", "orange", "grey", "gray",
        "色", "赤", "青", "緑", "黄色", "黒", "白",
        "Farbe", "rot", "blau", "grün", "gelb", "schwarz", "weiß", "braun",
        "grau", "rosa", "lila",
    ],
}
_ASCII_WORD = re.compile(r"^[a-zA-Z]+$")


def has_keyword(haystack: str, keyword: str) -> bool:
    if _ASCII_WORD.fullmatch(keyword):
        return bool(re.search(rf"\b{re.escape(keyword)}\b", haystack, re.IGNORECASE))
    return keyword in haystack


def compute_tags(german: str, pos: str, ja: str, en: str, level: str) -> list[str]:
    haystack = " ".join(filter(None, [german, ja, en]))
    tags: list[str] = []
    for theme, kws in THEMES.items():
        for kw in kws:
            if has_keyword(haystack, kw):
                tags.append(theme)
                break
    if pos:
        tags.append(pos.strip().lower())
    if level:
        tags.append(level)
    # Dedup preserving order
    seen: set[str] = set()
    out = []
    for t in tags:
        if t not in seen:
            seen.add(t)
            out.append(t)
    return out


def main():
    wb = load_workbook(MASTER)
    ws = wb[SHEET]
    # Locate columns
    header = [c.value for c in ws[1]]
    if "Tags" not in header:
        raise RuntimeError("Tags column missing — run add_tags_to_session_new.py first")

    # Index of existing German terms to avoid duplicates
    existing_terms: set[str] = set()
    for row in ws.iter_rows(min_row=2, values_only=True):
        g = row[0]
        if g and str(g).strip():
            existing_terms.add(str(g).strip().lower())

    start_row = ws.max_row + 1
    added = 0
    skipped = 0
    for g, pos, art, ja, en, prat, pii, plural, notes in A1_ENTRIES:
        if g.strip().lower() in existing_terms:
            skipped += 1
            continue
        tags = compute_tags(g, pos, ja, en, LEVEL)
        row_data = [g, pos, art, ja, en, 1, prat, pii, plural, notes, ", ".join(tags)]
        for col_idx, value in enumerate(row_data, start=1):
            ws.cell(row=start_row + added, column=col_idx, value=value)
        added += 1

    wb.save(MASTER)
    print(f"Added {added} A1 entries. Skipped {skipped} (already present). Total rows now: {ws.max_row}.")


if __name__ == "__main__":
    main()
