"""Append A2 vocabulary to german_vocab_session_new.xlsx (the master file).

A2 vocabulary is curated against Goethe Start Deutsch 2 / telc A2 official word
lists. Builds on A1 (handled by add_a1_to_master.py) — duplicates are skipped.

Each row carries:
  German term | POS | Article | Japanese | English | Appearance_Count |
  Präteritum  | Partizip II | Plural | Notes | Tags

Tags are computed automatically (theme + POS + level=A2). The level tag drives
the deck-creation level filter via `cards.levels`.
"""

from __future__ import annotations
import re
import sys
from pathlib import Path

from openpyxl import load_workbook

sys.stdout.reconfigure(encoding="utf-8")

MASTER = Path(__file__).resolve().parent / "german_vocab_master.xlsx"
SHEET = "Session Vokabeln"
LEVEL = "A2"

# Entry format: (German, POS, Article, Japanese, English, Präteritum, Partizip II, Plural, Notes)
A2_ENTRIES: list[tuple[str, str, str, str, str, str, str, str, str]] = [
    # ---------- Family & relationships (extended) ----------
    ("der Verwandte", "noun", "der", "親戚", "relative", "", "", "die Verwandten", "adj-decl"),
    ("die Verwandte", "noun", "die", "親戚（女）", "relative (f)", "", "", "die Verwandten", ""),
    ("der Nachbar", "noun", "der", "隣人", "neighbour", "", "", "die Nachbarn", ""),
    ("die Nachbarin", "noun", "die", "隣人（女）", "neighbour (f)", "", "", "die Nachbarinnen", ""),
    ("der Bekannte", "noun", "der", "知人", "acquaintance", "", "", "die Bekannten", "adj-decl"),
    ("die Beziehung", "noun", "die", "関係", "relationship", "", "", "die Beziehungen", ""),
    ("verheiratet", "adj", "", "結婚している", "married", "", "", "", ""),
    ("geschieden", "adj", "", "離婚した", "divorced", "", "", "", ""),
    ("ledig", "adj", "", "独身の", "single", "", "", "", ""),
    ("die Hochzeit", "noun", "die", "結婚式", "wedding", "", "", "die Hochzeiten", ""),
    ("die Ehe", "noun", "die", "結婚生活", "marriage", "", "", "die Ehen", ""),
    ("heiraten", "verb", "", "結婚する", "to marry", "heiratete", "hat geheiratet", "", ""),
    ("sich scheiden lassen", "verb", "", "離婚する", "to get divorced", "ließ sich scheiden", "hat sich scheiden lassen", "", ""),
    ("die Geburt", "noun", "die", "誕生", "birth", "", "", "die Geburten", ""),
    ("der Geburtstag", "noun", "der", "誕生日", "birthday", "", "", "die Geburtstage", ""),
    ("der Tod", "noun", "der", "死", "death", "", "", "", ""),
    ("sterben", "verb", "", "死ぬ", "to die", "starb", "ist gestorben", "", "irregular"),
    ("die Jugend", "noun", "die", "若さ／青春", "youth", "", "", "", ""),
    ("der Erwachsene", "noun", "der", "大人", "adult", "", "", "die Erwachsenen", "adj-decl"),
    ("der Verlobte", "noun", "der", "婚約者", "fiancé", "", "", "die Verlobten", "adj-decl"),
    ("schwanger", "adj", "", "妊娠している", "pregnant", "", "", "", ""),

    # ---------- Work & profession (extended) ----------
    ("der Beruf", "noun", "der", "職業", "profession", "", "", "die Berufe", ""),
    ("die Karriere", "noun", "die", "キャリア", "career", "", "", "die Karrieren", ""),
    ("der Arbeitgeber", "noun", "der", "雇用主", "employer", "", "", "die Arbeitgeber", ""),
    ("der Arbeitnehmer", "noun", "der", "従業員", "employee", "", "", "die Arbeitnehmer", ""),
    ("der Kollege", "noun", "der", "同僚", "colleague (m)", "", "", "die Kollegen", "n-decl"),
    ("die Kollegin", "noun", "die", "同僚（女）", "colleague (f)", "", "", "die Kolleginnen", ""),
    ("der Chef", "noun", "der", "上司", "boss", "", "", "die Chefs", ""),
    ("die Chefin", "noun", "die", "上司（女）", "boss (f)", "", "", "die Chefinnen", ""),
    ("die Firma", "noun", "die", "会社", "company, firm", "", "", "die Firmen", ""),
    ("das Unternehmen", "noun", "das", "企業", "enterprise", "", "", "die Unternehmen", ""),
    ("die Stelle", "noun", "die", "ポスト／場所", "position, place", "", "", "die Stellen", ""),
    ("die Arbeitsstelle", "noun", "die", "勤務先", "workplace", "", "", "die Arbeitsstellen", ""),
    ("die Bewerbung", "noun", "die", "応募", "application", "", "", "die Bewerbungen", ""),
    ("sich bewerben", "verb", "", "応募する", "to apply", "bewarb", "hat beworben", "", "irregular"),
    ("das Vorstellungsgespräch", "noun", "das", "面接", "job interview", "", "", "die Vorstellungsgespräche", ""),
    ("der Lebenslauf", "noun", "der", "履歴書", "CV, résumé", "", "", "die Lebensläufe", ""),
    ("das Zeugnis", "noun", "das", "成績証明書", "certificate", "", "", "die Zeugnisse", ""),
    ("der Vertrag", "noun", "der", "契約", "contract", "", "", "die Verträge", ""),
    ("das Gehalt", "noun", "das", "給与", "salary", "", "", "die Gehälter", ""),
    ("der Lohn", "noun", "der", "賃金", "wage", "", "", "die Löhne", ""),
    ("verdienen", "verb", "", "稼ぐ", "to earn", "verdiente", "hat verdient", "", ""),
    ("die Pause", "noun", "die", "休憩", "break", "", "", "die Pausen", ""),
    ("der Urlaub", "noun", "der", "休暇", "vacation, holiday", "", "", "die Urlaube", ""),
    ("der Feierabend", "noun", "der", "終業後", "end of working day", "", "", "", ""),
    ("die Überstunden", "noun", "die", "残業", "overtime", "", "", "", "plural"),
    ("die Karte", "noun", "die", "カード／地図", "card, map", "", "", "die Karten", ""),
    ("kündigen", "verb", "", "解雇する／退職する", "to quit, to fire", "kündigte", "hat gekündigt", "", ""),
    ("die Kündigung", "noun", "die", "解雇／退職", "termination", "", "", "die Kündigungen", ""),
    ("arbeitslos", "adj", "", "失業中の", "unemployed", "", "", "", ""),
    ("die Arbeitslosigkeit", "noun", "die", "失業", "unemployment", "", "", "", ""),
    ("der Termin", "noun", "der", "予定", "appointment", "", "", "die Termine", ""),
    ("die Besprechung", "noun", "die", "ミーティング", "meeting", "", "", "die Besprechungen", ""),
    ("die Sitzung", "noun", "die", "会議", "session", "", "", "die Sitzungen", ""),
    ("das Projekt", "noun", "das", "プロジェクト", "project", "", "", "die Projekte", ""),
    ("das Team", "noun", "das", "チーム", "team", "", "", "die Teams", ""),
    ("der Kunde", "noun", "der", "顧客", "customer", "", "", "die Kunden", "n-decl"),
    ("die Kundin", "noun", "die", "顧客（女）", "customer (f)", "", "", "die Kundinnen", ""),
    ("der Auftrag", "noun", "der", "依頼／注文", "order, task", "", "", "die Aufträge", ""),
    ("die Aufgabe", "noun", "die", "課題", "task", "", "", "die Aufgaben", ""),
    ("verantwortlich", "adj", "", "責任のある", "responsible", "", "", "", ""),
    ("die Verantwortung", "noun", "die", "責任", "responsibility", "", "", "die Verantwortungen", ""),
    ("die Erfahrung", "noun", "die", "経験", "experience", "", "", "die Erfahrungen", ""),
    ("die Ausbildung", "noun", "die", "職業訓練", "vocational training", "", "", "die Ausbildungen", ""),
    ("der Praktikant", "noun", "der", "インターン", "intern", "", "", "die Praktikanten", ""),
    ("das Praktikum", "noun", "das", "インターンシップ", "internship", "", "", "die Praktika", ""),

    # ---------- Common professions ----------
    ("der Architekt", "noun", "der", "建築家", "architect", "", "", "die Architekten", ""),
    ("die Architektin", "noun", "die", "建築家（女）", "architect (f)", "", "", "die Architektinnen", ""),
    ("der Anwalt", "noun", "der", "弁護士", "lawyer (m)", "", "", "die Anwälte", ""),
    ("die Anwältin", "noun", "die", "弁護士（女）", "lawyer (f)", "", "", "die Anwältinnen", ""),
    ("der Beamte", "noun", "der", "公務員", "civil servant (m)", "", "", "die Beamten", "adj-decl"),
    ("die Beamtin", "noun", "die", "公務員（女）", "civil servant (f)", "", "", "die Beamtinnen", ""),
    ("der Ingenieur", "noun", "der", "エンジニア", "engineer (m)", "", "", "die Ingenieure", ""),
    ("die Ingenieurin", "noun", "die", "エンジニア（女）", "engineer (f)", "", "", "die Ingenieurinnen", ""),
    ("der Journalist", "noun", "der", "ジャーナリスト", "journalist (m)", "", "", "die Journalisten", ""),
    ("die Journalistin", "noun", "die", "ジャーナリスト（女）", "journalist (f)", "", "", "die Journalistinnen", ""),
    ("der Künstler", "noun", "der", "芸術家", "artist (m)", "", "", "die Künstler", ""),
    ("die Künstlerin", "noun", "die", "芸術家（女）", "artist (f)", "", "", "die Künstlerinnen", ""),
    ("der Politiker", "noun", "der", "政治家", "politician (m)", "", "", "die Politiker", ""),
    ("die Politikerin", "noun", "die", "政治家（女）", "politician (f)", "", "", "die Politikerinnen", ""),
    ("der Wissenschaftler", "noun", "der", "科学者", "scientist (m)", "", "", "die Wissenschaftler", ""),
    ("die Wissenschaftlerin", "noun", "die", "科学者（女）", "scientist (f)", "", "", "die Wissenschaftlerinnen", ""),
    ("der Programmierer", "noun", "der", "プログラマー", "programmer", "", "", "die Programmierer", ""),
    ("der Krankenpfleger", "noun", "der", "看護師（男）", "nurse (m)", "", "", "die Krankenpfleger", ""),
    ("die Krankenschwester", "noun", "die", "看護師（女）", "nurse (f)", "", "", "die Krankenschwestern", ""),
    ("der Friseur", "noun", "der", "美容師", "hairdresser (m)", "", "", "die Friseure", ""),
    ("die Friseuse", "noun", "die", "美容師（女）", "hairdresser (f)", "", "", "die Friseusen", ""),
    ("der Mechaniker", "noun", "der", "整備士", "mechanic", "", "", "die Mechaniker", ""),
    ("der Elektriker", "noun", "der", "電気技師", "electrician", "", "", "die Elektriker", ""),
    ("der Bäcker", "noun", "der", "パン職人", "baker", "", "", "die Bäcker", ""),
    ("der Metzger", "noun", "der", "肉屋", "butcher", "", "", "die Metzger", ""),
    ("der Koch", "noun", "der", "料理人", "cook (m)", "", "", "die Köche", ""),
    ("die Köchin", "noun", "die", "料理人（女）", "cook (f)", "", "", "die Köchinnen", ""),
    ("der Kellner", "noun", "der", "ウェイター", "waiter", "", "", "die Kellner", ""),
    ("die Kellnerin", "noun", "die", "ウェイトレス", "waitress", "", "", "die Kellnerinnen", ""),
    ("der Bauer", "noun", "der", "農家", "farmer", "", "", "die Bauern", "n-decl"),
    ("der Soldat", "noun", "der", "兵士", "soldier", "", "", "die Soldaten", "n-decl"),
    ("der Polizist", "noun", "der", "警察官", "police officer (m)", "", "", "die Polizisten", "n-decl"),
    ("die Polizistin", "noun", "die", "警察官（女）", "police officer (f)", "", "", "die Polizistinnen", ""),

    # ---------- Money, economy & shopping (extended) ----------
    ("die Bank", "noun", "die", "銀行", "bank", "", "", "die Banken", ""),
    ("das Konto", "noun", "das", "口座", "account", "", "", "die Konten", ""),
    ("die Kreditkarte", "noun", "die", "クレジットカード", "credit card", "", "", "die Kreditkarten", ""),
    ("die EC-Karte", "noun", "die", "デビットカード", "debit card", "", "", "die EC-Karten", ""),
    ("die Münze", "noun", "die", "硬貨", "coin", "", "", "die Münzen", ""),
    ("der Schein", "noun", "der", "紙幣／レシート", "bill, banknote", "", "", "die Scheine", ""),
    ("die Rechnung", "noun", "die", "請求書", "invoice, bill", "", "", "die Rechnungen", ""),
    ("die Quittung", "noun", "die", "領収書", "receipt", "", "", "die Quittungen", ""),
    ("der Beleg", "noun", "der", "証票", "voucher, slip", "", "", "die Belege", ""),
    ("die Summe", "noun", "die", "合計", "sum, total", "", "", "die Summen", ""),
    ("der Betrag", "noun", "der", "金額", "amount", "", "", "die Beträge", ""),
    ("überweisen", "verb", "", "振り込む", "to transfer (money)", "überwies", "hat überwiesen", "", "irregular"),
    ("abheben", "verb", "", "引き出す", "to withdraw", "hob ab", "hat abgehoben", "", "irregular"),
    ("einzahlen", "verb", "", "預け入れる", "to deposit", "zahlte ein", "hat eingezahlt", "", ""),
    ("sparen", "verb", "", "節約する／貯金する", "to save", "sparte", "hat gespart", "", ""),
    ("ausgeben", "verb", "", "支出する", "to spend", "gab aus", "hat ausgegeben", "", "irregular"),
    ("die Steuer", "noun", "die", "税金", "tax", "", "", "die Steuern", ""),
    ("die Versicherung", "noun", "die", "保険", "insurance", "", "", "die Versicherungen", ""),
    ("die Miete", "noun", "die", "家賃", "rent", "", "", "die Mieten", ""),
    ("die Nebenkosten", "noun", "die", "光熱費", "utilities", "", "", "", "plural"),
    ("der Vertrag", "noun", "der", "契約", "contract", "", "", "die Verträge", ""),
    ("das Angebot", "noun", "das", "提案／オファー", "offer", "", "", "die Angebote", ""),
    ("der Markt", "noun", "der", "市場", "market", "", "", "die Märkte", ""),
    ("der Wochenmarkt", "noun", "der", "週末市", "weekly market", "", "", "die Wochenmärkte", ""),
    ("das Schaufenster", "noun", "das", "ショーウィンドウ", "shop window", "", "", "die Schaufenster", ""),
    ("die Größe", "noun", "die", "サイズ", "size", "", "", "die Größen", ""),
    ("das Sonderangebot", "noun", "das", "特別オファー", "special offer", "", "", "die Sonderangebote", ""),
    ("der Rabatt", "noun", "der", "割引", "discount", "", "", "die Rabatte", ""),
    ("kostenlos", "adj", "", "無料の", "free of charge", "", "", "", ""),
    ("umtauschen", "verb", "", "交換する", "to exchange", "tauschte um", "hat umgetauscht", "", ""),
    ("zurückgeben", "verb", "", "返品する", "to return", "gab zurück", "hat zurückgegeben", "", "irregular"),

    # ---------- Housing (extended) ----------
    ("die Wohngemeinschaft", "noun", "die", "シェアハウス", "shared flat", "", "", "die Wohngemeinschaften", "WG"),
    ("die WG", "noun", "die", "シェアハウス（略）", "shared flat (abbr)", "", "", "die WGs", ""),
    ("der Vermieter", "noun", "der", "家主", "landlord", "", "", "die Vermieter", ""),
    ("die Vermieterin", "noun", "die", "家主（女）", "landlady", "", "", "die Vermieterinnen", ""),
    ("der Mieter", "noun", "der", "賃借人", "tenant", "", "", "die Mieter", ""),
    ("mieten", "verb", "", "賃貸する（借りる）", "to rent", "mietete", "hat gemietet", "", ""),
    ("vermieten", "verb", "", "賃貸する（貸す）", "to rent out", "vermietete", "hat vermietet", "", ""),
    ("umziehen", "verb", "", "引っ越す", "to move (house)", "zog um", "ist umgezogen", "", "irregular"),
    ("der Umzug", "noun", "der", "引っ越し", "move", "", "", "die Umzüge", ""),
    ("möbliert", "adj", "", "家具付きの", "furnished", "", "", "", ""),
    ("die Möbel", "noun", "die", "家具", "furniture", "", "", "", "plural"),
    ("das Sofa", "noun", "das", "ソファ", "sofa", "", "", "die Sofas", ""),
    ("der Sessel", "noun", "der", "肘掛け椅子", "armchair", "", "", "die Sessel", ""),
    ("der Teppich", "noun", "der", "じゅうたん", "carpet", "", "", "die Teppiche", ""),
    ("der Vorhang", "noun", "der", "カーテン", "curtain", "", "", "die Vorhänge", ""),
    ("die Heizung", "noun", "die", "暖房", "heating", "", "", "die Heizungen", ""),
    ("die Klimaanlage", "noun", "die", "エアコン", "air conditioning", "", "", "die Klimaanlagen", ""),
    ("der Strom", "noun", "der", "電気", "electricity", "", "", "", ""),
    ("das Gas", "noun", "das", "ガス", "gas", "", "", "die Gase", ""),
    ("das Wasser", "noun", "das", "水", "water", "", "", "", ""),
    ("der Müll", "noun", "der", "ごみ", "trash", "", "", "", ""),
    ("die Mülltonne", "noun", "die", "ごみ箱", "trash can", "", "", "die Mülltonnen", ""),
    ("der Aufzug", "noun", "der", "エレベーター", "elevator", "", "", "die Aufzüge", ""),
    ("der Keller", "noun", "der", "地下室", "cellar, basement", "", "", "die Keller", ""),
    ("der Dachboden", "noun", "der", "屋根裏", "attic", "", "", "die Dachböden", ""),
    ("die Treppe", "noun", "die", "階段", "staircase", "", "", "die Treppen", ""),
    ("der Garten", "noun", "der", "庭", "garden", "", "", "die Gärten", ""),
    ("der Balkon", "noun", "der", "バルコニー", "balcony", "", "", "die Balkone", ""),
    ("die Terrasse", "noun", "die", "テラス", "terrace", "", "", "die Terrassen", ""),
    ("renovieren", "verb", "", "改装する", "to renovate", "renovierte", "hat renoviert", "", ""),
    ("reparieren", "verb", "", "修理する", "to repair", "reparierte", "hat repariert", "", ""),
    ("putzen", "verb", "", "掃除する", "to clean", "putzte", "hat geputzt", "", ""),
    ("staubsaugen", "verb", "", "掃除機をかける", "to vacuum", "staubsaugte", "hat gestaubsaugt", "", ""),
    ("der Staubsauger", "noun", "der", "掃除機", "vacuum cleaner", "", "", "die Staubsauger", ""),
    ("die Waschmaschine", "noun", "die", "洗濯機", "washing machine", "", "", "die Waschmaschinen", ""),
    ("der Geschirrspüler", "noun", "der", "食器洗い機", "dishwasher", "", "", "die Geschirrspüler", ""),

    # ---------- Body parts (extended) ----------
    ("der Körper", "noun", "der", "体", "body", "", "", "die Körper", ""),
    ("der Kopf", "noun", "der", "頭", "head", "", "", "die Köpfe", ""),
    ("das Gehirn", "noun", "das", "脳", "brain", "", "", "die Gehirne", ""),
    ("die Stirn", "noun", "die", "額", "forehead", "", "", "die Stirnen", ""),
    ("die Wange", "noun", "die", "頬", "cheek", "", "", "die Wangen", ""),
    ("das Kinn", "noun", "das", "あご", "chin", "", "", "die Kinne", ""),
    ("die Lippe", "noun", "die", "唇", "lip", "", "", "die Lippen", ""),
    ("die Zunge", "noun", "die", "舌", "tongue", "", "", "die Zungen", ""),
    ("der Zahn", "noun", "der", "歯", "tooth", "", "", "die Zähne", ""),
    ("der Hals", "noun", "der", "首／喉", "neck, throat", "", "", "die Hälse", ""),
    ("die Schulter", "noun", "die", "肩", "shoulder", "", "", "die Schultern", ""),
    ("der Arm", "noun", "der", "腕", "arm", "", "", "die Arme", ""),
    ("der Ellbogen", "noun", "der", "肘", "elbow", "", "", "die Ellbogen", ""),
    ("das Handgelenk", "noun", "das", "手首", "wrist", "", "", "die Handgelenke", ""),
    ("der Finger", "noun", "der", "指", "finger", "", "", "die Finger", ""),
    ("der Daumen", "noun", "der", "親指", "thumb", "", "", "die Daumen", ""),
    ("der Nagel", "noun", "der", "爪", "nail", "", "", "die Nägel", ""),
    ("die Brust", "noun", "die", "胸", "chest, breast", "", "", "die Brüste", ""),
    ("der Rücken", "noun", "der", "背中", "back", "", "", "die Rücken", ""),
    ("der Bauch", "noun", "der", "腹", "belly", "", "", "die Bäuche", ""),
    ("die Hüfte", "noun", "die", "腰", "hip", "", "", "die Hüften", ""),
    ("das Bein", "noun", "das", "脚", "leg", "", "", "die Beine", ""),
    ("das Knie", "noun", "das", "膝", "knee", "", "", "die Knie", ""),
    ("der Fuß", "noun", "der", "足", "foot", "", "", "die Füße", ""),
    ("der Zeh", "noun", "der", "足の指", "toe", "", "", "die Zehen", ""),
    ("die Haut", "noun", "die", "皮膚", "skin", "", "", "die Häute", ""),
    ("das Haar", "noun", "das", "髪", "hair", "", "", "die Haare", ""),
    ("der Bart", "noun", "der", "ひげ", "beard", "", "", "die Bärte", ""),
    ("das Herz", "noun", "das", "心臓", "heart", "", "", "die Herzen", ""),
    ("die Lunge", "noun", "die", "肺", "lung", "", "", "die Lungen", ""),
    ("die Leber", "noun", "die", "肝臓", "liver", "", "", "die Lebern", ""),
    ("der Magen", "noun", "der", "胃", "stomach", "", "", "die Mägen", ""),
    ("die Niere", "noun", "die", "腎臓", "kidney", "", "", "die Nieren", ""),
    ("das Blut", "noun", "das", "血", "blood", "", "", "", ""),
    ("der Muskel", "noun", "der", "筋肉", "muscle", "", "", "die Muskeln", ""),
    ("der Knochen", "noun", "der", "骨", "bone", "", "", "die Knochen", ""),

    # ---------- Health (extended) ----------
    ("die Gesundheit", "noun", "die", "健康", "health", "", "", "", ""),
    ("die Krankheit", "noun", "die", "病気", "illness", "", "", "die Krankheiten", ""),
    ("der Schnupfen", "noun", "der", "鼻風邪", "cold (runny nose)", "", "", "", ""),
    ("der Husten", "noun", "der", "せき", "cough", "", "", "", ""),
    ("die Erkältung", "noun", "die", "かぜ", "cold", "", "", "die Erkältungen", ""),
    ("die Grippe", "noun", "die", "インフルエンザ", "flu", "", "", "die Grippen", ""),
    ("die Allergie", "noun", "die", "アレルギー", "allergy", "", "", "die Allergien", ""),
    ("die Verletzung", "noun", "die", "けが", "injury", "", "", "die Verletzungen", ""),
    ("verletzt", "adj", "", "けがをした", "injured", "", "", "", ""),
    ("die Wunde", "noun", "die", "傷", "wound", "", "", "die Wunden", ""),
    ("das Pflaster", "noun", "das", "ばんそうこう", "plaster, band-aid", "", "", "die Pflaster", ""),
    ("die Tablette", "noun", "die", "錠剤", "tablet, pill", "", "", "die Tabletten", ""),
    ("die Spritze", "noun", "die", "注射", "injection", "", "", "die Spritzen", ""),
    ("die Operation", "noun", "die", "手術", "operation", "", "", "die Operationen", ""),
    ("die Untersuchung", "noun", "die", "診察", "examination", "", "", "die Untersuchungen", ""),
    ("die Praxis", "noun", "die", "診療所", "doctor's practice", "", "", "die Praxen", ""),
    ("die Sprechstunde", "noun", "die", "診察時間", "consulting hours", "", "", "die Sprechstunden", ""),
    ("der Patient", "noun", "der", "患者", "patient (m)", "", "", "die Patienten", "n-decl"),
    ("die Patientin", "noun", "die", "患者（女）", "patient (f)", "", "", "die Patientinnen", ""),
    ("die Apotheke", "noun", "die", "薬局", "pharmacy", "", "", "die Apotheken", ""),
    ("das Rezept", "noun", "das", "処方箋／レシピ", "prescription, recipe", "", "", "die Rezepte", ""),
    ("untersuchen", "verb", "", "診察する／調べる", "to examine", "untersuchte", "hat untersucht", "", ""),
    ("behandeln", "verb", "", "治療する", "to treat", "behandelte", "hat behandelt", "", ""),
    ("sich erholen", "verb", "", "回復する", "to recover", "erholte sich", "hat sich erholt", "", ""),
    ("die Therapie", "noun", "die", "治療", "therapy", "", "", "die Therapien", ""),
    ("der Notarzt", "noun", "der", "救急医", "emergency doctor", "", "", "die Notärzte", ""),
    ("der Krankenwagen", "noun", "der", "救急車", "ambulance", "", "", "die Krankenwagen", ""),
    ("die Pflege", "noun", "die", "介護", "care", "", "", "", ""),

    # ---------- Food & drink (extended) ----------
    ("das Frühstück", "noun", "das", "朝食", "breakfast", "", "", "die Frühstücke", ""),
    ("frühstücken", "verb", "", "朝食を取る", "to have breakfast", "frühstückte", "hat gefrühstückt", "", ""),
    ("das Mittagessen", "noun", "das", "昼食", "lunch", "", "", "die Mittagessen", ""),
    ("die Mahlzeit", "noun", "die", "食事", "meal", "", "", "die Mahlzeiten", ""),
    ("der Imbiss", "noun", "der", "軽食", "snack stand", "", "", "die Imbisse", ""),
    ("die Vorspeise", "noun", "die", "前菜", "starter", "", "", "die Vorspeisen", ""),
    ("die Hauptspeise", "noun", "die", "メイン料理", "main course", "", "", "die Hauptspeisen", ""),
    ("die Nachspeise", "noun", "die", "デザート", "dessert", "", "", "die Nachspeisen", ""),
    ("der Nachtisch", "noun", "der", "デザート", "dessert", "", "", "die Nachtische", ""),
    ("die Speisekarte", "noun", "die", "メニュー", "menu", "", "", "die Speisekarten", ""),
    ("die Suppe", "noun", "die", "スープ", "soup", "", "", "die Suppen", ""),
    ("der Salat", "noun", "der", "サラダ", "salad", "", "", "die Salate", ""),
    ("die Soße", "noun", "die", "ソース", "sauce", "", "", "die Soßen", ""),
    ("die Pommes", "noun", "die", "ポテトフライ", "fries", "", "", "", "plural"),
    ("die Nudeln", "noun", "die", "麺", "noodles", "", "", "", "plural"),
    ("die Pizza", "noun", "die", "ピザ", "pizza", "", "", "die Pizzen", ""),
    ("die Wurst", "noun", "die", "ソーセージ", "sausage", "", "", "die Würste", ""),
    ("der Schinken", "noun", "der", "ハム", "ham", "", "", "die Schinken", ""),
    ("das Hähnchen", "noun", "das", "若鶏", "chicken (dish)", "", "", "die Hähnchen", ""),
    ("das Schwein", "noun", "das", "豚／豚肉", "pig, pork", "", "", "die Schweine", ""),
    ("das Rind", "noun", "das", "牛／牛肉", "cattle, beef", "", "", "die Rinder", ""),
    ("der Fisch", "noun", "der", "魚", "fish", "", "", "die Fische", ""),
    ("der Lachs", "noun", "der", "鮭", "salmon", "", "", "die Lachse", ""),
    ("die Garnele", "noun", "die", "エビ", "shrimp", "", "", "die Garnelen", ""),
    ("die Banane", "noun", "die", "バナナ", "banana", "", "", "die Bananen", ""),
    ("die Orange", "noun", "die", "オレンジ", "orange", "", "", "die Orangen", ""),
    ("die Zitrone", "noun", "die", "レモン", "lemon", "", "", "die Zitronen", ""),
    ("die Erdbeere", "noun", "die", "イチゴ", "strawberry", "", "", "die Erdbeeren", ""),
    ("die Kirsche", "noun", "die", "サクランボ", "cherry", "", "", "die Kirschen", ""),
    ("die Birne", "noun", "die", "ナシ", "pear", "", "", "die Birnen", ""),
    ("die Traube", "noun", "die", "ブドウ", "grape", "", "", "die Trauben", ""),
    ("die Tomate", "noun", "die", "トマト", "tomato", "", "", "die Tomaten", ""),
    ("die Karotte", "noun", "die", "ニンジン", "carrot", "", "", "die Karotten", ""),
    ("die Möhre", "noun", "die", "ニンジン", "carrot (regional)", "", "", "die Möhren", ""),
    ("die Gurke", "noun", "die", "キュウリ", "cucumber", "", "", "die Gurken", ""),
    ("der Salat", "noun", "der", "レタス／サラダ", "lettuce, salad", "", "", "die Salate", ""),
    ("die Paprika", "noun", "die", "パプリカ", "bell pepper", "", "", "die Paprikas", ""),
    ("die Zwiebel", "noun", "die", "玉ねぎ", "onion", "", "", "die Zwiebeln", ""),
    ("der Knoblauch", "noun", "der", "ニンニク", "garlic", "", "", "", ""),
    ("die Pilz", "noun", "der", "キノコ", "mushroom", "", "", "die Pilze", "der Pilz"),
    ("der Reis", "noun", "der", "米", "rice", "", "", "", ""),
    ("die Bohne", "noun", "die", "豆", "bean", "", "", "die Bohnen", ""),
    ("das Ei", "noun", "das", "卵", "egg", "", "", "die Eier", ""),
    ("die Butter", "noun", "die", "バター", "butter", "", "", "", ""),
    ("die Marmelade", "noun", "die", "ジャム", "jam", "", "", "die Marmeladen", ""),
    ("der Honig", "noun", "der", "蜂蜜", "honey", "", "", "", ""),
    ("der Zucker", "noun", "der", "砂糖", "sugar", "", "", "", ""),
    ("das Salz", "noun", "das", "塩", "salt", "", "", "die Salze", ""),
    ("der Pfeffer", "noun", "der", "コショウ", "pepper", "", "", "", ""),
    ("das Öl", "noun", "das", "油", "oil", "", "", "die Öle", ""),
    ("der Essig", "noun", "der", "酢", "vinegar", "", "", "", ""),
    ("der Senf", "noun", "der", "マスタード", "mustard", "", "", "", ""),
    ("das Mehl", "noun", "das", "小麦粉", "flour", "", "", "die Mehle", ""),
    ("der Kuchen", "noun", "der", "ケーキ", "cake", "", "", "die Kuchen", ""),
    ("die Torte", "noun", "die", "タルト", "tart, cake", "", "", "die Torten", ""),
    ("das Eis", "noun", "das", "アイス／氷", "ice cream, ice", "", "", "", ""),
    ("die Schokolade", "noun", "die", "チョコレート", "chocolate", "", "", "die Schokoladen", ""),
    ("der Saft", "noun", "der", "ジュース", "juice", "", "", "die Säfte", ""),
    ("das Mineralwasser", "noun", "das", "ミネラルウォーター", "mineral water", "", "", "die Mineralwässer", ""),
    ("der Wein", "noun", "der", "ワイン", "wine", "", "", "die Weine", ""),
    ("der Sekt", "noun", "der", "スパークリングワイン", "sparkling wine", "", "", "die Sekte", ""),
    ("der Schnaps", "noun", "der", "蒸留酒", "schnapps", "", "", "die Schnäpse", ""),
    ("der Cocktail", "noun", "der", "カクテル", "cocktail", "", "", "die Cocktails", ""),
    ("durstig", "adj", "", "のどが渇いた", "thirsty", "", "", "", ""),
    ("hungrig", "adj", "", "空腹の", "hungry", "", "", "", ""),
    ("satt", "adj", "", "満腹の", "full", "", "", "", ""),
    ("lecker", "adj", "", "おいしい", "delicious", "", "", "", ""),
    ("süß", "adj", "", "甘い", "sweet", "", "", "", ""),
    ("sauer", "adj", "", "酸っぱい／怒った", "sour, angry", "", "", "", ""),
    ("salzig", "adj", "", "塩辛い", "salty", "", "", "", ""),
    ("scharf", "adj", "", "辛い", "spicy, sharp", "", "", "", ""),
    ("bitter", "adj", "", "苦い", "bitter", "", "", "", ""),
    ("schmecken", "verb", "", "味がする", "to taste", "schmeckte", "hat geschmeckt", "", ""),
    ("bestellen", "verb", "", "注文する", "to order", "bestellte", "hat bestellt", "", ""),
    ("servieren", "verb", "", "給仕する", "to serve", "servierte", "hat serviert", "", ""),

    # ---------- Travel & transport (extended) ----------
    ("die Reise", "noun", "die", "旅行", "trip, journey", "", "", "die Reisen", ""),
    ("reisen", "verb", "", "旅する", "to travel", "reiste", "ist gereist", "", ""),
    ("die Ferien", "noun", "die", "休暇", "holidays", "", "", "", "plural"),
    ("der Urlaub", "noun", "der", "休暇", "vacation", "", "", "die Urlaube", ""),
    ("buchen", "verb", "", "予約する", "to book", "buchte", "hat gebucht", "", ""),
    ("die Buchung", "noun", "die", "予約", "booking", "", "", "die Buchungen", ""),
    ("die Reservierung", "noun", "die", "予約", "reservation", "", "", "die Reservierungen", ""),
    ("reservieren", "verb", "", "予約する", "to reserve", "reservierte", "hat reserviert", "", ""),
    ("der Flug", "noun", "der", "フライト", "flight", "", "", "die Flüge", ""),
    ("der Flughafen", "noun", "der", "空港", "airport", "", "", "die Flughäfen", ""),
    ("das Flugzeug", "noun", "das", "飛行機", "airplane", "", "", "die Flugzeuge", ""),
    ("fliegen", "verb", "", "飛ぶ", "to fly", "flog", "ist geflogen", "", "irregular"),
    ("die Landung", "noun", "die", "着陸", "landing", "", "", "die Landungen", ""),
    ("landen", "verb", "", "着陸する", "to land", "landete", "ist gelandet", "", ""),
    ("starten", "verb", "", "離陸する／始める", "to take off, to start", "startete", "ist gestartet", "", ""),
    ("der Koffer", "noun", "der", "スーツケース", "suitcase", "", "", "die Koffer", ""),
    ("das Gepäck", "noun", "das", "荷物", "luggage", "", "", "", ""),
    ("der Rucksack", "noun", "der", "リュック", "backpack", "", "", "die Rucksäcke", ""),
    ("die Tasche", "noun", "die", "バッグ", "bag", "", "", "die Taschen", ""),
    ("der Pass", "noun", "der", "パスポート", "passport", "", "", "die Pässe", ""),
    ("der Reisepass", "noun", "der", "パスポート", "passport", "", "", "die Reisepässe", ""),
    ("das Visum", "noun", "das", "ビザ", "visa", "", "", "die Visa", ""),
    ("die Grenze", "noun", "die", "国境", "border", "", "", "die Grenzen", ""),
    ("das Hotel", "noun", "das", "ホテル", "hotel", "", "", "die Hotels", ""),
    ("die Pension", "noun", "die", "民宿", "guesthouse", "", "", "die Pensionen", ""),
    ("die Jugendherberge", "noun", "die", "ユースホステル", "youth hostel", "", "", "die Jugendherbergen", ""),
    ("das Zelt", "noun", "das", "テント", "tent", "", "", "die Zelte", ""),
    ("zelten", "verb", "", "キャンプする", "to camp", "zeltete", "hat gezeltet", "", ""),
    ("der Campingplatz", "noun", "der", "キャンプ場", "campsite", "", "", "die Campingplätze", ""),
    ("die Sehenswürdigkeit", "noun", "die", "観光名所", "sight", "", "", "die Sehenswürdigkeiten", ""),
    ("besichtigen", "verb", "", "見学する", "to visit, to view", "besichtigte", "hat besichtigt", "", ""),
    ("die Führung", "noun", "die", "ガイドツアー", "guided tour", "", "", "die Führungen", ""),
    ("der Reiseführer", "noun", "der", "ガイドブック", "guidebook, tour guide", "", "", "die Reiseführer", ""),
    ("die Karte", "noun", "die", "地図／カード", "map, card", "", "", "die Karten", ""),
    ("die Landkarte", "noun", "die", "地図", "map", "", "", "die Landkarten", ""),
    ("der Stadtplan", "noun", "der", "市街地図", "city map", "", "", "die Stadtpläne", ""),
    ("der Tourist", "noun", "der", "観光客", "tourist", "", "", "die Touristen", "n-decl"),
    ("das Souvenir", "noun", "das", "お土産", "souvenir", "", "", "die Souvenirs", ""),
    ("der Stempel", "noun", "der", "スタンプ", "stamp (rubber)", "", "", "die Stempel", ""),
    ("die Auskunft", "noun", "die", "案内／情報", "information desk", "", "", "die Auskünfte", ""),
    ("die Information", "noun", "die", "情報", "information", "", "", "die Informationen", ""),
    ("die Verspätung", "noun", "die", "遅延", "delay", "", "", "die Verspätungen", ""),
    ("die Ankunft", "noun", "die", "到着", "arrival", "", "", "die Ankünfte", ""),
    ("die Abfahrt", "noun", "die", "出発", "departure", "", "", "die Abfahrten", ""),
    ("der Zug", "noun", "der", "電車", "train", "", "", "die Züge", ""),
    ("die Bahn", "noun", "die", "鉄道", "railway", "", "", "die Bahnen", ""),
    ("die S-Bahn", "noun", "die", "Sバーン", "city train", "", "", "die S-Bahnen", ""),
    ("die U-Bahn", "noun", "die", "地下鉄", "subway", "", "", "die U-Bahnen", ""),
    ("die Straßenbahn", "noun", "die", "路面電車", "tram", "", "", "die Straßenbahnen", ""),
    ("das Gleis", "noun", "das", "ホーム", "platform", "", "", "die Gleise", ""),
    ("der Bahnsteig", "noun", "der", "ホーム", "platform", "", "", "die Bahnsteige", ""),
    ("die Haltestelle", "noun", "die", "停留所", "stop", "", "", "die Haltestellen", ""),
    ("die Strecke", "noun", "die", "区間", "route, stretch", "", "", "die Strecken", ""),
    ("der Fahrplan", "noun", "der", "時刻表", "timetable", "", "", "die Fahrpläne", ""),
    ("die Fahrkarte", "noun", "die", "乗車券", "ticket", "", "", "die Fahrkarten", ""),
    ("der Fahrschein", "noun", "der", "乗車券", "ticket", "", "", "die Fahrscheine", ""),
    ("das Ticket", "noun", "das", "チケット", "ticket", "", "", "die Tickets", ""),
    ("einsteigen", "verb", "", "乗る", "to get on", "stieg ein", "ist eingestiegen", "", "irregular"),
    ("aussteigen", "verb", "", "降りる", "to get off", "stieg aus", "ist ausgestiegen", "", "irregular"),
    ("umsteigen", "verb", "", "乗り換える", "to transfer", "stieg um", "ist umgestiegen", "", "irregular"),
    ("der Schaffner", "noun", "der", "車掌", "conductor", "", "", "die Schaffner", ""),

    # ---------- Verbs (extended modal & frequent) ----------
    ("dürfen", "verb", "", "～してもよい", "to be allowed to", "durfte", "hat gedurft", "", "modal"),
    ("müssen", "verb", "", "～しなければならない", "must, to have to", "musste", "hat gemusst", "", "modal"),
    ("sollen", "verb", "", "～すべき", "should", "sollte", "hat gesollt", "", "modal"),
    ("wollen", "verb", "", "～したい", "to want", "wollte", "hat gewollt", "", "modal"),
    ("möchten", "verb", "", "～したいのですが", "would like", "wollte", "", "", "Konj II"),
    ("erlauben", "verb", "", "許可する", "to allow", "erlaubte", "hat erlaubt", "", ""),
    ("verbieten", "verb", "", "禁止する", "to forbid", "verbot", "hat verboten", "", "irregular"),
    ("vergessen", "verb", "", "忘れる", "to forget", "vergaß", "hat vergessen", "", "irregular"),
    ("sich erinnern", "verb", "", "思い出す", "to remember", "erinnerte sich", "hat sich erinnert", "", ""),
    ("wiederholen", "verb", "", "繰り返す", "to repeat", "wiederholte", "hat wiederholt", "", ""),
    ("erklären", "verb", "", "説明する", "to explain", "erklärte", "hat erklärt", "", ""),
    ("beschreiben", "verb", "", "描写する", "to describe", "beschrieb", "hat beschrieben", "", "irregular"),
    ("erzählen", "verb", "", "語る", "to tell, to narrate", "erzählte", "hat erzählt", "", ""),
    ("berichten", "verb", "", "報告する", "to report", "berichtete", "hat berichtet", "", ""),
    ("zeigen", "verb", "", "見せる", "to show", "zeigte", "hat gezeigt", "", ""),
    ("zeichnen", "verb", "", "描く", "to draw", "zeichnete", "hat gezeichnet", "", ""),
    ("schenken", "verb", "", "贈る", "to give as a gift", "schenkte", "hat geschenkt", "", ""),
    ("gratulieren", "verb", "", "祝う", "to congratulate", "gratulierte", "hat gratuliert", "", ""),
    ("einladen", "verb", "", "招待する", "to invite", "lud ein", "hat eingeladen", "", "irregular"),
    ("besuchen", "verb", "", "訪問する", "to visit", "besuchte", "hat besucht", "", ""),
    ("treffen", "verb", "", "会う", "to meet", "traf", "hat getroffen", "", "irregular"),
    ("verabreden", "verb", "", "約束する", "to arrange a meeting", "verabredete", "hat verabredet", "", ""),
    ("warten", "verb", "", "待つ", "to wait", "wartete", "hat gewartet", "", ""),
    ("suchen", "verb", "", "探す", "to search", "suchte", "hat gesucht", "", ""),
    ("finden", "verb", "", "見つける", "to find", "fand", "hat gefunden", "", "irregular"),
    ("verlieren", "verb", "", "失う", "to lose", "verlor", "hat verloren", "", "irregular"),
    ("gewinnen", "verb", "", "勝つ", "to win", "gewann", "hat gewonnen", "", "irregular"),
    ("verwenden", "verb", "", "使用する", "to use", "verwendete", "hat verwendet", "", ""),
    ("benutzen", "verb", "", "使う", "to use", "benutzte", "hat benutzt", "", ""),
    ("brauchen", "verb", "", "必要とする", "to need", "brauchte", "hat gebraucht", "", ""),
    ("benötigen", "verb", "", "必要とする", "to require", "benötigte", "hat benötigt", "", ""),
    ("versuchen", "verb", "", "試みる", "to try", "versuchte", "hat versucht", "", ""),
    ("schaffen", "verb", "", "やり遂げる", "to manage", "schaffte", "hat geschafft", "", ""),
    ("gelingen", "verb", "", "成功する", "to succeed", "gelang", "ist gelungen", "", "irregular"),
    ("scheitern", "verb", "", "失敗する", "to fail", "scheiterte", "ist gescheitert", "", ""),
    ("entscheiden", "verb", "", "決定する", "to decide", "entschied", "hat entschieden", "", "irregular"),
    ("entwickeln", "verb", "", "発展させる", "to develop", "entwickelte", "hat entwickelt", "", ""),
    ("ändern", "verb", "", "変える", "to change", "änderte", "hat geändert", "", ""),
    ("verändern", "verb", "", "変化させる", "to change", "veränderte", "hat verändert", "", ""),
    ("sich ändern", "verb", "", "変わる", "to change (intransitive)", "änderte sich", "hat sich geändert", "", ""),
    ("bedeuten", "verb", "", "意味する", "to mean", "bedeutete", "hat bedeutet", "", ""),
    ("bestehen", "verb", "", "合格する／存在する", "to pass, to consist of", "bestand", "hat bestanden", "", "irregular"),
    ("besitzen", "verb", "", "所有する", "to own", "besaß", "hat besessen", "", "irregular"),
    ("bekommen", "verb", "", "得る", "to receive, to get", "bekam", "hat bekommen", "", "irregular"),
    ("erhalten", "verb", "", "受け取る", "to receive", "erhielt", "hat erhalten", "", "irregular"),
    ("schicken", "verb", "", "送る", "to send", "schickte", "hat geschickt", "", ""),
    ("senden", "verb", "", "送る", "to send", "sandte", "hat gesandt", "", "mixed"),
    ("zustellen", "verb", "", "配達する", "to deliver", "stellte zu", "hat zugestellt", "", ""),
    ("anbieten", "verb", "", "提供する", "to offer", "bot an", "hat angeboten", "", "irregular"),
    ("annehmen", "verb", "", "受け入れる", "to accept", "nahm an", "hat angenommen", "", "irregular"),
    ("ablehnen", "verb", "", "拒否する", "to reject", "lehnte ab", "hat abgelehnt", "", ""),
    ("teilen", "verb", "", "分ける／共有する", "to share, to divide", "teilte", "hat geteilt", "", ""),
    ("verteilen", "verb", "", "分配する", "to distribute", "verteilte", "hat verteilt", "", ""),
    ("zählen", "verb", "", "数える", "to count", "zählte", "hat gezählt", "", ""),
    ("rechnen", "verb", "", "計算する", "to calculate", "rechnete", "hat gerechnet", "", ""),
    ("messen", "verb", "", "測る", "to measure", "maß", "hat gemessen", "", "irregular"),
    ("wiegen", "verb", "", "重さを量る", "to weigh", "wog", "hat gewogen", "", "irregular"),
    ("dauern", "verb", "", "続く", "to last", "dauerte", "hat gedauert", "", ""),
    ("beginnen", "verb", "", "始まる", "to begin", "begann", "hat begonnen", "", "irregular"),
    ("starten", "verb", "", "始める／離陸", "to start", "startete", "ist gestartet", "", ""),
    ("aufhören", "verb", "", "やめる", "to stop", "hörte auf", "hat aufgehört", "", ""),
    ("beenden", "verb", "", "終える", "to finish", "beendete", "hat beendet", "", ""),
    ("fortsetzen", "verb", "", "続ける", "to continue", "setzte fort", "hat fortgesetzt", "", ""),
    ("weitergehen", "verb", "", "進み続ける", "to go on", "ging weiter", "ist weitergegangen", "", "irregular"),
    ("vorbereiten", "verb", "", "準備する", "to prepare", "bereitete vor", "hat vorbereitet", "", ""),
    ("aufräumen", "verb", "", "片づける", "to tidy up", "räumte auf", "hat aufgeräumt", "", ""),
    ("ordnen", "verb", "", "整える", "to arrange", "ordnete", "hat geordnet", "", ""),
    ("vergleichen", "verb", "", "比較する", "to compare", "verglich", "hat verglichen", "", "irregular"),
    ("unterscheiden", "verb", "", "区別する", "to differentiate", "unterschied", "hat unterschieden", "", "irregular"),
    ("erkennen", "verb", "", "認識する", "to recognize", "erkannte", "hat erkannt", "", "mixed"),
    ("verstehen", "verb", "", "理解する", "to understand", "verstand", "hat verstanden", "", "irregular"),
    ("missverstehen", "verb", "", "誤解する", "to misunderstand", "missverstand", "hat missverstanden", "", "irregular"),
    ("übersetzen", "verb", "", "翻訳する", "to translate", "übersetzte", "hat übersetzt", "", ""),
    ("erlernen", "verb", "", "習得する", "to learn", "erlernte", "hat erlernt", "", ""),
    ("unterrichten", "verb", "", "教える", "to teach", "unterrichtete", "hat unterrichtet", "", ""),
    ("üben", "verb", "", "練習する", "to practice", "übte", "hat geübt", "", ""),
    ("trainieren", "verb", "", "訓練する", "to train", "trainierte", "hat trainiert", "", ""),
    ("vorlesen", "verb", "", "音読する", "to read aloud", "las vor", "hat vorgelesen", "", "irregular"),
    ("notieren", "verb", "", "書き留める", "to note", "notierte", "hat notiert", "", ""),
    ("aufschreiben", "verb", "", "書き留める", "to write down", "schrieb auf", "hat aufgeschrieben", "", "irregular"),
    ("unterschreiben", "verb", "", "署名する", "to sign", "unterschrieb", "hat unterschrieben", "", "irregular"),
    ("ausfüllen", "verb", "", "記入する", "to fill out", "füllte aus", "hat ausgefüllt", "", ""),
    ("drucken", "verb", "", "印刷する", "to print", "druckte", "hat gedruckt", "", ""),
    ("kopieren", "verb", "", "コピーする", "to copy", "kopierte", "hat kopiert", "", ""),
    ("scannen", "verb", "", "スキャンする", "to scan", "scannte", "hat gescannt", "", ""),
    ("klicken", "verb", "", "クリックする", "to click", "klickte", "hat geklickt", "", ""),
    ("speichern", "verb", "", "保存する", "to save", "speicherte", "hat gespeichert", "", ""),
    ("löschen", "verb", "", "削除する", "to delete", "löschte", "hat gelöscht", "", ""),

    # ---------- Communication ----------
    ("die Kommunikation", "noun", "die", "コミュニケーション", "communication", "", "", "die Kommunikationen", ""),
    ("das Gespräch", "noun", "das", "会話", "conversation", "", "", "die Gespräche", ""),
    ("die Unterhaltung", "noun", "die", "雑談／娯楽", "conversation, entertainment", "", "", "die Unterhaltungen", ""),
    ("die Diskussion", "noun", "die", "議論", "discussion", "", "", "die Diskussionen", ""),
    ("diskutieren", "verb", "", "議論する", "to discuss", "diskutierte", "hat diskutiert", "", ""),
    ("der Streit", "noun", "der", "口論", "argument, quarrel", "", "", "die Streite", ""),
    ("sich streiten", "verb", "", "言い争う", "to quarrel", "stritt sich", "hat sich gestritten", "", "irregular"),
    ("die Meinung", "noun", "die", "意見", "opinion", "", "", "die Meinungen", ""),
    ("der Vorschlag", "noun", "der", "提案", "suggestion", "", "", "die Vorschläge", ""),
    ("vorschlagen", "verb", "", "提案する", "to suggest", "schlug vor", "hat vorgeschlagen", "", "irregular"),
    ("die Idee", "noun", "die", "アイディア", "idea", "", "", "die Ideen", ""),
    ("der Plan", "noun", "der", "計画", "plan", "", "", "die Pläne", ""),
    ("planen", "verb", "", "計画する", "to plan", "plante", "hat geplant", "", ""),
    ("die Lösung", "noun", "die", "解決策", "solution", "", "", "die Lösungen", ""),
    ("lösen", "verb", "", "解く", "to solve", "löste", "hat gelöst", "", ""),
    ("das Problem", "noun", "das", "問題", "problem", "", "", "die Probleme", ""),
    ("die Frage", "noun", "die", "質問", "question", "", "", "die Fragen", ""),
    ("die Antwort", "noun", "die", "回答", "answer", "", "", "die Antworten", ""),
    ("die Mitteilung", "noun", "die", "通知", "notification", "", "", "die Mitteilungen", ""),
    ("die Nachricht", "noun", "die", "知らせ／ニュース", "message, news", "", "", "die Nachrichten", ""),
    ("die SMS", "noun", "die", "ショートメッセージ", "text message", "", "", "die SMS", ""),
    ("die E-Mail", "noun", "die", "Eメール", "e-mail", "", "", "die E-Mails", ""),
    ("der Brief", "noun", "der", "手紙", "letter", "", "", "die Briefe", ""),
    ("die Postkarte", "noun", "die", "はがき", "postcard", "", "", "die Postkarten", ""),
    ("der Umschlag", "noun", "der", "封筒", "envelope", "", "", "die Umschläge", ""),
    ("die Briefmarke", "noun", "die", "切手", "stamp", "", "", "die Briefmarken", ""),
    ("die Post", "noun", "die", "郵便", "post", "", "", "", ""),
    ("der Briefkasten", "noun", "der", "郵便ポスト", "letterbox", "", "", "die Briefkästen", ""),
    ("das Paket", "noun", "das", "小包", "package", "", "", "die Pakete", ""),
    ("verschicken", "verb", "", "発送する", "to dispatch", "verschickte", "hat verschickt", "", ""),
    ("anrufen", "verb", "", "電話する", "to call", "rief an", "hat angerufen", "", "irregular"),
    ("zurückrufen", "verb", "", "折り返し電話する", "to call back", "rief zurück", "hat zurückgerufen", "", "irregular"),
    ("auflegen", "verb", "", "電話を切る", "to hang up", "legte auf", "hat aufgelegt", "", ""),
    ("die Nummer", "noun", "die", "番号", "number", "", "", "die Nummern", ""),
    ("die Telefonnummer", "noun", "die", "電話番号", "phone number", "", "", "die Telefonnummern", ""),
    ("die Vorwahl", "noun", "die", "市外局番", "area code", "", "", "die Vorwahlen", ""),
    ("die Verbindung", "noun", "die", "接続", "connection", "", "", "die Verbindungen", ""),

    # ---------- Internet & technology ----------
    ("das Internet", "noun", "das", "インターネット", "internet", "", "", "", ""),
    ("die Webseite", "noun", "die", "ウェブサイト", "website", "", "", "die Webseiten", ""),
    ("die Adresse", "noun", "die", "アドレス", "address", "", "", "die Adressen", ""),
    ("der Computer", "noun", "der", "コンピューター", "computer", "", "", "die Computer", ""),
    ("der Laptop", "noun", "der", "ノートPC", "laptop", "", "", "die Laptops", ""),
    ("das Smartphone", "noun", "das", "スマートフォン", "smartphone", "", "", "die Smartphones", ""),
    ("das Tablet", "noun", "das", "タブレット", "tablet", "", "", "die Tablets", ""),
    ("der Bildschirm", "noun", "der", "画面", "screen", "", "", "die Bildschirme", ""),
    ("die Tastatur", "noun", "die", "キーボード", "keyboard", "", "", "die Tastaturen", ""),
    ("die Maus", "noun", "die", "マウス／ねずみ", "mouse", "", "", "die Mäuse", ""),
    ("der Drucker", "noun", "der", "プリンター", "printer", "", "", "die Drucker", ""),
    ("das Programm", "noun", "das", "プログラム", "program", "", "", "die Programme", ""),
    ("die App", "noun", "die", "アプリ", "app", "", "", "die Apps", ""),
    ("die Datei", "noun", "die", "ファイル", "file", "", "", "die Dateien", ""),
    ("der Ordner", "noun", "der", "フォルダ", "folder", "", "", "die Ordner", ""),
    ("das Foto", "noun", "das", "写真", "photo", "", "", "die Fotos", ""),
    ("das Video", "noun", "das", "動画", "video", "", "", "die Videos", ""),
    ("das Passwort", "noun", "das", "パスワード", "password", "", "", "die Passwörter", ""),
    ("der Benutzername", "noun", "der", "ユーザー名", "username", "", "", "die Benutzernamen", ""),
    ("herunterladen", "verb", "", "ダウンロードする", "to download", "lud herunter", "hat heruntergeladen", "", "irregular"),
    ("hochladen", "verb", "", "アップロードする", "to upload", "lud hoch", "hat hochgeladen", "", "irregular"),
    ("verbinden", "verb", "", "接続する", "to connect", "verband", "hat verbunden", "", "irregular"),
    ("trennen", "verb", "", "切断する", "to disconnect, to separate", "trennte", "hat getrennt", "", ""),
    ("online", "adj", "", "オンラインの", "online", "", "", "", ""),
    ("offline", "adj", "", "オフラインの", "offline", "", "", "", ""),
    ("digital", "adj", "", "デジタルの", "digital", "", "", "", ""),
    ("sozial", "adj", "", "社会的な", "social", "", "", "", ""),

    # ---------- Education (extended) ----------
    ("die Bildung", "noun", "die", "教育", "education", "", "", "", ""),
    ("die Grundschule", "noun", "die", "小学校", "primary school", "", "", "die Grundschulen", ""),
    ("das Gymnasium", "noun", "das", "ギムナジウム", "high school", "", "", "die Gymnasien", ""),
    ("die Realschule", "noun", "die", "実科学校", "secondary school", "", "", "die Realschulen", ""),
    ("die Hochschule", "noun", "die", "高等専門学校", "college", "", "", "die Hochschulen", ""),
    ("der Studiengang", "noun", "der", "専攻", "degree program", "", "", "die Studiengänge", ""),
    ("der Student", "noun", "der", "大学生", "student (university)", "", "", "die Studenten", "n-decl"),
    ("die Studentin", "noun", "die", "大学生（女）", "student (f)", "", "", "die Studentinnen", ""),
    ("der Professor", "noun", "der", "教授", "professor", "", "", "die Professoren", ""),
    ("die Vorlesung", "noun", "die", "講義", "lecture", "", "", "die Vorlesungen", ""),
    ("das Seminar", "noun", "das", "セミナー", "seminar", "", "", "die Seminare", ""),
    ("das Semester", "noun", "das", "学期", "semester", "", "", "die Semester", ""),
    ("die Klausur", "noun", "die", "筆記試験", "written exam", "", "", "die Klausuren", ""),
    ("der Abschluss", "noun", "der", "卒業", "degree", "", "", "die Abschlüsse", ""),
    ("das Diplom", "noun", "das", "学位", "diploma", "", "", "die Diplome", ""),
    ("das Stipendium", "noun", "das", "奨学金", "scholarship", "", "", "die Stipendien", ""),
    ("das Wissen", "noun", "das", "知識", "knowledge", "", "", "", ""),
    ("die Kenntnis", "noun", "die", "知識", "knowledge", "", "", "die Kenntnisse", ""),
    ("die Sprache", "noun", "die", "言語", "language", "", "", "die Sprachen", ""),
    ("die Muttersprache", "noun", "die", "母語", "mother tongue", "", "", "die Muttersprachen", ""),
    ("die Fremdsprache", "noun", "die", "外国語", "foreign language", "", "", "die Fremdsprachen", ""),
    ("die Übung", "noun", "die", "練習", "exercise", "", "", "die Übungen", ""),
    ("der Aufsatz", "noun", "der", "作文", "essay", "", "", "die Aufsätze", ""),
    ("die Lösung", "noun", "die", "解答", "solution", "", "", "die Lösungen", ""),
    ("die Aufgabe", "noun", "die", "課題", "task", "", "", "die Aufgaben", ""),

    # ---------- Society & politics ----------
    ("die Gesellschaft", "noun", "die", "社会", "society", "", "", "die Gesellschaften", ""),
    ("das Volk", "noun", "das", "民族", "people, folk", "", "", "die Völker", ""),
    ("die Bevölkerung", "noun", "die", "人口", "population", "", "", "die Bevölkerungen", ""),
    ("die Regierung", "noun", "die", "政府", "government", "", "", "die Regierungen", ""),
    ("die Politik", "noun", "die", "政治", "politics", "", "", "", ""),
    ("die Wahl", "noun", "die", "選挙／選択", "election, choice", "", "", "die Wahlen", ""),
    ("wählen", "verb", "", "選ぶ／投票する", "to choose, to vote", "wählte", "hat gewählt", "", ""),
    ("die Partei", "noun", "die", "政党", "party", "", "", "die Parteien", ""),
    ("das Gesetz", "noun", "das", "法律", "law", "", "", "die Gesetze", ""),
    ("die Demokratie", "noun", "die", "民主主義", "democracy", "", "", "die Demokratien", ""),
    ("der Präsident", "noun", "der", "大統領", "president", "", "", "die Präsidenten", "n-decl"),
    ("der Kanzler", "noun", "der", "首相", "chancellor", "", "", "die Kanzler", ""),
    ("der Minister", "noun", "der", "大臣", "minister", "", "", "die Minister", ""),
    ("die Stadt", "noun", "die", "都市", "city", "", "", "die Städte", ""),
    ("das Land", "noun", "das", "国", "country", "", "", "die Länder", ""),
    ("der Staat", "noun", "der", "国家", "state", "", "", "die Staaten", ""),
    ("die Heimat", "noun", "die", "故郷", "homeland", "", "", "die Heimaten", ""),
    ("der Ausländer", "noun", "der", "外国人", "foreigner", "", "", "die Ausländer", ""),
    ("der Flüchtling", "noun", "der", "難民", "refugee", "", "", "die Flüchtlinge", ""),
    ("die Religion", "noun", "die", "宗教", "religion", "", "", "die Religionen", ""),
    ("die Kirche", "noun", "die", "教会", "church", "", "", "die Kirchen", ""),
    ("die Moschee", "noun", "die", "モスク", "mosque", "", "", "die Moscheen", ""),
    ("der Tempel", "noun", "der", "寺院", "temple", "", "", "die Tempel", ""),
    ("der Gott", "noun", "der", "神", "god", "", "", "die Götter", ""),
    ("die Kultur", "noun", "die", "文化", "culture", "", "", "die Kulturen", ""),
    ("die Tradition", "noun", "die", "伝統", "tradition", "", "", "die Traditionen", ""),
    ("die Geschichte", "noun", "die", "歴史／物語", "history, story", "", "", "die Geschichten", ""),

    # ---------- Leisure & hobbies (extended) ----------
    ("das Hobby", "noun", "das", "趣味", "hobby", "", "", "die Hobbys", ""),
    ("die Freizeit", "noun", "die", "余暇", "free time", "", "", "", ""),
    ("der Spaß", "noun", "der", "楽しみ", "fun", "", "", "die Späße", ""),
    ("das Vergnügen", "noun", "das", "楽しみ", "pleasure", "", "", "die Vergnügen", ""),
    ("der Sport", "noun", "der", "スポーツ", "sport", "", "", "die Sportarten", ""),
    ("treiben", "verb", "", "（スポーツを）する", "to do (sport)", "trieb", "hat getrieben", "", "irregular"),
    ("joggen", "verb", "", "ジョギングする", "to jog", "joggte", "ist gejoggt", "", ""),
    ("laufen", "verb", "", "走る／歩く", "to run", "lief", "ist gelaufen", "", "irregular"),
    ("schwimmen", "verb", "", "泳ぐ", "to swim", "schwamm", "ist geschwommen", "", "irregular"),
    ("radfahren", "verb", "", "自転車に乗る", "to cycle", "fuhr Rad", "ist Rad gefahren", "", "irregular"),
    ("Ski fahren", "verb", "", "スキーをする", "to ski", "fuhr Ski", "ist Ski gefahren", "", "irregular"),
    ("der Skiort", "noun", "der", "スキー場", "ski resort", "", "", "die Skiorte", ""),
    ("der Tennisplatz", "noun", "der", "テニスコート", "tennis court", "", "", "die Tennisplätze", ""),
    ("der Fitness", "noun", "der", "フィットネス", "fitness", "", "", "", ""),
    ("das Fitnessstudio", "noun", "das", "ジム", "gym", "", "", "die Fitnessstudios", ""),
    ("die Mannschaft", "noun", "die", "チーム", "team", "", "", "die Mannschaften", ""),
    ("der Verein", "noun", "der", "クラブ", "club, association", "", "", "die Vereine", ""),
    ("der Spieler", "noun", "der", "選手", "player", "", "", "die Spieler", ""),
    ("der Trainer", "noun", "der", "コーチ", "coach", "", "", "die Trainer", ""),
    ("das Turnier", "noun", "das", "トーナメント", "tournament", "", "", "die Turniere", ""),
    ("der Wettkampf", "noun", "der", "競技", "competition", "", "", "die Wettkämpfe", ""),
    ("das Tor", "noun", "das", "ゴール／門", "goal, gate", "", "", "die Tore", ""),
    ("der Schiedsrichter", "noun", "der", "審判", "referee", "", "", "die Schiedsrichter", ""),
    ("der Sieg", "noun", "der", "勝利", "victory", "", "", "die Siege", ""),
    ("die Niederlage", "noun", "die", "敗北", "defeat", "", "", "die Niederlagen", ""),
    ("die Medaille", "noun", "die", "メダル", "medal", "", "", "die Medaillen", ""),
    ("das Konzert", "noun", "das", "コンサート", "concert", "", "", "die Konzerte", ""),
    ("die Oper", "noun", "die", "オペラ", "opera", "", "", "die Opern", ""),
    ("das Theater", "noun", "das", "劇場", "theatre", "", "", "die Theater", ""),
    ("das Stück", "noun", "das", "劇／一部", "play, piece", "", "", "die Stücke", ""),
    ("die Vorstellung", "noun", "die", "上演／想像", "performance, idea", "", "", "die Vorstellungen", ""),
    ("die Karte", "noun", "die", "入場券", "ticket, card", "", "", "die Karten", ""),
    ("die Eintrittskarte", "noun", "die", "入場券", "admission ticket", "", "", "die Eintrittskarten", ""),
    ("der Eintritt", "noun", "der", "入場（料）", "admission", "", "", "die Eintritte", ""),
    ("die Ausstellung", "noun", "die", "展示", "exhibition", "", "", "die Ausstellungen", ""),
    ("die Galerie", "noun", "die", "ギャラリー", "gallery", "", "", "die Galerien", ""),
    ("die Bibliothek", "noun", "die", "図書館", "library", "", "", "die Bibliotheken", ""),
    ("die Zeitschrift", "noun", "die", "雑誌", "magazine", "", "", "die Zeitschriften", ""),
    ("die Zeitung", "noun", "die", "新聞", "newspaper", "", "", "die Zeitungen", ""),
    ("der Roman", "noun", "der", "小説", "novel", "", "", "die Romane", ""),
    ("das Märchen", "noun", "das", "童話", "fairy tale", "", "", "die Märchen", ""),
    ("das Gedicht", "noun", "das", "詩", "poem", "", "", "die Gedichte", ""),
    ("die Musik", "noun", "die", "音楽", "music", "", "", "", ""),
    ("die Band", "noun", "die", "バンド", "band", "", "", "die Bands", ""),
    ("das Lied", "noun", "das", "歌", "song", "", "", "die Lieder", ""),
    ("das Instrument", "noun", "das", "楽器", "instrument", "", "", "die Instrumente", ""),
    ("die Gitarre", "noun", "die", "ギター", "guitar", "", "", "die Gitarren", ""),
    ("das Klavier", "noun", "das", "ピアノ", "piano", "", "", "die Klaviere", ""),
    ("das Schlagzeug", "noun", "das", "ドラム", "drums", "", "", "die Schlagzeuge", ""),

    # ---------- Weather & nature (extended) ----------
    ("die Natur", "noun", "die", "自然", "nature", "", "", "", ""),
    ("die Umwelt", "noun", "die", "環境", "environment", "", "", "", ""),
    ("der Klimawandel", "noun", "der", "気候変動", "climate change", "", "", "", ""),
    ("die Luft", "noun", "die", "空気", "air", "", "", "", ""),
    ("die Sonne", "noun", "die", "太陽", "sun", "", "", "die Sonnen", ""),
    ("der Mond", "noun", "der", "月", "moon", "", "", "die Monde", ""),
    ("der Stern", "noun", "der", "星", "star", "", "", "die Sterne", ""),
    ("der Himmel", "noun", "der", "空／天", "sky, heaven", "", "", "die Himmel", ""),
    ("die Wolke", "noun", "die", "雲", "cloud", "", "", "die Wolken", ""),
    ("der Nebel", "noun", "der", "霧", "fog", "", "", "die Nebel", ""),
    ("der Sturm", "noun", "der", "嵐", "storm", "", "", "die Stürme", ""),
    ("das Gewitter", "noun", "das", "雷雨", "thunderstorm", "", "", "die Gewitter", ""),
    ("der Donner", "noun", "der", "雷", "thunder", "", "", "", ""),
    ("der Blitz", "noun", "der", "稲妻", "lightning", "", "", "die Blitze", ""),
    ("das Eis", "noun", "das", "氷", "ice", "", "", "", ""),
    ("der Frost", "noun", "der", "霜", "frost", "", "", "die Fröste", ""),
    ("die Hitze", "noun", "die", "暑さ", "heat", "", "", "", ""),
    ("die Kälte", "noun", "die", "寒さ", "cold", "", "", "", ""),
    ("der Berg", "noun", "der", "山", "mountain", "", "", "die Berge", ""),
    ("das Tal", "noun", "das", "谷", "valley", "", "", "die Täler", ""),
    ("der Fluss", "noun", "der", "川", "river", "", "", "die Flüsse", ""),
    ("der See", "noun", "der", "湖", "lake", "", "", "die Seen", ""),
    ("das Meer", "noun", "das", "海", "sea", "", "", "die Meere", ""),
    ("der Ozean", "noun", "der", "海洋", "ocean", "", "", "die Ozeane", ""),
    ("die Insel", "noun", "die", "島", "island", "", "", "die Inseln", ""),
    ("der Strand", "noun", "der", "浜辺", "beach", "", "", "die Strände", ""),
    ("der Wald", "noun", "der", "森", "forest", "", "", "die Wälder", ""),
    ("der Baum", "noun", "der", "木", "tree", "", "", "die Bäume", ""),
    ("die Blume", "noun", "die", "花", "flower", "", "", "die Blumen", ""),
    ("die Pflanze", "noun", "die", "植物", "plant", "", "", "die Pflanzen", ""),
    ("das Tier", "noun", "das", "動物", "animal", "", "", "die Tiere", ""),
    ("der Hund", "noun", "der", "犬", "dog", "", "", "die Hunde", ""),
    ("die Katze", "noun", "die", "猫", "cat", "", "", "die Katzen", ""),
    ("das Pferd", "noun", "das", "馬", "horse", "", "", "die Pferde", ""),
    ("die Kuh", "noun", "die", "牛", "cow", "", "", "die Kühe", ""),
    ("der Vogel", "noun", "der", "鳥", "bird", "", "", "die Vögel", ""),
    ("der Bär", "noun", "der", "クマ", "bear", "", "", "die Bären", "n-decl"),

    # ---------- Adjectives & qualities (extended) ----------
    ("herrlich", "adj", "", "素晴らしい", "wonderful", "", "", "", ""),
    ("wunderbar", "adj", "", "素敵な", "wonderful", "", "", "", ""),
    ("toll", "adj", "", "すごい", "great", "", "", "", ""),
    ("super", "adj", "", "最高の", "super", "", "", "", ""),
    ("prima", "adj", "", "最高の", "great", "", "", "", "indeclinable"),
    ("nett", "adj", "", "親切な", "nice", "", "", "", ""),
    ("freundlich", "adj", "", "親しみやすい", "friendly", "", "", "", ""),
    ("höflich", "adj", "", "礼儀正しい", "polite", "", "", "", ""),
    ("unfreundlich", "adj", "", "不親切な", "unfriendly", "", "", "", ""),
    ("ehrlich", "adj", "", "正直な", "honest", "", "", "", ""),
    ("ernst", "adj", "", "真剣な", "serious", "", "", "", ""),
    ("lustig", "adj", "", "面白い", "funny", "", "", "", ""),
    ("ruhig", "adj", "", "静かな", "quiet, calm", "", "", "", ""),
    ("laut", "adj", "", "うるさい", "loud", "", "", "", ""),
    ("leise", "adj", "", "静かな", "quiet", "", "", "", ""),
    ("hell", "adj", "", "明るい", "bright, light", "", "", "", ""),
    ("dunkel", "adj", "", "暗い", "dark", "", "", "", ""),
    ("breit", "adj", "", "幅広い", "wide", "", "", "", ""),
    ("schmal", "adj", "", "細い", "narrow", "", "", "", ""),
    ("rund", "adj", "", "丸い", "round", "", "", "", ""),
    ("eckig", "adj", "", "角ばった", "angular", "", "", "", ""),
    ("flach", "adj", "", "平らな", "flat", "", "", "", ""),
    ("tief", "adj", "", "深い", "deep", "", "", "", ""),
    ("hoch", "adj", "", "高い", "high, tall", "", "", "", ""),
    ("niedrig", "adj", "", "低い", "low", "", "", "", ""),
    ("schwer", "adj", "", "重い／難しい", "heavy, difficult", "", "", "", ""),
    ("leicht", "adj", "", "軽い／簡単な", "light, easy", "", "", "", ""),
    ("hart", "adj", "", "硬い", "hard", "", "", "", ""),
    ("weich", "adj", "", "柔らかい", "soft", "", "", "", ""),
    ("trocken", "adj", "", "乾いた", "dry", "", "", "", ""),
    ("nass", "adj", "", "濡れた", "wet", "", "", "", ""),
    ("feucht", "adj", "", "湿った", "humid", "", "", "", ""),
    ("sauber", "adj", "", "清潔な", "clean", "", "", "", ""),
    ("schmutzig", "adj", "", "汚れた", "dirty", "", "", "", ""),
    ("frei", "adj", "", "自由な／空いている", "free", "", "", "", ""),
    ("besetzt", "adj", "", "占有された", "occupied", "", "", "", ""),
    ("voll", "adj", "", "いっぱいの", "full", "", "", "", ""),
    ("leer", "adj", "", "空の", "empty", "", "", "", ""),
    ("genug", "adj/adv", "", "十分な", "enough", "", "", "", ""),
    ("wenig", "adj", "", "少ない", "few, little", "", "", "", ""),
    ("viel", "adj", "", "多い", "much, many", "", "", "", ""),
    ("ähnlich", "adj", "", "似ている", "similar", "", "", "", ""),
    ("verschieden", "adj", "", "異なる", "different", "", "", "", ""),
    ("gleich", "adj", "", "同じ", "same", "", "", "", ""),
    ("möglich", "adj", "", "可能な", "possible", "", "", "", ""),
    ("unmöglich", "adj", "", "不可能な", "impossible", "", "", "", ""),
    ("notwendig", "adj", "", "必要な", "necessary", "", "", "", ""),
    ("wichtig", "adj", "", "重要な", "important", "", "", "", ""),
    ("unwichtig", "adj", "", "重要でない", "unimportant", "", "", "", ""),
    ("sicher", "adj", "", "確実な／安全な", "sure, safe", "", "", "", ""),
    ("unsicher", "adj", "", "不確かな", "unsure", "", "", "", ""),
    ("gefährlich", "adj", "", "危険な", "dangerous", "", "", "", ""),
    ("vorsichtig", "adj", "", "用心深い", "careful", "", "", "", ""),
    ("genau", "adj/adv", "", "正確な", "exact", "", "", "", ""),
    ("ungefähr", "adv", "", "おおよそ", "approximately", "", "", "", ""),
    ("ungefähr", "adj", "", "おおよそ", "approximate", "", "", "", ""),
    ("typisch", "adj", "", "典型的な", "typical", "", "", "", ""),
    ("normal", "adj", "", "普通の", "normal", "", "", "", ""),
    ("modern", "adj", "", "現代的な", "modern", "", "", "", ""),
    ("traditionell", "adj", "", "伝統的な", "traditional", "", "", "", ""),
    ("praktisch", "adj", "", "実用的な", "practical", "", "", "", ""),
    ("nützlich", "adj", "", "役に立つ", "useful", "", "", "", ""),
    ("nutzlos", "adj", "", "無用な", "useless", "", "", "", ""),
    ("preiswert", "adj", "", "お買い得な", "good value", "", "", "", ""),
    ("günstig", "adj", "", "好都合な／安い", "favorable, cheap", "", "", "", ""),
    ("zufrieden", "adj", "", "満足した", "satisfied", "", "", "", ""),
    ("unzufrieden", "adj", "", "不満な", "dissatisfied", "", "", "", ""),
    ("stolz", "adj", "", "誇りに思う", "proud", "", "", "", ""),
    ("nervös", "adj", "", "緊張した", "nervous", "", "", "", ""),
    ("aufgeregt", "adj", "", "興奮した", "excited", "", "", "", ""),
    ("entspannt", "adj", "", "リラックスした", "relaxed", "", "", "", ""),
    ("ängstlich", "adj", "", "不安な", "anxious", "", "", "", ""),
    ("mutig", "adj", "", "勇敢な", "brave", "", "", "", ""),
    ("ruhig", "adj", "", "落ち着いた", "calm", "", "", "", ""),
    ("egal", "adj", "", "どうでもよい", "indifferent", "", "", "", ""),
    ("sympathisch", "adj", "", "感じのよい", "likable", "", "", "", ""),
    ("unsympathisch", "adj", "", "感じの悪い", "unlikable", "", "", "", ""),

    # ---------- Adverbs & connectors (extended) ----------
    ("erst", "adv", "", "やっと", "only, not until", "", "", "", ""),
    ("schon", "adv", "", "もう", "already", "", "", "", ""),
    ("noch", "adv", "", "まだ", "still, yet", "", "", "", ""),
    ("immer", "adv", "", "いつも", "always", "", "", "", ""),
    ("nie", "adv", "", "決してない", "never", "", "", "", ""),
    ("oft", "adv", "", "しばしば", "often", "", "", "", ""),
    ("manchmal", "adv", "", "ときどき", "sometimes", "", "", "", ""),
    ("selten", "adv", "", "まれに", "rarely", "", "", "", ""),
    ("meistens", "adv", "", "たいてい", "mostly", "", "", "", ""),
    ("normalerweise", "adv", "", "通常は", "normally", "", "", "", ""),
    ("gewöhnlich", "adv", "", "普通", "usually", "", "", "", ""),
    ("plötzlich", "adv", "", "突然", "suddenly", "", "", "", ""),
    ("sofort", "adv", "", "すぐに", "immediately", "", "", "", ""),
    ("gleich", "adv", "", "すぐに／同じく", "right away, equally", "", "", "", ""),
    ("zuerst", "adv", "", "まず", "first of all", "", "", "", ""),
    ("danach", "adv", "", "その後", "afterwards", "", "", "", ""),
    ("dann", "adv", "", "それから", "then", "", "", "", ""),
    ("zuletzt", "adv", "", "最後に", "finally", "", "", "", ""),
    ("schließlich", "adv", "", "結局", "finally, after all", "", "", "", ""),
    ("vorher", "adv", "", "以前に", "previously", "", "", "", ""),
    ("nachher", "adv", "", "後で", "afterwards", "", "", "", ""),
    ("inzwischen", "adv", "", "そのうちに", "meanwhile", "", "", "", ""),
    ("damals", "adv", "", "当時", "back then", "", "", "", ""),
    ("neulich", "adv", "", "最近", "recently", "", "", "", ""),
    ("kürzlich", "adv", "", "つい先日", "recently", "", "", "", ""),
    ("bald", "adv", "", "もうすぐ", "soon", "", "", "", ""),
    ("später", "adv", "", "後で", "later", "", "", "", ""),
    ("hier", "adv", "", "ここに", "here", "", "", "", ""),
    ("dort", "adv", "", "そこに", "there", "", "", "", ""),
    ("da", "adv", "", "そこに", "there", "", "", "", ""),
    ("überall", "adv", "", "いたるところに", "everywhere", "", "", "", ""),
    ("nirgendwo", "adv", "", "どこにも～ない", "nowhere", "", "", "", ""),
    ("irgendwo", "adv", "", "どこかに", "somewhere", "", "", "", ""),
    ("oben", "adv", "", "上に", "above", "", "", "", ""),
    ("unten", "adv", "", "下に", "below", "", "", "", ""),
    ("vorn", "adv", "", "前に", "in front", "", "", "", ""),
    ("hinten", "adv", "", "後ろに", "in the back", "", "", "", ""),
    ("links", "adv", "", "左に", "left", "", "", "", ""),
    ("rechts", "adv", "", "右に", "right", "", "", "", ""),
    ("geradeaus", "adv", "", "まっすぐ", "straight ahead", "", "", "", ""),
    ("draußen", "adv", "", "外に", "outside", "", "", "", ""),
    ("drinnen", "adv", "", "中に", "inside", "", "", "", ""),
    ("zusammen", "adv", "", "一緒に", "together", "", "", "", ""),
    ("getrennt", "adv", "", "別々に", "separately", "", "", "", ""),
    ("besonders", "adv", "", "特に", "especially", "", "", "", ""),
    ("vor allem", "adv", "", "とりわけ", "above all", "", "", "", ""),
    ("zum Beispiel", "adv", "", "例えば", "for example", "", "", "", ""),
    ("trotzdem", "adv", "", "それでも", "nevertheless", "", "", "", ""),
    ("deshalb", "adv", "", "それゆえ", "therefore", "", "", "", ""),
    ("deswegen", "adv", "", "それゆえ", "for that reason", "", "", "", ""),
    ("daher", "adv", "", "それゆえ", "hence", "", "", "", ""),
    ("vielleicht", "adv", "", "おそらく", "perhaps", "", "", "", ""),
    ("hoffentlich", "adv", "", "願わくは", "hopefully", "", "", "", ""),
    ("leider", "adv", "", "残念ながら", "unfortunately", "", "", "", ""),
    ("zum Glück", "adv", "", "幸いにも", "luckily", "", "", "", ""),
    ("natürlich", "adv", "", "もちろん", "of course", "", "", "", ""),
    ("klar", "adv", "", "もちろん", "of course", "", "", "", ""),
    ("wirklich", "adv", "", "本当に", "really", "", "", "", ""),
    ("eigentlich", "adv", "", "実は", "actually", "", "", "", ""),
    ("genauso", "adv", "", "ちょうど同じく", "just as", "", "", "", ""),
    ("ebenso", "adv", "", "同様に", "likewise", "", "", "", ""),
    ("ungefähr", "adv", "", "おおよそ", "approximately", "", "", "", ""),
    ("fast", "adv", "", "ほとんど", "almost", "", "", "", ""),
    ("kaum", "adv", "", "ほとんど～ない", "hardly", "", "", "", ""),
    ("ziemlich", "adv", "", "かなり", "rather", "", "", "", ""),
    ("ganz", "adv", "", "全く", "entirely", "", "", "", ""),
    ("völlig", "adv", "", "完全に", "completely", "", "", "", ""),

    # ---------- Conjunctions & subjunctors (extended) ----------
    ("dass", "conj", "", "～ということ", "that", "", "", "", "subordinating"),
    ("ob", "conj", "", "～かどうか", "whether", "", "", "", "subordinating"),
    ("weil", "conj", "", "なぜなら", "because", "", "", "", "subordinating"),
    ("da", "conj", "", "～なので", "since", "", "", "", "subordinating"),
    ("wenn", "conj", "", "もし", "if, when", "", "", "", "subordinating"),
    ("falls", "conj", "", "～の場合", "in case", "", "", "", "subordinating"),
    ("obwohl", "conj", "", "～にもかかわらず", "although", "", "", "", "subordinating"),
    ("während", "conj", "", "～する間", "while", "", "", "", "subordinating"),
    ("bis", "conj", "", "～まで", "until", "", "", "", "subordinating"),
    ("seit", "conj", "", "～以来", "since", "", "", "", "subordinating"),
    ("seitdem", "conj", "", "～以来", "since (then)", "", "", "", "subordinating"),
    ("nachdem", "conj", "", "～した後で", "after", "", "", "", "subordinating"),
    ("bevor", "conj", "", "～する前に", "before", "", "", "", "subordinating"),
    ("damit", "conj", "", "～するために", "so that", "", "", "", "subordinating"),
    ("sodass", "conj", "", "～するように", "so that", "", "", "", "subordinating"),
    ("solange", "conj", "", "～する限り", "as long as", "", "", "", "subordinating"),
    ("sobald", "conj", "", "～するとすぐに", "as soon as", "", "", "", "subordinating"),
    ("wobei", "conj", "", "～する際に", "whereby", "", "", "", "subordinating"),
    ("entweder ... oder", "conj", "", "～か～か", "either ... or", "", "", "", ""),
    ("weder ... noch", "conj", "", "～も～もない", "neither ... nor", "", "", "", ""),
    ("sowohl ... als auch", "conj", "", "～も～も", "both ... and", "", "", "", ""),

    # ---------- Prepositions (extended) ----------
    ("gegen", "prep", "", "～に対して", "against", "", "", "", "+Akk"),
    ("durch", "prep", "", "～を通って", "through", "", "", "", "+Akk"),
    ("ohne", "prep", "", "～なしで", "without", "", "", "", "+Akk"),
    ("für", "prep", "", "～のために", "for", "", "", "", "+Akk"),
    ("um", "prep", "", "～の周り／時刻", "around, at (time)", "", "", "", "+Akk"),
    ("entlang", "prep", "", "～に沿って", "along", "", "", "", "+Akk (post)"),
    ("seit", "prep", "", "～以来", "since", "", "", "", "+Dat"),
    ("aus", "prep", "", "～から（出身）", "out of, from", "", "", "", "+Dat"),
    ("bei", "prep", "", "～のもとで", "at, near", "", "", "", "+Dat"),
    ("nach", "prep", "", "～後／～へ", "after, to", "", "", "", "+Dat"),
    ("von", "prep", "", "～から", "from", "", "", "", "+Dat"),
    ("zu", "prep", "", "～へ", "to", "", "", "", "+Dat"),
    ("gegenüber", "prep", "", "～の向かいに", "opposite", "", "", "", "+Dat"),
    ("außer", "prep", "", "～を除いて", "except", "", "", "", "+Dat"),
    ("wegen", "prep", "", "～のために", "because of", "", "", "", "+Gen"),
    ("trotz", "prep", "", "～にもかかわらず", "despite", "", "", "", "+Gen"),
    ("statt", "prep", "", "～の代わりに", "instead of", "", "", "", "+Gen"),
    ("anstatt", "prep", "", "～の代わりに", "instead of", "", "", "", "+Gen"),
    ("während", "prep", "", "～の間", "during", "", "", "", "+Gen"),
    ("innerhalb", "prep", "", "～以内に", "within", "", "", "", "+Gen"),
    ("außerhalb", "prep", "", "～の外に", "outside of", "", "", "", "+Gen"),
    ("zwischen", "prep", "", "～の間に", "between", "", "", "", "+Dat/Akk"),
    ("hinter", "prep", "", "～の後ろに", "behind", "", "", "", "+Dat/Akk"),
    ("über", "prep", "", "～の上に", "above, over", "", "", "", "+Dat/Akk"),
    ("unter", "prep", "", "～の下に", "under", "", "", "", "+Dat/Akk"),
    ("neben", "prep", "", "～の隣に", "next to", "", "", "", "+Dat/Akk"),
    ("vor", "prep", "", "～の前に", "before, in front of", "", "", "", "+Dat/Akk"),
]

# ---------- Theme keyword index (shared with add_a1) ----------
THEMES = {
    "Familie": [
        "family", "father", "mother", "son", "daughter", "brother", "sister",
        "child", "wife", "husband", "parent",
        "家族", "父", "母", "息子", "娘", "兄弟", "姉妹", "子供", "妻", "夫",
        "親", "祖父", "祖母", "おじ", "おば", "いとこ", "結婚", "離婚", "妊娠",
        "Familie", "Vater", "Mutter", "Sohn", "Tochter", "Bruder", "Schwester",
        "Kind", "Eltern", "Geschwister", "Opa", "Oma", "Onkel", "Tante",
        "Mann", "Frau", "Cousin", "Cousine", "Verwandte", "Beziehung",
        "Hochzeit", "Ehe", "heiraten", "geschieden", "ledig", "verlobt",
    ],
    "Essen": [
        "food", "eat", "drink", "breakfast", "lunch", "dinner", "bread", "meat",
        "fish", "fruit", "vegetable", "cheese", "milk", "water", "coffee", "tea",
        "beer", "wine", "delicious", "tasty", "spicy", "sweet", "sour",
        "食事", "食べる", "飲む", "朝食", "昼食", "夕食", "パン", "肉", "魚",
        "果物", "野菜", "チーズ", "牛乳", "水", "コーヒー", "紅茶", "ビール",
        "ワイン", "ジュース", "甘い", "辛い", "塩",
        "Essen", "essen", "trinken", "Frühstück", "Mittagessen", "Abendessen",
        "Brot", "Brötchen", "Käse", "Wurst", "Fleisch", "Schinken", "Hähnchen",
        "Schwein", "Rind", "Fisch", "Lachs", "Garnele", "Obst", "Apfel",
        "Banane", "Orange", "Birne", "Traube", "Erdbeere", "Kirsche", "Zitrone",
        "Gemüse", "Tomate", "Karotte", "Möhre", "Gurke", "Salat", "Paprika",
        "Zwiebel", "Knoblauch", "Pilz", "Bohne", "Reis", "Nudel", "Suppe",
        "Pizza", "Pommes", "Kuchen", "Torte", "Eis", "Schokolade", "Honig",
        "Marmelade", "Butter", "Salz", "Zucker", "Pfeffer", "Soße", "Senf",
        "Ei", "Öl", "Essig", "Mehl", "lecker", "süß", "sauer", "salzig",
        "scharf", "bitter", "schmecken", "hungrig", "durstig", "satt",
    ],
    "Arbeit": [
        "work", "job", "office", "boss", "colleague", "employee", "company",
        "career", "salary", "wage", "interview", "application",
        "仕事", "職業", "会社", "上司", "同僚", "従業員", "給与", "面接",
        "履歴書", "応募", "キャリア",
        "Arbeit", "arbeiten", "Beruf", "Büro", "Chef", "Kollege", "Kollegin",
        "Mitarbeiter", "Firma", "Unternehmen", "Stelle", "Bewerbung",
        "Vorstellungsgespräch", "Lebenslauf", "Gehalt", "Lohn", "Karriere",
        "Vertrag", "kündigen", "Kündigung", "arbeitslos", "Praktikum",
        "Termin", "Besprechung", "Sitzung", "Projekt", "Team", "Auftrag",
        "Aufgabe", "Verantwortung", "Erfahrung", "Ausbildung", "Architekt",
        "Anwalt", "Ingenieur", "Lehrer", "Arzt", "Programmierer", "Mechaniker",
    ],
    "Verkehr": [
        "car", "bus", "train", "bike", "taxi", "drive", "street", "station",
        "ticket", "tram", "subway", "platform",
        "車", "バス", "電車", "自転車", "タクシー", "駅", "電車",
        "Auto", "Wagen", "Bus", "Zug", "Bahn", "Fahrrad", "Taxi", "fahren",
        "Bahnhof", "Haltestelle", "Straße", "Flugzeug", "Verkehr", "Fahrkarte",
        "Fahrschein", "Fahrplan", "Strecke", "Gleis", "Bahnsteig",
        "S-Bahn", "U-Bahn", "Straßenbahn", "einsteigen", "aussteigen",
        "umsteigen", "Ankunft", "Abfahrt", "Verspätung",
    ],
    "Reisen": [
        "travel", "trip", "holiday", "vacation", "airport", "flight", "hotel",
        "passport", "ticket", "tourist", "luggage", "guidebook", "border",
        "旅", "旅行", "休暇", "空港", "飛行", "ホテル", "パスポート", "観光",
        "荷物", "ガイドブック",
        "Reise", "reisen", "Urlaub", "Ferien", "Flug", "fliegen", "Flughafen",
        "Hotel", "Pension", "Pass", "Reisepass", "Visum", "Ticket", "Fahrkarte",
        "Koffer", "Gepäck", "Rucksack", "Tasche", "Tourist", "Souvenir",
        "Sehenswürdigkeit", "besichtigen", "Reiseführer", "buchen", "reservieren",
        "Buchung", "Reservierung", "Landkarte", "Stadtplan", "Auskunft",
        "Jugendherberge", "Camping", "Zelt", "zelten", "Grenze",
    ],
    "Wohnen": [
        "house", "apartment", "room", "kitchen", "bathroom", "bedroom",
        "garden", "door", "window", "furniture", "rent", "landlord", "tenant",
        "家", "部屋", "アパート", "キッチン", "風呂", "庭", "ドア", "窓",
        "家具", "家賃", "家主", "賃借",
        "Haus", "Wohnung", "Zimmer", "Küche", "Bad", "Schlafzimmer",
        "Wohnzimmer", "Garten", "Balkon", "Terrasse", "Tisch", "Stuhl",
        "Bett", "Schrank", "Lampe", "Sofa", "Sessel", "Teppich", "Vorhang",
        "Tür", "Fenster", "Wand", "Boden", "Adresse", "Straße", "Treppe",
        "Aufzug", "Keller", "Dachboden", "Heizung", "Klimaanlage", "Strom",
        "Gas", "Müll", "mieten", "vermieten", "Vermieter", "Mieter", "Miete",
        "Nebenkosten", "Möbel", "möbliert", "umziehen", "Umzug", "renovieren",
        "reparieren", "putzen", "Waschmaschine", "Geschirrspüler", "Staubsauger",
    ],
    "Gesundheit": [
        "health", "sick", "doctor", "hospital", "medicine", "pain", "fever",
        "patient", "pharmacy", "operation", "injury", "wound", "allergy",
        "健康", "病気", "医者", "病院", "痛", "薬", "患者", "けが", "傷",
        "アレルギー", "手術",
        "Gesundheit", "gesund", "krank", "Krankheit", "Arzt", "Ärztin",
        "Krankenhaus", "Apotheke", "Medikament", "Tablette", "Spritze",
        "Schmerz", "Fieber", "Husten", "Erkältung", "Schnupfen", "Grippe",
        "Allergie", "Verletzung", "Wunde", "Pflaster", "Operation",
        "Untersuchung", "Praxis", "Sprechstunde", "Patient", "Patientin",
        "Rezept", "untersuchen", "behandeln", "erholen", "Therapie",
        "Notarzt", "Krankenwagen", "Pflege", "Körper", "Kopf", "Hand",
        "Arm", "Bein", "Fuß", "Bauch", "Rücken", "Hals", "Auge", "Mund",
        "Nase", "Ohr", "Herz", "Lunge", "Leber", "Magen", "Blut", "Muskel",
        "Knochen", "Haut", "Haar", "Zahn",
    ],
    "Kleidung": [
        "clothes", "shirt", "trouser", "dress", "shoe", "jacket", "coat",
        "skirt", "hat", "fashion",
        "シャツ", "ズボン", "靴", "ジャケット", "コート", "スカート", "帽子",
        "ファッション",
        "Kleidung", "Hemd", "Bluse", "Pullover", "Jacke", "Mantel", "Hose",
        "Rock", "Schuh", "Socke", "Hut", "Mütze", "Tasche", "Brille",
        "anziehen", "ausziehen", "tragen", "Mode", "Stoff",
    ],
    "Einkaufen": [
        "shop", "buy", "sell", "pay", "money", "price", "cheap", "expensive",
        "bank", "account", "credit", "tax", "rent",
        "店", "買う", "売る", "値段", "安い", "高い", "銀行", "口座", "税金",
        "einkaufen", "kaufen", "verkaufen", "Preis", "kosten", "billig",
        "teuer", "Euro", "Geld", "bezahlen", "Verkäufer", "Bank", "Konto",
        "Kreditkarte", "Münze", "Schein", "Rechnung", "Quittung", "Beleg",
        "Summe", "Betrag", "überweisen", "abheben", "einzahlen", "sparen",
        "ausgeben", "Steuer", "Versicherung", "Markt", "Wochenmarkt",
        "Sonderangebot", "Rabatt", "kostenlos", "günstig", "preiswert",
        "umtauschen", "zurückgeben", "Schaufenster",
    ],
    "Zeit": [
        "hour", "minute", "day", "week", "month", "year", "morning", "evening",
        "night", "today", "tomorrow", "yesterday", "season",
        "時間", "分", "週", "月", "年", "朝", "夕方", "夜", "今日", "明日",
        "昨日", "季節",
        "Zeit", "Stunde", "Minute", "Tag", "Woche", "Monat", "Jahr", "heute",
        "morgen", "gestern", "jetzt", "früh", "spät", "Uhr", "Termin",
        "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag",
        "Sonntag", "Januar", "Februar", "März", "April", "Mai", "Juni", "Juli",
        "August", "September", "Oktober", "November", "Dezember",
        "Frühling", "Sommer", "Herbst", "Winter",
    ],
    "Wetter": [
        "weather", "rain", "snow", "sun", "wind", "cold", "hot", "warm",
        "storm", "fog", "thunderstorm",
        "天気", "雨", "雪", "太陽", "寒い", "暑い", "暖かい", "嵐", "霧",
        "Wetter", "Regen", "Schnee", "Sonne", "Wind", "Wolke", "kalt", "warm",
        "heiß", "kühl", "sonnig", "Sturm", "Nebel", "Gewitter", "Donner",
        "Blitz", "Eis", "Frost", "Hitze", "Kälte",
    ],
    "Schule": [
        "school", "teacher", "student", "class", "lesson", "learn", "study",
        "homework", "exam", "university", "education", "degree", "scholar",
        "学校", "先生", "学生", "授業", "勉強", "宿題", "試験", "大学", "教育",
        "Schule", "Schüler", "Schülerin", "Lehrer", "Lehrerin", "Klasse",
        "Unterricht", "lernen", "studieren", "Universität", "Hausaufgabe",
        "Prüfung", "Test", "Buch", "Heft", "Stift", "Tafel", "Fach", "Note",
        "Bildung", "Grundschule", "Gymnasium", "Realschule", "Hochschule",
        "Student", "Studentin", "Professor", "Vorlesung", "Seminar", "Semester",
        "Klausur", "Abschluss", "Diplom", "Stipendium", "Wissen", "Kenntnis",
        "Sprache", "Muttersprache", "Fremdsprache", "Übung", "Aufsatz",
    ],
    "Freizeit": [
        "sport", "game", "play", "music", "film", "movie", "book", "read",
        "hobby", "party", "dance", "concert", "theatre", "exhibition",
        "スポーツ", "ゲーム", "音楽", "映画", "本", "趣味", "コンサート",
        "Sport", "Spiel", "spielen", "Musik", "Film", "Kino", "Theater",
        "Museum", "Park", "Fußball", "Ball", "tanzen", "singen", "Hobby",
        "Freizeit", "Spaß", "Vergnügen", "joggen", "schwimmen", "radfahren",
        "Fitness", "Fitnessstudio", "Mannschaft", "Verein", "Spieler",
        "Trainer", "Turnier", "Wettkampf", "Tor", "Sieg", "Niederlage",
        "Medaille", "Konzert", "Oper", "Stück", "Vorstellung", "Galerie",
        "Bibliothek", "Zeitung", "Zeitschrift", "Roman", "Gedicht", "Lied",
        "Band", "Instrument", "Gitarre", "Klavier", "Schlagzeug",
    ],
    "Gefühle": [
        "happy", "sad", "angry", "love", "feel", "feeling", "proud", "nervous",
        "excited", "relaxed", "anxious", "brave",
        "嬉", "悲", "怒", "愛", "誇", "緊張", "リラックス",
        "Liebe", "lieben", "glücklich", "traurig", "Spaß", "freuen", "müde",
        "interessant", "langweilig", "stolz", "nervös", "aufgeregt",
        "entspannt", "ängstlich", "mutig", "sympathisch",
    ],
    "Farben": [
        "color", "colour", "red", "blue", "green", "yellow", "black", "white",
        "brown", "pink", "orange", "grey", "gray",
        "色", "赤", "青", "緑", "黄色", "黒", "白",
        "Farbe", "rot", "blau", "grün", "gelb", "schwarz", "weiß", "braun",
        "grau", "rosa", "lila",
    ],
}

_ASCII_WORD = re.compile(r"^[a-zA-Z]+$")


def has_keyword(haystack: str, keyword: str) -> bool:
    if _ASCII_WORD.fullmatch(keyword):
        return bool(re.search(rf"\b{re.escape(keyword)}\b", haystack, re.IGNORECASE))
    return keyword in haystack


def compute_tags(german: str, pos: str, ja: str, en: str, level: str) -> list[str]:
    haystack = " ".join(filter(None, [german, ja, en]))
    tags: list[str] = []
    for theme, kws in THEMES.items():
        for kw in kws:
            if has_keyword(haystack, kw):
                tags.append(theme)
                break
    if pos:
        tags.append(pos.strip().lower())
    if level:
        tags.append(level)
    seen: set[str] = set()
    out = []
    for t in tags:
        if t not in seen:
            seen.add(t)
            out.append(t)
    return out


def main():
    wb = load_workbook(MASTER)
    ws = wb[SHEET]
    header = [c.value for c in ws[1]]
    if "Tags" not in header:
        raise RuntimeError("Tags column missing — run add_tags_to_session_new.py first")

    existing_terms: set[str] = set()
    for row in ws.iter_rows(min_row=2, values_only=True):
        g = row[0]
        if g and str(g).strip():
            existing_terms.add(str(g).strip().lower())

    start_row = ws.max_row + 1
    added = 0
    skipped = 0
    for g, pos, art, ja, en, prat, pii, plural, notes in A2_ENTRIES:
        if g.strip().lower() in existing_terms:
            skipped += 1
            continue
        tags = compute_tags(g, pos, ja, en, LEVEL)
        row_data = [g, pos, art, ja, en, 1, prat, pii, plural, notes, ", ".join(tags)]
        for col_idx, value in enumerate(row_data, start=1):
            ws.cell(row=start_row + added, column=col_idx, value=value)
        added += 1
        existing_terms.add(g.strip().lower())

    wb.save(MASTER)
    print(f"Added {added} A2 entries. Skipped {skipped} (already present). Total rows now: {ws.max_row}.")


if __name__ == "__main__":
    main()
