"""Append B2 vocabulary to german_vocab_session_new.xlsx (the master file).

B2 vocabulary is curated against Goethe Zertifikat B2 / telc B2 word lists.
Focus: abstract concepts, society & economy, science & technology, media,
psychology, common academic verbs, advanced connectors.

Each row carries:
  German term | POS | Article | Japanese | English | Appearance_Count |
  Präteritum  | Partizip II | Plural | Notes | Tags
"""

from __future__ import annotations
import re
import sys
from pathlib import Path

from openpyxl import load_workbook

sys.stdout.reconfigure(encoding="utf-8")

MASTER = Path(__file__).resolve().parent / "german_vocab_master.xlsx"
SHEET = "Session Vokabeln"
LEVEL = "B2"

B2_ENTRIES: list[tuple[str, str, str, str, str, str, str, str, str]] = [
    # ---------- Abstract concepts ----------
    ("die Vorstellung", "noun", "die", "想像／提示", "imagination, idea", "", "", "die Vorstellungen", ""),
    ("die Wahrnehmung", "noun", "die", "知覚", "perception", "", "", "die Wahrnehmungen", ""),
    ("die Erkenntnis", "noun", "die", "認識", "insight", "", "", "die Erkenntnisse", ""),
    ("die Annahme", "noun", "die", "仮定", "assumption", "", "", "die Annahmen", ""),
    ("die Vermutung", "noun", "die", "推測", "supposition", "", "", "die Vermutungen", ""),
    ("die Überzeugung", "noun", "die", "確信", "conviction", "", "", "die Überzeugungen", ""),
    ("der Zweifel", "noun", "der", "疑い", "doubt", "", "", "die Zweifel", ""),
    ("die Theorie", "noun", "die", "理論", "theory", "", "", "die Theorien", ""),
    ("die These", "noun", "die", "テーゼ", "thesis", "", "", "die Thesen", ""),
    ("das Konzept", "noun", "das", "コンセプト", "concept", "", "", "die Konzepte", ""),
    ("der Begriff", "noun", "der", "概念", "term, concept", "", "", "die Begriffe", ""),
    ("die Definition", "noun", "die", "定義", "definition", "", "", "die Definitionen", ""),
    ("der Sinn", "noun", "der", "意味／感覚", "meaning, sense", "", "", "die Sinne", ""),
    ("der Zweck", "noun", "der", "目的", "purpose", "", "", "die Zwecke", ""),
    ("das Ziel", "noun", "das", "目標", "goal", "", "", "die Ziele", ""),
    ("die Absicht", "noun", "die", "意図", "intention", "", "", "die Absichten", ""),
    ("der Grund", "noun", "der", "理由", "reason", "", "", "die Gründe", ""),
    ("die Ursache", "noun", "die", "原因", "cause", "", "", "die Ursachen", ""),
    ("die Wirkung", "noun", "die", "影響", "effect", "", "", "die Wirkungen", ""),
    ("die Folge", "noun", "die", "結果", "consequence", "", "", "die Folgen", ""),
    ("die Konsequenz", "noun", "die", "結末", "consequence", "", "", "die Konsequenzen", ""),
    ("die Auswirkung", "noun", "die", "影響", "effect, impact", "", "", "die Auswirkungen", ""),
    ("der Einfluss", "noun", "der", "影響力", "influence", "", "", "die Einflüsse", ""),
    ("der Aspekt", "noun", "der", "観点", "aspect", "", "", "die Aspekte", ""),
    ("die Perspektive", "noun", "die", "視点", "perspective", "", "", "die Perspektiven", ""),
    ("der Standpunkt", "noun", "der", "立場", "viewpoint", "", "", "die Standpunkte", ""),
    ("die Sichtweise", "noun", "die", "見方", "viewpoint", "", "", "die Sichtweisen", ""),
    ("die Tatsache", "noun", "die", "事実", "fact", "", "", "die Tatsachen", ""),
    ("die Wirklichkeit", "noun", "die", "現実", "reality", "", "", "die Wirklichkeiten", ""),
    ("die Realität", "noun", "die", "現実", "reality", "", "", "die Realitäten", ""),
    ("die Wahrheit", "noun", "die", "真実", "truth", "", "", "die Wahrheiten", ""),
    ("die Lüge", "noun", "die", "嘘", "lie", "", "", "die Lügen", ""),
    ("der Beweis", "noun", "der", "証拠", "proof", "", "", "die Beweise", ""),
    ("das Beispiel", "noun", "das", "例", "example", "", "", "die Beispiele", ""),
    ("der Vergleich", "noun", "der", "比較", "comparison", "", "", "die Vergleiche", ""),
    ("der Unterschied", "noun", "der", "違い", "difference", "", "", "die Unterschiede", ""),
    ("die Ähnlichkeit", "noun", "die", "類似", "similarity", "", "", "die Ähnlichkeiten", ""),
    ("die Beziehung", "noun", "die", "関係", "relationship", "", "", "die Beziehungen", ""),
    ("der Zusammenhang", "noun", "der", "関連", "context, connection", "", "", "die Zusammenhänge", ""),
    ("die Bedeutung", "noun", "die", "意味／重要性", "meaning, importance", "", "", "die Bedeutungen", ""),
    ("der Hintergrund", "noun", "der", "背景", "background", "", "", "die Hintergründe", ""),
    ("die Voraussetzung", "noun", "die", "前提", "prerequisite", "", "", "die Voraussetzungen", ""),
    ("die Bedingung", "noun", "die", "条件", "condition", "", "", "die Bedingungen", ""),

    # ---------- Society & politics (advanced) ----------
    ("die Gesellschaft", "noun", "die", "社会", "society", "", "", "die Gesellschaften", ""),
    ("der Bürger", "noun", "der", "市民", "citizen", "", "", "die Bürger", ""),
    ("die Bürgerin", "noun", "die", "市民（女）", "citizen (f)", "", "", "die Bürgerinnen", ""),
    ("die Staatsbürgerschaft", "noun", "die", "国籍", "citizenship", "", "", "die Staatsbürgerschaften", ""),
    ("die Integration", "noun", "die", "統合", "integration", "", "", "die Integrationen", ""),
    ("integrieren", "verb", "", "統合する", "to integrate", "integrierte", "hat integriert", "", ""),
    ("die Diskriminierung", "noun", "die", "差別", "discrimination", "", "", "die Diskriminierungen", ""),
    ("diskriminieren", "verb", "", "差別する", "to discriminate", "diskriminierte", "hat diskriminiert", "", ""),
    ("die Gleichberechtigung", "noun", "die", "平等", "equal rights", "", "", "", ""),
    ("die Gleichstellung", "noun", "die", "対等な立場", "equality", "", "", "", ""),
    ("die Minderheit", "noun", "die", "少数派", "minority", "", "", "die Minderheiten", ""),
    ("die Mehrheit", "noun", "die", "多数派", "majority", "", "", "die Mehrheiten", ""),
    ("der Konflikt", "noun", "der", "対立", "conflict", "", "", "die Konflikte", ""),
    ("der Krieg", "noun", "der", "戦争", "war", "", "", "die Kriege", ""),
    ("der Frieden", "noun", "der", "平和", "peace", "", "", "", ""),
    ("die Gewalt", "noun", "die", "暴力", "violence", "", "", "die Gewalten", ""),
    ("die Sicherheit", "noun", "die", "安全", "security", "", "", "die Sicherheiten", ""),
    ("das Recht", "noun", "das", "権利／法律", "right, law", "", "", "die Rechte", ""),
    ("die Pflicht", "noun", "die", "義務", "duty", "", "", "die Pflichten", ""),
    ("die Freiheit", "noun", "die", "自由", "freedom", "", "", "die Freiheiten", ""),
    ("die Meinungsfreiheit", "noun", "die", "言論の自由", "freedom of speech", "", "", "", ""),
    ("die Pressefreiheit", "noun", "die", "報道の自由", "press freedom", "", "", "", ""),
    ("die Verfassung", "noun", "die", "憲法", "constitution", "", "", "die Verfassungen", ""),
    ("das Grundgesetz", "noun", "das", "基本法", "basic law", "", "", "die Grundgesetze", ""),
    ("die Behörde", "noun", "die", "官庁", "authority", "", "", "die Behörden", ""),
    ("das Amt", "noun", "das", "役所", "office", "", "", "die Ämter", ""),
    ("die Verwaltung", "noun", "die", "行政", "administration", "", "", "die Verwaltungen", ""),
    ("die Bürokratie", "noun", "die", "官僚主義", "bureaucracy", "", "", "die Bürokratien", ""),
    ("der Antrag", "noun", "der", "申請", "application", "", "", "die Anträge", ""),
    ("beantragen", "verb", "", "申請する", "to apply for", "beantragte", "hat beantragt", "", ""),
    ("die Genehmigung", "noun", "die", "許可", "approval", "", "", "die Genehmigungen", ""),
    ("genehmigen", "verb", "", "許可する", "to approve", "genehmigte", "hat genehmigt", "", ""),
    ("verbieten", "verb", "", "禁止する", "to forbid", "verbot", "hat verboten", "", "irregular"),
    ("das Verbot", "noun", "das", "禁止", "prohibition", "", "", "die Verbote", ""),
    ("die Strafe", "noun", "die", "罰", "punishment", "", "", "die Strafen", ""),
    ("bestrafen", "verb", "", "罰する", "to punish", "bestrafte", "hat bestraft", "", ""),
    ("der Verbrecher", "noun", "der", "犯罪者", "criminal", "", "", "die Verbrecher", ""),
    ("das Verbrechen", "noun", "das", "犯罪", "crime", "", "", "die Verbrechen", ""),
    ("der Diebstahl", "noun", "der", "窃盗", "theft", "", "", "die Diebstähle", ""),
    ("der Betrug", "noun", "der", "詐欺", "fraud", "", "", "die Betrügereien", ""),
    ("der Mord", "noun", "der", "殺人", "murder", "", "", "die Morde", ""),
    ("das Gericht", "noun", "das", "裁判所", "court", "", "", "die Gerichte", ""),
    ("der Richter", "noun", "der", "裁判官", "judge", "", "", "die Richter", ""),
    ("das Urteil", "noun", "das", "判決", "verdict", "", "", "die Urteile", ""),
    ("die Justiz", "noun", "die", "司法", "judiciary", "", "", "", ""),
    ("die Polizei", "noun", "die", "警察", "police", "", "", "", ""),

    # ---------- Economy & business ----------
    ("die Wirtschaft", "noun", "die", "経済", "economy", "", "", "die Wirtschaften", ""),
    ("der Markt", "noun", "der", "市場", "market", "", "", "die Märkte", ""),
    ("der Handel", "noun", "der", "貿易", "trade", "", "", "", ""),
    ("handeln", "verb", "", "取引する／行動する", "to trade, to act", "handelte", "hat gehandelt", "", ""),
    ("die Wirtschaftslage", "noun", "die", "経済状況", "economic situation", "", "", "die Wirtschaftslagen", ""),
    ("die Krise", "noun", "die", "危機", "crisis", "", "", "die Krisen", ""),
    ("das Wachstum", "noun", "das", "成長", "growth", "", "", "", ""),
    ("wachsen", "verb", "", "成長する", "to grow", "wuchs", "ist gewachsen", "", "irregular"),
    ("die Entwicklung", "noun", "die", "発展", "development", "", "", "die Entwicklungen", ""),
    ("der Fortschritt", "noun", "der", "進歩", "progress", "", "", "die Fortschritte", ""),
    ("der Rückgang", "noun", "der", "減少", "decline", "", "", "die Rückgänge", ""),
    ("die Inflation", "noun", "die", "インフレ", "inflation", "", "", "die Inflationen", ""),
    ("der Aktienmarkt", "noun", "der", "株式市場", "stock market", "", "", "die Aktienmärkte", ""),
    ("die Aktie", "noun", "die", "株", "share", "", "", "die Aktien", ""),
    ("der Aktionär", "noun", "der", "株主", "shareholder", "", "", "die Aktionäre", ""),
    ("die Investition", "noun", "die", "投資", "investment", "", "", "die Investitionen", ""),
    ("investieren", "verb", "", "投資する", "to invest", "investierte", "hat investiert", "", ""),
    ("der Gewinn", "noun", "der", "利益", "profit", "", "", "die Gewinne", ""),
    ("der Verlust", "noun", "der", "損失", "loss", "", "", "die Verluste", ""),
    ("der Umsatz", "noun", "der", "売上", "turnover", "", "", "die Umsätze", ""),
    ("die Konkurrenz", "noun", "die", "競合", "competition", "", "", "die Konkurrenzen", ""),
    ("der Wettbewerb", "noun", "der", "競争", "competition", "", "", "die Wettbewerbe", ""),
    ("die Globalisierung", "noun", "die", "グローバル化", "globalization", "", "", "", ""),
    ("der Export", "noun", "der", "輸出", "export", "", "", "die Exporte", ""),
    ("der Import", "noun", "der", "輸入", "import", "", "", "die Importe", ""),
    ("exportieren", "verb", "", "輸出する", "to export", "exportierte", "hat exportiert", "", ""),
    ("importieren", "verb", "", "輸入する", "to import", "importierte", "hat importiert", "", ""),
    ("die Produktion", "noun", "die", "生産", "production", "", "", "die Produktionen", ""),
    ("produzieren", "verb", "", "生産する", "to produce", "produzierte", "hat produziert", "", ""),
    ("herstellen", "verb", "", "製造する", "to manufacture", "stellte her", "hat hergestellt", "", ""),
    ("der Hersteller", "noun", "der", "メーカー", "manufacturer", "", "", "die Hersteller", ""),
    ("die Industrie", "noun", "die", "産業", "industry", "", "", "die Industrien", ""),
    ("die Branche", "noun", "die", "業界", "sector", "", "", "die Branchen", ""),
    ("der Sektor", "noun", "der", "セクター", "sector", "", "", "die Sektoren", ""),
    ("die Lieferung", "noun", "die", "配送", "delivery", "", "", "die Lieferungen", ""),
    ("liefern", "verb", "", "配送する", "to deliver", "lieferte", "hat geliefert", "", ""),
    ("der Lieferant", "noun", "der", "供給業者", "supplier", "", "", "die Lieferanten", "n-decl"),
    ("der Kunde", "noun", "der", "顧客", "customer", "", "", "die Kunden", "n-decl"),
    ("die Marktforschung", "noun", "die", "市場調査", "market research", "", "", "", ""),
    ("die Werbung", "noun", "die", "広告", "advertisement", "", "", "die Werbungen", ""),
    ("werben", "verb", "", "宣伝する", "to advertise", "warb", "hat geworben", "", "irregular"),
    ("die Marke", "noun", "die", "ブランド", "brand", "", "", "die Marken", ""),
    ("das Marketing", "noun", "das", "マーケティング", "marketing", "", "", "", ""),
    ("die Strategie", "noun", "die", "戦略", "strategy", "", "", "die Strategien", ""),
    ("die Effizienz", "noun", "die", "効率", "efficiency", "", "", "", ""),
    ("effizient", "adj", "", "効率的な", "efficient", "", "", "", ""),
    ("die Produktivität", "noun", "die", "生産性", "productivity", "", "", "", ""),
    ("produktiv", "adj", "", "生産的な", "productive", "", "", "", ""),
    ("die Qualität", "noun", "die", "品質", "quality", "", "", "die Qualitäten", ""),
    ("die Quantität", "noun", "die", "数量", "quantity", "", "", "die Quantitäten", ""),
    ("die Innovation", "noun", "die", "革新", "innovation", "", "", "die Innovationen", ""),
    ("innovativ", "adj", "", "革新的な", "innovative", "", "", "", ""),
    ("die Selbstständigkeit", "noun", "die", "自営業", "self-employment", "", "", "", ""),
    ("selbstständig", "adj", "", "自営の", "self-employed", "", "", "", ""),
    ("der Unternehmer", "noun", "der", "経営者", "entrepreneur", "", "", "die Unternehmer", ""),
    ("die Unternehmerin", "noun", "die", "経営者（女）", "entrepreneur (f)", "", "", "die Unternehmerinnen", ""),

    # ---------- Environment & climate ----------
    ("die Umwelt", "noun", "die", "環境", "environment", "", "", "", ""),
    ("der Umweltschutz", "noun", "der", "環境保護", "environmental protection", "", "", "", ""),
    ("die Verschmutzung", "noun", "die", "汚染", "pollution", "", "", "die Verschmutzungen", ""),
    ("verschmutzen", "verb", "", "汚染する", "to pollute", "verschmutzte", "hat verschmutzt", "", ""),
    ("die Luftverschmutzung", "noun", "die", "大気汚染", "air pollution", "", "", "", ""),
    ("der Klimawandel", "noun", "der", "気候変動", "climate change", "", "", "", ""),
    ("die Erderwärmung", "noun", "die", "地球温暖化", "global warming", "", "", "", ""),
    ("die Treibhausgase", "noun", "die", "温室効果ガス", "greenhouse gases", "", "", "", "plural"),
    ("der CO2-Ausstoß", "noun", "der", "CO2排出量", "CO2 emissions", "", "", "", ""),
    ("die Emission", "noun", "die", "排出", "emission", "", "", "die Emissionen", ""),
    ("die Energie", "noun", "die", "エネルギー", "energy", "", "", "die Energien", ""),
    ("die Solaranlage", "noun", "die", "太陽光発電", "solar panel system", "", "", "die Solaranlagen", ""),
    ("die Windkraft", "noun", "die", "風力", "wind power", "", "", "", ""),
    ("die Wasserkraft", "noun", "die", "水力", "hydropower", "", "", "", ""),
    ("die Atomkraft", "noun", "die", "原子力", "nuclear power", "", "", "", ""),
    ("die Kernenergie", "noun", "die", "原子力エネルギー", "nuclear energy", "", "", "", ""),
    ("erneuerbar", "adj", "", "再生可能な", "renewable", "", "", "", ""),
    ("nachhaltig", "adj", "", "持続可能な", "sustainable", "", "", "", ""),
    ("die Nachhaltigkeit", "noun", "die", "持続可能性", "sustainability", "", "", "", ""),
    ("der Rohstoff", "noun", "der", "原料", "raw material", "", "", "die Rohstoffe", ""),
    ("die Ressource", "noun", "die", "資源", "resource", "", "", "die Ressourcen", ""),
    ("verbrauchen", "verb", "", "消費する", "to consume", "verbrauchte", "hat verbraucht", "", ""),
    ("der Verbrauch", "noun", "der", "消費", "consumption", "", "", "", ""),
    ("der Konsum", "noun", "der", "消費", "consumption", "", "", "", ""),
    ("recyceln", "verb", "", "リサイクルする", "to recycle", "recycelte", "hat recycelt", "", ""),
    ("das Recycling", "noun", "das", "リサイクル", "recycling", "", "", "", ""),
    ("die Mülltrennung", "noun", "die", "ごみ分別", "waste separation", "", "", "", ""),
    ("der Plastikmüll", "noun", "der", "プラスチックごみ", "plastic waste", "", "", "", ""),
    ("schützen", "verb", "", "保護する", "to protect", "schützte", "hat geschützt", "", ""),
    ("der Schutz", "noun", "der", "保護", "protection", "", "", "", ""),
    ("zerstören", "verb", "", "破壊する", "to destroy", "zerstörte", "hat zerstört", "", ""),
    ("die Zerstörung", "noun", "die", "破壊", "destruction", "", "", "die Zerstörungen", ""),
    ("die Katastrophe", "noun", "die", "災害", "catastrophe", "", "", "die Katastrophen", ""),
    ("das Erdbeben", "noun", "das", "地震", "earthquake", "", "", "die Erdbeben", ""),
    ("die Überschwemmung", "noun", "die", "洪水", "flood", "", "", "die Überschwemmungen", ""),
    ("die Dürre", "noun", "die", "干ばつ", "drought", "", "", "die Dürren", ""),
    ("der Waldbrand", "noun", "der", "山火事", "forest fire", "", "", "die Waldbrände", ""),

    # ---------- Science & technology ----------
    ("die Wissenschaft", "noun", "die", "科学", "science", "", "", "die Wissenschaften", ""),
    ("wissenschaftlich", "adj", "", "科学的な", "scientific", "", "", "", ""),
    ("die Forschung", "noun", "die", "研究", "research", "", "", "die Forschungen", ""),
    ("forschen", "verb", "", "研究する", "to research", "forschte", "hat geforscht", "", ""),
    ("der Forscher", "noun", "der", "研究者", "researcher", "", "", "die Forscher", ""),
    ("das Experiment", "noun", "das", "実験", "experiment", "", "", "die Experimente", ""),
    ("experimentieren", "verb", "", "実験する", "to experiment", "experimentierte", "hat experimentiert", "", ""),
    ("das Ergebnis", "noun", "das", "結果", "result", "", "", "die Ergebnisse", ""),
    ("das Resultat", "noun", "das", "結果", "result", "", "", "die Resultate", ""),
    ("die Methode", "noun", "die", "方法", "method", "", "", "die Methoden", ""),
    ("die Studie", "noun", "die", "研究／調査", "study", "", "", "die Studien", ""),
    ("die Untersuchung", "noun", "die", "調査", "investigation", "", "", "die Untersuchungen", ""),
    ("die Statistik", "noun", "die", "統計", "statistics", "", "", "die Statistiken", ""),
    ("die Daten", "noun", "die", "データ", "data", "", "", "", "plural"),
    ("die Information", "noun", "die", "情報", "information", "", "", "die Informationen", ""),
    ("die Technologie", "noun", "die", "技術", "technology", "", "", "die Technologien", ""),
    ("die Technik", "noun", "die", "技術／工学", "technology, technique", "", "", "die Techniken", ""),
    ("technisch", "adj", "", "技術的な", "technical", "", "", "", ""),
    ("digital", "adj", "", "デジタルの", "digital", "", "", "", ""),
    ("die Digitalisierung", "noun", "die", "デジタル化", "digitization", "", "", "", ""),
    ("die Künstliche Intelligenz", "noun", "die", "人工知能", "artificial intelligence", "", "", "", ""),
    ("die KI", "noun", "die", "AI", "AI", "", "", "", ""),
    ("der Algorithmus", "noun", "der", "アルゴリズム", "algorithm", "", "", "die Algorithmen", ""),
    ("die Software", "noun", "die", "ソフトウェア", "software", "", "", "die Software", ""),
    ("die Hardware", "noun", "die", "ハードウェア", "hardware", "", "", "", ""),
    ("der Roboter", "noun", "der", "ロボット", "robot", "", "", "die Roboter", ""),
    ("die Automatisierung", "noun", "die", "自動化", "automation", "", "", "", ""),
    ("automatisch", "adj", "", "自動の", "automatic", "", "", "", ""),
    ("die Maschine", "noun", "die", "機械", "machine", "", "", "die Maschinen", ""),
    ("das Gerät", "noun", "das", "装置", "device", "", "", "die Geräte", ""),
    ("die Erfindung", "noun", "die", "発明", "invention", "", "", "die Erfindungen", ""),
    ("erfinden", "verb", "", "発明する", "to invent", "erfand", "hat erfunden", "", "irregular"),
    ("die Entdeckung", "noun", "die", "発見", "discovery", "", "", "die Entdeckungen", ""),
    ("entdecken", "verb", "", "発見する", "to discover", "entdeckte", "hat entdeckt", "", ""),
    ("die Mathematik", "noun", "die", "数学", "mathematics", "", "", "", ""),
    ("die Physik", "noun", "die", "物理学", "physics", "", "", "", ""),
    ("die Chemie", "noun", "die", "化学", "chemistry", "", "", "", ""),
    ("die Biologie", "noun", "die", "生物学", "biology", "", "", "", ""),
    ("die Medizin", "noun", "die", "医学", "medicine", "", "", "", ""),
    ("die Psychologie", "noun", "die", "心理学", "psychology", "", "", "", ""),
    ("die Soziologie", "noun", "die", "社会学", "sociology", "", "", "", ""),
    ("die Philosophie", "noun", "die", "哲学", "philosophy", "", "", "die Philosophien", ""),

    # ---------- Media & communication ----------
    ("die Medien", "noun", "die", "メディア", "media", "", "", "", "plural"),
    ("das Massenmedium", "noun", "das", "マスメディア", "mass medium", "", "", "die Massenmedien", ""),
    ("das Fernsehen", "noun", "das", "テレビ", "television", "", "", "", ""),
    ("der Sender", "noun", "der", "放送局", "broadcaster", "", "", "die Sender", ""),
    ("die Sendung", "noun", "die", "番組", "broadcast", "", "", "die Sendungen", ""),
    ("die Nachrichten", "noun", "die", "ニュース", "news", "", "", "", "plural"),
    ("der Bericht", "noun", "der", "報告", "report", "", "", "die Berichte", ""),
    ("berichten", "verb", "", "報告する", "to report", "berichtete", "hat berichtet", "", ""),
    ("die Reportage", "noun", "die", "ルポルタージュ", "report", "", "", "die Reportagen", ""),
    ("das Interview", "noun", "das", "インタビュー", "interview", "", "", "die Interviews", ""),
    ("interviewen", "verb", "", "インタビューする", "to interview", "interviewte", "hat interviewt", "", ""),
    ("die Schlagzeile", "noun", "die", "見出し", "headline", "", "", "die Schlagzeilen", ""),
    ("die Anzeige", "noun", "die", "広告／届け出", "ad, notification", "", "", "die Anzeigen", ""),
    ("der Artikel", "noun", "der", "記事／冠詞", "article", "", "", "die Artikel", ""),
    ("der Beitrag", "noun", "der", "投稿／寄与", "contribution", "", "", "die Beiträge", ""),
    ("der Kommentar", "noun", "der", "コメント", "comment", "", "", "die Kommentare", ""),
    ("kommentieren", "verb", "", "コメントする", "to comment", "kommentierte", "hat kommentiert", "", ""),
    ("die Werbung", "noun", "die", "宣伝", "advertising", "", "", "die Werbungen", ""),
    ("die Reklame", "noun", "die", "広告", "advertisement", "", "", "die Reklamen", ""),
    ("das Publikum", "noun", "das", "観客", "audience", "", "", "", ""),
    ("der Zuschauer", "noun", "der", "視聴者", "viewer", "", "", "die Zuschauer", ""),
    ("der Hörer", "noun", "der", "聴取者", "listener", "", "", "die Hörer", ""),
    ("der Leser", "noun", "der", "読者", "reader", "", "", "die Leser", ""),
    ("veröffentlichen", "verb", "", "発表する", "to publish", "veröffentlichte", "hat veröffentlicht", "", ""),
    ("die Veröffentlichung", "noun", "die", "発表", "publication", "", "", "die Veröffentlichungen", ""),
    ("der Verlag", "noun", "der", "出版社", "publisher", "", "", "die Verlage", ""),
    ("die Auflage", "noun", "die", "発行部数／版", "edition, circulation", "", "", "die Auflagen", ""),
    ("die Quelle", "noun", "die", "源／情報源", "source", "", "", "die Quellen", ""),
    ("die Recherche", "noun", "die", "調査", "research", "", "", "die Recherchen", ""),
    ("recherchieren", "verb", "", "調査する", "to research", "recherchierte", "hat recherchiert", "", ""),
    ("zitieren", "verb", "", "引用する", "to quote", "zitierte", "hat zitiert", "", ""),
    ("das Zitat", "noun", "das", "引用", "quote", "", "", "die Zitate", ""),
    ("die Pressemitteilung", "noun", "die", "プレスリリース", "press release", "", "", "die Pressemitteilungen", ""),
    ("die Konferenz", "noun", "die", "会議", "conference", "", "", "die Konferenzen", ""),
    ("die Pressekonferenz", "noun", "die", "記者会見", "press conference", "", "", "die Pressekonferenzen", ""),
    ("die Debatte", "noun", "die", "討論", "debate", "", "", "die Debatten", ""),
    ("debattieren", "verb", "", "討論する", "to debate", "debattierte", "hat debattiert", "", ""),
    ("argumentieren", "verb", "", "論じる", "to argue", "argumentierte", "hat argumentiert", "", ""),
    ("das Argument", "noun", "das", "論拠", "argument", "", "", "die Argumente", ""),
    ("die Stellungnahme", "noun", "die", "意見表明", "statement", "", "", "die Stellungnahmen", ""),

    # ---------- Education & learning (advanced) ----------
    ("das Bildungssystem", "noun", "das", "教育制度", "education system", "", "", "die Bildungssysteme", ""),
    ("die Schulpflicht", "noun", "die", "義務教育", "compulsory education", "", "", "", ""),
    ("der Lehrplan", "noun", "der", "学習指導要領", "curriculum", "", "", "die Lehrpläne", ""),
    ("das Stipendium", "noun", "das", "奨学金", "scholarship", "", "", "die Stipendien", ""),
    ("der Bewerber", "noun", "der", "応募者", "applicant", "", "", "die Bewerber", ""),
    ("die Bewerbung", "noun", "die", "応募", "application", "", "", "die Bewerbungen", ""),
    ("die Zulassung", "noun", "die", "入学許可", "admission", "", "", "die Zulassungen", ""),
    ("der NC", "noun", "der", "成績制限値", "numerus clausus", "", "", "", ""),
    ("der Numerus clausus", "noun", "der", "成績制限値", "numerus clausus", "", "", "", ""),
    ("die Promotion", "noun", "die", "博士号取得", "doctorate", "", "", "die Promotionen", ""),
    ("die Dissertation", "noun", "die", "博士論文", "dissertation", "", "", "die Dissertationen", ""),
    ("die Bachelorarbeit", "noun", "die", "学士論文", "bachelor's thesis", "", "", "die Bachelorarbeiten", ""),
    ("die Masterarbeit", "noun", "die", "修士論文", "master's thesis", "", "", "die Masterarbeiten", ""),
    ("die Doktorarbeit", "noun", "die", "博士論文", "doctoral thesis", "", "", "die Doktorarbeiten", ""),
    ("der Dozent", "noun", "der", "講師", "lecturer", "", "", "die Dozenten", "n-decl"),
    ("die Dozentin", "noun", "die", "講師（女）", "lecturer (f)", "", "", "die Dozentinnen", ""),
    ("der Tutor", "noun", "der", "チューター", "tutor", "", "", "die Tutoren", ""),
    ("die Fachrichtung", "noun", "die", "専攻分野", "field of study", "", "", "die Fachrichtungen", ""),
    ("die Spezialisierung", "noun", "die", "専門化", "specialization", "", "", "die Spezialisierungen", ""),
    ("sich spezialisieren", "verb", "", "専門化する", "to specialize", "spezialisierte sich", "hat sich spezialisiert", "", ""),
    ("die Weiterbildung", "noun", "die", "継続教育", "further training", "", "", "die Weiterbildungen", ""),
    ("die Fortbildung", "noun", "die", "再教育", "advanced training", "", "", "die Fortbildungen", ""),
    ("das lebenslange Lernen", "noun", "das", "生涯学習", "lifelong learning", "", "", "", ""),

    # ---------- Psychology & emotions ----------
    ("das Gefühl", "noun", "das", "感情", "feeling", "", "", "die Gefühle", ""),
    ("die Emotion", "noun", "die", "感情", "emotion", "", "", "die Emotionen", ""),
    ("emotional", "adj", "", "感情的な", "emotional", "", "", "", ""),
    ("die Stimmung", "noun", "die", "気分", "mood", "", "", "die Stimmungen", ""),
    ("die Laune", "noun", "die", "機嫌", "mood", "", "", "die Launen", ""),
    ("die Freude", "noun", "die", "喜び", "joy", "", "", "die Freuden", ""),
    ("sich freuen", "verb", "", "喜ぶ", "to be pleased", "freute sich", "hat sich gefreut", "", ""),
    ("die Trauer", "noun", "die", "悲しみ", "sorrow", "", "", "", ""),
    ("trauern", "verb", "", "悲しむ", "to mourn", "trauerte", "hat getrauert", "", ""),
    ("die Wut", "noun", "die", "怒り", "anger", "", "", "", ""),
    ("die Angst", "noun", "die", "不安", "fear", "", "", "die Ängste", ""),
    ("sich fürchten", "verb", "", "恐れる", "to be afraid", "fürchtete sich", "hat sich gefürchtet", "", ""),
    ("die Sorge", "noun", "die", "心配", "worry", "", "", "die Sorgen", ""),
    ("sich sorgen", "verb", "", "心配する", "to worry", "sorgte sich", "hat sich gesorgt", "", ""),
    ("der Stress", "noun", "der", "ストレス", "stress", "", "", "", ""),
    ("gestresst", "adj", "", "ストレス状態の", "stressed", "", "", "", ""),
    ("sich entspannen", "verb", "", "リラックスする", "to relax", "entspannte sich", "hat sich entspannt", "", ""),
    ("die Entspannung", "noun", "die", "リラックス", "relaxation", "", "", "die Entspannungen", ""),
    ("die Depression", "noun", "die", "うつ病", "depression", "", "", "die Depressionen", ""),
    ("die Einsamkeit", "noun", "die", "孤独", "loneliness", "", "", "", ""),
    ("einsam", "adj", "", "孤独な", "lonely", "", "", "", ""),
    ("die Sehnsucht", "noun", "die", "憧れ", "longing", "", "", "die Sehnsüchte", ""),
    ("die Hoffnung", "noun", "die", "希望", "hope", "", "", "die Hoffnungen", ""),
    ("hoffen", "verb", "", "願う", "to hope", "hoffte", "hat gehofft", "", ""),
    ("die Enttäuschung", "noun", "die", "失望", "disappointment", "", "", "die Enttäuschungen", ""),
    ("enttäuscht", "adj", "", "失望した", "disappointed", "", "", "", ""),
    ("der Stolz", "noun", "der", "誇り", "pride", "", "", "", ""),
    ("die Scham", "noun", "die", "恥", "shame", "", "", "", ""),
    ("sich schämen", "verb", "", "恥じる", "to be ashamed", "schämte sich", "hat sich geschämt", "", ""),
    ("die Eifersucht", "noun", "die", "嫉妬", "jealousy", "", "", "", ""),
    ("eifersüchtig", "adj", "", "嫉妬深い", "jealous", "", "", "", ""),
    ("das Mitleid", "noun", "das", "同情", "sympathy", "", "", "", ""),
    ("die Sympathie", "noun", "die", "好感", "sympathy", "", "", "die Sympathien", ""),
    ("die Empathie", "noun", "die", "共感", "empathy", "", "", "", ""),
    ("das Selbstbewusstsein", "noun", "das", "自信", "self-confidence", "", "", "", ""),
    ("selbstbewusst", "adj", "", "自信のある", "self-confident", "", "", "", ""),
    ("die Persönlichkeit", "noun", "die", "人格", "personality", "", "", "die Persönlichkeiten", ""),
    ("der Charakter", "noun", "der", "性格", "character", "", "", "die Charaktere", ""),
    ("das Verhalten", "noun", "das", "態度", "behavior", "", "", "", ""),
    ("sich verhalten", "verb", "", "振る舞う", "to behave", "verhielt sich", "hat sich verhalten", "", "irregular"),

    # ---------- Common B2 verbs ----------
    ("erlauben", "verb", "", "許可する", "to allow", "erlaubte", "hat erlaubt", "", ""),
    ("ermöglichen", "verb", "", "可能にする", "to enable", "ermöglichte", "hat ermöglicht", "", ""),
    ("erfordern", "verb", "", "要求する", "to require", "erforderte", "hat erfordert", "", ""),
    ("verlangen", "verb", "", "要求する", "to demand", "verlangte", "hat verlangt", "", ""),
    ("erwarten", "verb", "", "期待する", "to expect", "erwartete", "hat erwartet", "", ""),
    ("die Erwartung", "noun", "die", "期待", "expectation", "", "", "die Erwartungen", ""),
    ("annehmen", "verb", "", "仮定する／受け入れる", "to assume, to accept", "nahm an", "hat angenommen", "", "irregular"),
    ("ablehnen", "verb", "", "拒否する", "to reject", "lehnte ab", "hat abgelehnt", "", ""),
    ("zustimmen", "verb", "", "同意する", "to agree", "stimmte zu", "hat zugestimmt", "", ""),
    ("widersprechen", "verb", "", "反論する", "to contradict", "widersprach", "hat widersprochen", "", "irregular"),
    ("akzeptieren", "verb", "", "受け入れる", "to accept", "akzeptierte", "hat akzeptiert", "", ""),
    ("respektieren", "verb", "", "尊重する", "to respect", "respektierte", "hat respektiert", "", ""),
    ("der Respekt", "noun", "der", "尊敬", "respect", "", "", "", ""),
    ("kritisieren", "verb", "", "批判する", "to criticize", "kritisierte", "hat kritisiert", "", ""),
    ("die Kritik", "noun", "die", "批判", "criticism", "", "", "die Kritiken", ""),
    ("loben", "verb", "", "ほめる", "to praise", "lobte", "hat gelobt", "", ""),
    ("das Lob", "noun", "das", "賞賛", "praise", "", "", "", ""),
    ("beurteilen", "verb", "", "評価する", "to judge", "beurteilte", "hat beurteilt", "", ""),
    ("die Beurteilung", "noun", "die", "評価", "assessment", "", "", "die Beurteilungen", ""),
    ("bewerten", "verb", "", "評価する", "to evaluate", "bewertete", "hat bewertet", "", ""),
    ("die Bewertung", "noun", "die", "評価", "evaluation", "", "", "die Bewertungen", ""),
    ("schätzen", "verb", "", "見積もる／評価する", "to estimate, to value", "schätzte", "hat geschätzt", "", ""),
    ("die Schätzung", "noun", "die", "見積もり", "estimate", "", "", "die Schätzungen", ""),
    ("vermeiden", "verb", "", "避ける", "to avoid", "vermied", "hat vermieden", "", "irregular"),
    ("verzichten", "verb", "", "あきらめる", "to give up", "verzichtete", "hat verzichtet", "", ""),
    ("ignorieren", "verb", "", "無視する", "to ignore", "ignorierte", "hat ignoriert", "", ""),
    ("berücksichtigen", "verb", "", "考慮する", "to consider", "berücksichtigte", "hat berücksichtigt", "", ""),
    ("betrachten", "verb", "", "考察する／観察する", "to consider, to observe", "betrachtete", "hat betrachtet", "", ""),
    ("beobachten", "verb", "", "観察する", "to observe", "beobachtete", "hat beobachtet", "", ""),
    ("die Beobachtung", "noun", "die", "観察", "observation", "", "", "die Beobachtungen", ""),
    ("untersuchen", "verb", "", "調査する", "to investigate", "untersuchte", "hat untersucht", "", ""),
    ("analysieren", "verb", "", "分析する", "to analyze", "analysierte", "hat analysiert", "", ""),
    ("die Analyse", "noun", "die", "分析", "analysis", "", "", "die Analysen", ""),
    ("auswerten", "verb", "", "評価する／集計する", "to evaluate, to analyze", "wertete aus", "hat ausgewertet", "", ""),
    ("die Auswertung", "noun", "die", "評価／集計", "evaluation", "", "", "die Auswertungen", ""),
    ("zusammenfassen", "verb", "", "要約する", "to summarize", "fasste zusammen", "hat zusammengefasst", "", ""),
    ("die Zusammenfassung", "noun", "die", "要約", "summary", "", "", "die Zusammenfassungen", ""),
    ("schlussfolgern", "verb", "", "結論づける", "to conclude", "schlussfolgerte", "hat geschlussfolgert", "", ""),
    ("die Schlussfolgerung", "noun", "die", "結論", "conclusion", "", "", "die Schlussfolgerungen", ""),
    ("hinzufügen", "verb", "", "追加する", "to add", "fügte hinzu", "hat hinzugefügt", "", ""),
    ("entfernen", "verb", "", "取り除く", "to remove", "entfernte", "hat entfernt", "", ""),
    ("ersetzen", "verb", "", "置き換える", "to replace", "ersetzte", "hat ersetzt", "", ""),
    ("vertreten", "verb", "", "代理する／代表する", "to represent", "vertrat", "hat vertreten", "", "irregular"),
    ("repräsentieren", "verb", "", "代表する", "to represent", "repräsentierte", "hat repräsentiert", "", ""),
    ("verhandeln", "verb", "", "交渉する", "to negotiate", "verhandelte", "hat verhandelt", "", ""),
    ("die Verhandlung", "noun", "die", "交渉", "negotiation", "", "", "die Verhandlungen", ""),
    ("überzeugen", "verb", "", "説得する", "to convince", "überzeugte", "hat überzeugt", "", ""),
    ("die Überzeugung", "noun", "die", "信念", "conviction", "", "", "die Überzeugungen", ""),
    ("beeinflussen", "verb", "", "影響する", "to influence", "beeinflusste", "hat beeinflusst", "", ""),
    ("auswirken", "verb", "", "影響する", "to affect", "wirkte aus", "hat ausgewirkt", "", ""),
    ("beitragen", "verb", "", "貢献する", "to contribute", "trug bei", "hat beigetragen", "", "irregular"),
    ("teilnehmen", "verb", "", "参加する", "to take part", "nahm teil", "hat teilgenommen", "", "irregular"),
    ("die Teilnahme", "noun", "die", "参加", "participation", "", "", "", ""),
    ("der Teilnehmer", "noun", "der", "参加者", "participant", "", "", "die Teilnehmer", ""),
    ("ermitteln", "verb", "", "突き止める", "to determine", "ermittelte", "hat ermittelt", "", ""),
    ("herausfinden", "verb", "", "見つけ出す", "to find out", "fand heraus", "hat herausgefunden", "", "irregular"),
    ("feststellen", "verb", "", "確認する", "to determine", "stellte fest", "hat festgestellt", "", ""),
    ("nachweisen", "verb", "", "立証する", "to prove", "wies nach", "hat nachgewiesen", "", "irregular"),
    ("bezweifeln", "verb", "", "疑う", "to doubt", "bezweifelte", "hat bezweifelt", "", ""),
    ("bestätigen", "verb", "", "確認する", "to confirm", "bestätigte", "hat bestätigt", "", ""),
    ("die Bestätigung", "noun", "die", "確認", "confirmation", "", "", "die Bestätigungen", ""),
    ("widerlegen", "verb", "", "反証する", "to refute", "widerlegte", "hat widerlegt", "", ""),
    ("beweisen", "verb", "", "証明する", "to prove", "bewies", "hat bewiesen", "", "irregular"),
    ("zeigen", "verb", "", "示す", "to show", "zeigte", "hat gezeigt", "", ""),
    ("andeuten", "verb", "", "ほのめかす", "to imply", "deutete an", "hat angedeutet", "", ""),
    ("voraussetzen", "verb", "", "前提とする", "to presuppose", "setzte voraus", "hat vorausgesetzt", "", ""),
    ("ausgehen", "verb", "", "前提とする／出かける", "to assume, to go out", "ging aus", "ist ausgegangen", "", "irregular"),
    ("verfolgen", "verb", "", "追跡する", "to pursue", "verfolgte", "hat verfolgt", "", ""),
    ("verfügen", "verb", "", "～を所有する", "to have at disposal", "verfügte", "hat verfügt", "", "+ über"),
    ("die Verfügung", "noun", "die", "支配／処分", "disposal, decree", "", "", "die Verfügungen", ""),

    # ---------- Connectors & advanced grammar ----------
    ("einerseits", "adv", "", "一方では", "on the one hand", "", "", "", ""),
    ("andererseits", "adv", "", "他方では", "on the other hand", "", "", "", ""),
    ("zwar", "adv", "", "確かに", "indeed", "", "", "", ""),
    ("dennoch", "adv", "", "それにもかかわらず", "nevertheless", "", "", "", ""),
    ("jedoch", "adv", "", "しかし", "however", "", "", "", ""),
    ("hingegen", "adv", "", "それに対して", "on the other hand", "", "", "", ""),
    ("dagegen", "adv", "", "それに対して", "on the contrary", "", "", "", ""),
    ("allerdings", "adv", "", "しかしながら", "however", "", "", "", ""),
    ("indessen", "adv", "", "とはいえ", "meanwhile, however", "", "", "", ""),
    ("vielmehr", "adv", "", "むしろ", "rather", "", "", "", ""),
    ("außerdem", "adv", "", "さらに", "moreover", "", "", "", ""),
    ("zudem", "adv", "", "さらに", "moreover", "", "", "", ""),
    ("ferner", "adv", "", "さらに", "furthermore", "", "", "", ""),
    ("darüber hinaus", "adv", "", "それを超えて", "beyond that", "", "", "", ""),
    ("infolge", "prep", "", "～の結果として", "as a result of", "", "", "", "+Gen"),
    ("infolgedessen", "adv", "", "その結果", "consequently", "", "", "", ""),
    ("folglich", "adv", "", "結果として", "therefore", "", "", "", ""),
    ("somit", "adv", "", "それゆえ", "thus", "", "", "", ""),
    ("hinsichtlich", "prep", "", "～に関して", "regarding", "", "", "", "+Gen"),
    ("bezüglich", "prep", "", "～に関する", "regarding", "", "", "", "+Gen"),
    ("aufgrund", "prep", "", "～のために", "due to", "", "", "", "+Gen"),
    ("zugunsten", "prep", "", "～のために", "in favor of", "", "", "", "+Gen"),
    ("zuungunsten", "prep", "", "～の不利になる", "to the disadvantage of", "", "", "", "+Gen"),
    ("mittels", "prep", "", "～によって", "by means of", "", "", "", "+Gen"),
    ("anhand", "prep", "", "～に基づいて", "based on", "", "", "", "+Gen"),
    ("gemäß", "prep", "", "～に従って", "according to", "", "", "", "+Dat"),
    ("entsprechend", "prep", "", "～に応じて", "according to", "", "", "", "+Dat"),
    ("laut", "prep", "", "～によると", "according to", "", "", "", "+Gen/Dat"),
    ("zufolge", "prep", "", "～によると", "according to", "", "", "", "+Dat (post)"),
    ("nämlich", "adv", "", "すなわち", "namely", "", "", "", ""),
    ("etwa", "adv", "", "おおよそ／例えば", "approximately, for example", "", "", "", ""),
    ("beziehungsweise", "conj", "", "あるいは", "respectively, or", "", "", "", "bzw."),
    ("bzw.", "conj", "", "あるいは", "respectively", "", "", "", "abbr"),
    ("d. h.", "phrase", "", "つまり", "i.e.", "", "", "", "abbr"),
    ("das heißt", "phrase", "", "つまり", "that means", "", "", "", ""),
    ("zum einen", "phrase", "", "一つには", "for one thing", "", "", "", ""),
    ("zum anderen", "phrase", "", "もう一つには", "for another", "", "", "", ""),
    ("im Übrigen", "phrase", "", "ところで", "by the way", "", "", "", ""),
    ("im Gegensatz zu", "phrase", "", "～と対照的に", "in contrast to", "", "", "", ""),
    ("im Vergleich zu", "phrase", "", "～と比較して", "in comparison to", "", "", "", ""),
    ("im Wesentlichen", "phrase", "", "本質的に", "essentially", "", "", "", ""),
    ("in der Tat", "phrase", "", "実際に", "indeed", "", "", "", ""),
    ("ohne Zweifel", "phrase", "", "疑いなく", "without doubt", "", "", "", ""),
    ("im Allgemeinen", "phrase", "", "一般に", "generally", "", "", "", ""),

    # ---------- B2 adjectives ----------
    ("abstrakt", "adj", "", "抽象的な", "abstract", "", "", "", ""),
    ("konkret", "adj", "", "具体的な", "concrete", "", "", "", ""),
    ("relevant", "adj", "", "関連する", "relevant", "", "", "", ""),
    ("irrelevant", "adj", "", "無関係な", "irrelevant", "", "", "", ""),
    ("wesentlich", "adj", "", "本質的な", "essential", "", "", "", ""),
    ("entscheidend", "adj", "", "決定的な", "decisive", "", "", "", ""),
    ("wirksam", "adj", "", "効果的な", "effective", "", "", "", ""),
    ("erfolgreich", "adj", "", "成功した", "successful", "", "", "", ""),
    ("erfolglos", "adj", "", "失敗した", "unsuccessful", "", "", "", ""),
    ("zuverlässig", "adj", "", "信頼できる", "reliable", "", "", "", ""),
    ("unzuverlässig", "adj", "", "信頼できない", "unreliable", "", "", "", ""),
    ("verlässlich", "adj", "", "頼れる", "dependable", "", "", "", ""),
    ("kompetent", "adj", "", "有能な", "competent", "", "", "", ""),
    ("inkompetent", "adj", "", "無能な", "incompetent", "", "", "", ""),
    ("qualifiziert", "adj", "", "有資格の", "qualified", "", "", "", ""),
    ("erfahren", "adj", "", "経験豊富な", "experienced", "", "", "", ""),
    ("anspruchsvoll", "adj", "", "要求の高い", "demanding", "", "", "", ""),
    ("flexibel", "adj", "", "柔軟な", "flexible", "", "", "", ""),
    ("starr", "adj", "", "硬直した", "rigid", "", "", "", ""),
    ("vielfältig", "adj", "", "多様な", "diverse", "", "", "", ""),
    ("unterschiedlich", "adj", "", "異なる", "different", "", "", "", ""),
    ("einheitlich", "adj", "", "統一された", "uniform", "", "", "", ""),
    ("gemeinsam", "adj", "", "共通の／一緒の", "common, joint", "", "", "", ""),
    ("getrennt", "adj", "", "別々の", "separate", "", "", "", ""),
    ("zusätzlich", "adj/adv", "", "追加の", "additional", "", "", "", ""),
    ("ausreichend", "adj", "", "十分な", "sufficient", "", "", "", ""),
    ("unzureichend", "adj", "", "不十分な", "insufficient", "", "", "", ""),
    ("überflüssig", "adj", "", "余分な", "superfluous", "", "", "", ""),
    ("dringend", "adj", "", "緊急の", "urgent", "", "", "", ""),
    ("unverzüglich", "adj/adv", "", "即座に", "immediate", "", "", "", ""),
    ("sofortig", "adj", "", "即時の", "immediate", "", "", "", ""),
    ("vorläufig", "adj", "", "暫定の", "preliminary", "", "", "", ""),
    ("endgültig", "adj", "", "最終的な", "final", "", "", "", ""),
    ("offiziell", "adj", "", "公式の", "official", "", "", "", ""),
    ("inoffiziell", "adj", "", "非公式の", "unofficial", "", "", "", ""),
    ("formal", "adj", "", "正式な", "formal", "", "", "", ""),
    ("informell", "adj", "", "非公式の", "informal", "", "", "", ""),
    ("gesetzlich", "adj", "", "法的な", "legal", "", "", "", ""),
    ("illegal", "adj", "", "違法な", "illegal", "", "", "", ""),
    ("legal", "adj", "", "合法の", "legal", "", "", "", ""),
    ("öffentlich", "adj", "", "公の", "public", "", "", "", ""),
    ("privat", "adj", "", "個人の", "private", "", "", "", ""),
    ("anonym", "adj", "", "匿名の", "anonymous", "", "", "", ""),
    ("vertraulich", "adj", "", "秘密の", "confidential", "", "", "", ""),
    ("transparent", "adj", "", "透明な", "transparent", "", "", "", ""),
    ("klar", "adj", "", "明確な", "clear", "", "", "", ""),
    ("unklar", "adj", "", "不明確な", "unclear", "", "", "", ""),
    ("eindeutig", "adj", "", "明白な", "unambiguous", "", "", "", ""),
    ("zweideutig", "adj", "", "曖昧な", "ambiguous", "", "", "", ""),
    ("offensichtlich", "adj", "", "明らかな", "obvious", "", "", "", ""),
    ("vermutlich", "adj/adv", "", "おそらく", "presumably", "", "", "", ""),
    ("wahrscheinlich", "adj/adv", "", "おそらく", "probable", "", "", "", ""),
    ("unwahrscheinlich", "adj/adv", "", "ありそうもない", "improbable", "", "", "", ""),
    ("sicher", "adj/adv", "", "確実な", "certain", "", "", "", ""),
    ("unsicher", "adj", "", "不確かな", "uncertain", "", "", "", ""),
    ("zweifelhaft", "adj", "", "疑わしい", "doubtful", "", "", "", ""),
    ("fraglich", "adj", "", "疑問の", "questionable", "", "", "", ""),
    ("ausgeschlossen", "adj", "", "あり得ない", "impossible", "", "", "", ""),
    ("denkbar", "adj", "", "考えられる", "conceivable", "", "", "", ""),
    ("realistisch", "adj", "", "現実的な", "realistic", "", "", "", ""),
    ("unrealistisch", "adj", "", "非現実的な", "unrealistic", "", "", "", ""),
    ("ideal", "adj", "", "理想的な", "ideal", "", "", "", ""),
    ("perfekt", "adj", "", "完璧な", "perfect", "", "", "", ""),
    ("optimal", "adj", "", "最適な", "optimal", "", "", "", ""),
    ("maximal", "adj", "", "最大の", "maximum", "", "", "", ""),
    ("minimal", "adj", "", "最小の", "minimum", "", "", "", ""),
    ("durchschnittlich", "adj", "", "平均的な", "average", "", "", "", ""),
    ("überdurchschnittlich", "adj", "", "平均以上の", "above average", "", "", "", ""),
    ("unterdurchschnittlich", "adj", "", "平均以下の", "below average", "", "", "", ""),
]

THEMES = {
    "Familie": [
        "family", "father", "mother", "child", "parent",
        "家族", "父", "母", "子供", "親",
        "Familie", "Vater", "Mutter", "Kind", "Eltern", "Geschwister",
        "Mann", "Frau", "Beziehung",
    ],
    "Essen": [
        "food", "eat", "drink", "meal",
        "食事", "食べる", "飲む",
        "Essen", "essen", "trinken", "Mahlzeit",
    ],
    "Arbeit": [
        "work", "job", "office", "boss", "colleague", "employee", "company",
        "career", "salary", "interview", "application", "entrepreneur",
        "仕事", "職業", "会社", "上司", "同僚", "給与", "面接", "応募",
        "経営者", "自営",
        "Arbeit", "arbeiten", "Beruf", "Büro", "Chef", "Kollege",
        "Mitarbeiter", "Firma", "Unternehmen", "Stelle", "Bewerbung",
        "Vorstellungsgespräch", "Gehalt", "Karriere", "Vertrag", "Kunde",
        "Unternehmer", "selbstständig", "Bewerber",
    ],
    "Wirtschaft": [
        "economy", "market", "trade", "industry", "business", "company",
        "profit", "loss", "investment", "stock", "share", "growth",
        "経済", "市場", "貿易", "産業", "ビジネス", "利益", "損失", "投資",
        "株", "成長", "競争", "輸出", "輸入",
        "Wirtschaft", "Markt", "Handel", "Industrie", "Konkurrenz",
        "Wettbewerb", "Gewinn", "Verlust", "Investition", "Aktie",
        "Aktienmarkt", "Wachstum", "Inflation", "Export", "Import",
        "exportieren", "importieren", "Produktion", "produzieren", "herstellen",
        "Hersteller", "Branche", "Sektor", "Lieferung", "Lieferant",
        "Kunde", "Marketing", "Werbung", "Marke", "Strategie", "Effizienz",
        "Produktivität", "Innovation", "Globalisierung", "Krise", "Umsatz",
        "Aktionär", "Marktforschung",
    ],
    "Politik": [
        "politics", "government", "election", "party", "law", "right",
        "policy", "democracy", "constitution",
        "政治", "政府", "選挙", "政党", "法律", "民主主義", "憲法",
        "Politik", "Regierung", "Wahl", "Partei", "Gesetz", "Recht",
        "Demokratie", "Verfassung", "Grundgesetz", "Behörde", "Amt",
        "Verwaltung", "Bürokratie", "Antrag", "beantragen", "Genehmigung",
        "Verbot", "Strafe", "Verbrechen", "Diebstahl", "Mord", "Gericht",
        "Richter", "Urteil", "Justiz", "Polizei", "Krieg", "Frieden",
        "Konflikt", "Gewalt", "Sicherheit", "Pflicht", "Freiheit",
        "Bürger", "Staatsbürgerschaft", "Integration", "Diskriminierung",
        "Gleichberechtigung", "Minderheit", "Mehrheit", "Pressefreiheit",
        "Meinungsfreiheit",
    ],
    "Umwelt": [
        "environment", "climate", "pollution", "energy", "nature",
        "sustainable", "recycle", "emission", "renewable",
        "環境", "気候", "汚染", "エネルギー", "持続可能", "リサイクル",
        "再生可能",
        "Umwelt", "Umweltschutz", "Klimawandel", "Erderwärmung",
        "Verschmutzung", "Treibhausgase", "CO2", "Emission", "Energie",
        "Solaranlage", "Windkraft", "Wasserkraft", "Atomkraft", "Kernenergie",
        "erneuerbar", "nachhaltig", "Nachhaltigkeit", "Rohstoff", "Ressource",
        "Verbrauch", "verbrauchen", "Konsum", "recyceln", "Recycling",
        "Mülltrennung", "Plastikmüll", "Schutz", "schützen", "Zerstörung",
        "Katastrophe", "Erdbeben", "Überschwemmung", "Dürre", "Waldbrand",
    ],
    "Wissenschaft": [
        "science", "research", "study", "experiment", "technology",
        "method", "data", "theory",
        "科学", "研究", "実験", "技術", "データ",
        "Wissenschaft", "wissenschaftlich", "Forschung", "forschen", "Forscher",
        "Experiment", "experimentieren", "Ergebnis", "Resultat", "Methode",
        "Studie", "Untersuchung", "Statistik", "Daten", "Technologie",
        "Technik", "Digitalisierung", "Künstliche Intelligenz", "KI",
        "Algorithmus", "Software", "Hardware", "Roboter", "Automatisierung",
        "Maschine", "Erfindung", "erfinden", "Entdeckung", "entdecken",
        "Mathematik", "Physik", "Chemie", "Biologie", "Medizin", "Psychologie",
        "Soziologie", "Philosophie",
    ],
    "Medien": [
        "media", "news", "press", "newspaper", "television", "magazine",
        "article", "report", "broadcast",
        "メディア", "ニュース", "報道", "新聞", "テレビ", "雑誌", "記事",
        "Medien", "Massenmedium", "Fernsehen", "Sender", "Sendung",
        "Nachrichten", "Bericht", "berichten", "Reportage", "Interview",
        "Schlagzeile", "Anzeige", "Artikel", "Beitrag", "Kommentar",
        "kommentieren", "Werbung", "Reklame", "Publikum", "Zuschauer",
        "Hörer", "Leser", "veröffentlichen", "Verlag", "Quelle", "Recherche",
        "Zitat", "zitieren", "Pressemitteilung", "Pressekonferenz", "Debatte",
        "debattieren", "argumentieren", "Argument", "Stellungnahme",
    ],
    "Gefühle": [
        "feeling", "emotion", "joy", "sad", "angry", "happy", "fear",
        "stress", "love", "hope", "pride",
        "感情", "喜び", "悲しみ", "怒り", "幸せ", "恐れ", "ストレス", "愛",
        "希望", "誇り",
        "Gefühl", "Emotion", "Stimmung", "Laune", "Freude", "freuen",
        "Trauer", "trauern", "Wut", "Angst", "fürchten", "Sorge", "sorgen",
        "Stress", "gestresst", "entspannen", "Entspannung", "Depression",
        "Einsamkeit", "einsam", "Sehnsucht", "Hoffnung", "hoffen",
        "Enttäuschung", "enttäuscht", "Stolz", "Scham", "schämen",
        "Eifersucht", "eifersüchtig", "Mitleid", "Sympathie", "Empathie",
        "Selbstbewusstsein", "Persönlichkeit", "Charakter", "Verhalten",
    ],
    "Bildung": [
        "education", "school", "student", "teacher", "university", "degree",
        "exam", "study", "learn", "lecture",
        "教育", "学校", "学生", "先生", "大学", "学位", "試験", "勉強",
        "Bildung", "Bildungssystem", "Schulpflicht", "Lehrplan", "Stipendium",
        "Bewerber", "Bewerbung", "Zulassung", "NC", "Numerus", "Promotion",
        "Dissertation", "Bachelorarbeit", "Masterarbeit", "Doktorarbeit",
        "Dozent", "Tutor", "Fachrichtung", "Spezialisierung", "spezialisieren",
        "Weiterbildung", "Fortbildung", "lebenslange", "Lernen",
        "Schule", "Universität", "studieren", "lernen", "Klausur", "Vorlesung",
        "Seminar", "Semester",
    ],
}

_ASCII_WORD = re.compile(r"^[a-zA-Z]+$")


def has_keyword(haystack: str, keyword: str) -> bool:
    if _ASCII_WORD.fullmatch(keyword):
        return bool(re.search(rf"\b{re.escape(keyword)}\b", haystack, re.IGNORECASE))
    return keyword in haystack


def compute_tags(german: str, pos: str, ja: str, en: str, level: str) -> list[str]:
    haystack = " ".join(filter(None, [german, ja, en]))
    tags: list[str] = []
    for theme, kws in THEMES.items():
        for kw in kws:
            if has_keyword(haystack, kw):
                tags.append(theme)
                break
    if pos:
        tags.append(pos.strip().lower())
    if level:
        tags.append(level)
    seen: set[str] = set()
    out = []
    for t in tags:
        if t not in seen:
            seen.add(t)
            out.append(t)
    return out


def main():
    wb = load_workbook(MASTER)
    ws = wb[SHEET]
    header = [c.value for c in ws[1]]
    if "Tags" not in header:
        raise RuntimeError("Tags column missing")

    existing_terms: set[str] = set()
    for row in ws.iter_rows(min_row=2, values_only=True):
        g = row[0]
        if g and str(g).strip():
            existing_terms.add(str(g).strip().lower())

    start_row = ws.max_row + 1
    added = 0
    skipped = 0
    for g, pos, art, ja, en, prat, pii, plural, notes in B2_ENTRIES:
        if g.strip().lower() in existing_terms:
            skipped += 1
            continue
        tags = compute_tags(g, pos, ja, en, LEVEL)
        row_data = [g, pos, art, ja, en, 1, prat, pii, plural, notes, ", ".join(tags)]
        for col_idx, value in enumerate(row_data, start=1):
            ws.cell(row=start_row + added, column=col_idx, value=value)
        added += 1
        existing_terms.add(g.strip().lower())

    wb.save(MASTER)
    print(f"Added {added} B2 entries. Skipped {skipped} (already present). Total rows now: {ws.max_row}.")


if __name__ == "__main__":
    main()
